### ISSUE TITLE
App won't install on Xperia Z3(SOL26)/Android5.0

### ISSUE THREAD

**Issue by vroad** [rovo89/Xposed#107]
Whenever I try to install/update apps from Google Play, installation fails with error code 504.
I've tried changing SELinux mode to permissive, but that doesn't fix this error.

Everything else seems to work fine, though performance penalty is noticeable in some apps, such as Google Play. Scrolling always stutter when Xposed is enabled.

```
I/PackageManager( 1337): Running dexopt on: /data/app/imoblife.androidsensorbox-1/base.apk pkg=imoblife.androidsensorbox isa=arm vmSafeMode=false

I/ActivityManager( 1337): Process com.sonymobile.dlna (pid 11126) has died

I/dex2oat (12569): /system/bin/dex2oat --zip-fd=6 --zip-location=/data/app/imoblife.androidsensorbox-1/base.apk --oat-fd=7 --oat-location=/data/dalvik-cache/arm/data@app@imoblife.androidsensorbox-1@base.apk@classes.dex --instruction-set=arm --instruction-set-features=div --runtime-arg -Xms64m --runtime-arg -Xmx512m

W/dex2oat (12569): Could not create image space with image file '/system/framework/boot.art'. Attempting to fall back to imageless running. Error was: Only the zygote can create the global boot image.

E/installd(  602): DexInv: --- END '/data/app/imoblife.androidsensorbox-1/base.apk' --- status=0x000b, process failed

W/PackageManager( 1337): Package couldn't be installed in /data/app/imoblife.androidsensorbox-1

W/PackageManager( 1337): com.android.server.pm.PackageManagerException: scanPackageLI

W/PackageManager( 1337): 	at com.android.server.pm.PackageManagerService.scanPackageDirtyLI(PackageManagerService.java:6200)

W/PackageManager( 1337): 	at com.android.server.pm.PackageManagerService.scanPackageLI(PackageManagerService.java:5529)

W/PackageManager( 1337): 	at com.android.server.pm.PackageManagerService.installNewPackageLI(PackageManagerService.java:10568)

W/PackageManager( 1337): 	at com.android.server.pm.PackageManagerService.installPackageLI(PackageManagerService.java:11135)

W/PackageManager( 1337): 	at com.android.server.pm.PackageManagerService.access$2400(PackageManagerService.java:251)

W/PackageManager( 1337): 	at com.android.server.pm.PackageManagerService$7.run(PackageManagerService.java:8960)

W/PackageManager( 1337): 	at android.os.Handler.handleCallback(Handler.java:739)

W/PackageManager( 1337): 	at android.os.Handler.dispatchMessage(Handler.java:95)

W/PackageManager( 1337): 	at android.os.Looper.loop(Looper.java:211)

W/PackageManager( 1337): 	at android.os.HandlerThread.run(HandlerThread.java:61)

W/PackageManager( 1337): 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by rovo89** [comment]
`Could not create image space with image file '/system/framework/boot.art'. Attempting to fall back to imageless running. Error was: Only the zygote can create the global boot image.`

This sounds like the issue is already at boot time when the boot image should be created. If that doesn't succeed, you usually have a bootloop, but I could also imagine that a ROMs falls back to interpreting the code, which is slower than usual. That could explain the stuttering.

Could you please execute "adb logcat -v time > logcat.txt" and then do a soft reboot (execute "adb shell stop;start")? Once the system has rebooted, press Ctrl+C for the first command. That should hopefully produce a log that shows what's going wrong with the boot image.

**Comment by rovo89** [comment]
Closing due to the lack of response...

**Comment by vroad** [comment]
@rovo89  Execuse me but I got logcat today. Please reopen this issue. https://gist.github.com/vroad/c562ddf6ac232181d0b0420a30bffdba

Unfortunately this issue still persists on xposed v85. ART is crashing again and again with the same message: `Abort message: 'art/runtime/runtime.cc:839] Check failed: options->boot_class_path_ != nullptr '`

**Comment by vroad** [comment]
I've installed from TWRP (instead of PhilZ Touch) wiped cache/dalvik cache. It's working now somehow. Did I install xposed in a wrong way?

**Comment by rovo89** [comment]
Unfortunately, the log you posted starts to late to see which issues occured while compiling the boot image. The message you posted is just a follow-up error. I don't have experience with PhilZ Touch recovery, but I also haven't heard about issues with it...
