### ISSUE TITLE
9 Apps Optimizing after Reboot

### ISSUE THREAD

**Issue by AntikerTa** [rovo89/Xposed#108]
[Xposed Logcat.pdf](https://github.com/rovo89/Xposed/files/74003/Xposed.Logcat.pdf)
Hello, 

on HTC One A9 with 6.0.1 Marshmallow 9 Apps every single time after Reboot will optimized.

**Comment by Zackptg5** [comment]
Try wiping dalvik cache, booting. Then doing a power off, not a reboot. Then turn your phone off and power off once more. Upon booting up this time, there should be no apps optimizing

**Comment by AntikerTa** [comment]
Have tried it. Wiping Dalvik Cache with TWRP. After Reboot and optimizing alle Apps i have made 5x Power Off and Power On. But it is not working. Every Time the 9 Apps will optimize after Reboot.

**Comment by AntikerTa** [comment]
Have tried it. Wiping Dalvik Cache with TWRP. After Reboot and optimizing alle Apps i have made 5x Power Off and Power On. But it is not working. Every Time the 9 Apps will optimize after Reboot.

**Comment by rovo89** [comment]
The PDF is hard to read, better use pastebin or something like that next time.
I saw one issue in the log which could be related to this, please refer to https://github.com/rovo89/android_art/issues/21
