### ISSUE TITLE
Sony Z5p dual - Album stopped after flashing xposed-v79-sdk22-arm64.zip

### ISSUE THREAD

**Issue by yanggq** [rovo89/Xposed#109]
I flashed xposed-v79-sdk22-arm64.zip on my Sony Z5 p, the device started successfully, but the album app can not be started.

Before that I flashed the AndroPlus Kernel and TWRP E6883 version from: https://dl.androplus.org/Xperia%20Z5%20Premium_E6853. 

If uninstall XPosed with xposed-uninstaller-20150831-arm64.zip, Album works again.
romracer version of XPosed doesn't help.

Is the any way to fix it or workaroud? Thanks in advance!

**Comment by rovo89** [comment]
Can you please post a logcat of the failing app start?

**Comment by yanggq** [comment]
Hi rovo99,

here's the logcat I catched by cmd:
logcat -b main -v time > /sdcard1/main3.txt &

[main3.txt](https://github.com/rovo89/Xposed/files/75923/main3.txt)

the crashdump.zip are the files I found under /data/crashdata.
[crashdump.zip](https://github.com/rovo89/Xposed/files/75922/crashdump.zip)

I don't know if this will help ? thank you!

BTW, Happy new year !

**Comment by yanggq** [comment]
Workaroud found of this issue: backup the Album app(com.sonyericsson.album) to a apk file, and install it normally. for the existing System app of album, installation will fail. Then, it works!

**Comment by mother32** [comment]
[col2notifyFileAllEn.txt](https://github.com/rovo89/Xposed/files/83693/col2notifyFileAllEn.txt)

**Comment by rovo89** [comment]
The ClassNotFoundException is probably the reason for the crash. For some reason, I can't find it in the logcat though. Do you know if this also happened with v78 or is v79 the first one that you've tried?

**Comment by yanggq** [comment]
Yes，this also happed with the romracer version which is based on v78(right ?). 
This can be reproduced: after installing Xposed or  wiping cache, Album app fails; removing Xposed or just reinstall album app  makes it work again.

**Comment by xXCooL69GuYXx** [comment]
Still fails

**Comment by mbc07** [comment]
Not sure if it helps but CameraCommon.apk and SemcAlbum-albumLive-release.apk needs to be deodexed manually, otherwise those apps won't start anymore after installing Xposed. I can confirm this behavior on Xperia M5 running stock Android 5.1 ROM. If that helps, I can provide the mentioned APKs with their respective odex files for investigation if needed...

**Comment by rovo89** [comment]
Can you please check if v83 fixes this?

**Comment by yanggq** [comment]
I've just tried it out, v83 works perfectly on my Z5p now!  This version seems more steady and performance is better.

Thank you so much!
