### ISSUE TITLE
x86 emulator support

### ISSUE THREAD

**Issue by Efreak** [rovo89/Xposed#110]
The x86 "emulator" uses hyper-v, and isn't locked down. Is there any chance of getting support for a zip file that can be flashed with the install_zip.sh file as a root user or via adb? ADB runs as root by default.

**Comment by rovo89** [comment]
Are you talking about the normal Android emulator? When I searched for `install_zip.sh`, I mainly found references to Microsoft's emulator.

**Comment by Efreak** [comment]
The Microsoft emulator is what I'm talking about (it's not really an emulator, it's just virtualized).

**Comment by Efreak** [comment]
The Microsoft emulator is what I'm talking about (it's not really an emulator, it's just virtualized). I've ][written up](http://forum.xda-developers.com/android/development/microsoft-android-emulator-t3283966) what I found about it over on XDA in the hopes that it'll help someone make it more useful for doing things with android on the computer while under windows, but nobody else seems terribly interested. Androidx86 under virtualbox is all very nice, but it has limitations. I have done very little since then--the Microsoft emulator requires a network bridge, which interferes with the built-in hostednetwork for providing an access point from your computer--but I'm hoping to figure out how to get my own kernel and kernel parameters in it without it breaking down.

In any case, it seems that installing the zip won't actually have any effect anyways, as while the system partition is flashable, some parts of it are contained in the ramdisk and I haven't figured out how to modify that without breaking the emulator.
