### ISSUE TITLE
Android 6.0 issue..

### ISSUE THREAD

**Issue by humza10** [rovo89/Xposed#112]
Hi guys, I am having bootloop when rebooting after installing the zip file I restart and phone works fine but when I go to the app and tick the modules I want which requires reboot and when I do the reboot phone doesn't turn on.. 

01-07 15:55:26.505 I/Xposed (11265): -----------------
01-07 15:55:26.505 I/Xposed (11265): Starting Xposed version 79, compiled for SDK 23
01-07 15:55:26.505 I/Xposed (11265): Device: SM-G901F (samsung), Android version 6.0.1 (SDK 23)
01-07 15:55:26.505 I/Xposed (11265): ROM: cm_kccat6xx-userdebug 6.0.1 MMB29M 6fed9b1fd5 test-keys
01-07 15:55:26.505 I/Xposed (11265): Build fingerprint: samsung/kccat6xx/kccat6:5.0.2/LRX22G/G901FXXU1BOD1:user/release-keys
01-07 15:55:26.505 I/Xposed (11265): Platform: armeabi-v7a, 32-bit binary, system server: yes
01-07 15:55:26.505 I/Xposed (11265): SELinux enabled: yes, enforcing: no
01-07 15:55:35.499 E/Xposed (11265): Found /data/data/de.robv.android.xposed.installer/conf/disabled, not loading Xposed

i have tried deleting the file in dada/data but after that phone was stuck at cm boot logo, very strange to why this is happening.

I am on Cm 13 android 6.0  for galaxy s5 g901f

**Comment by rovo89** [comment]
Please disable all modules and try again. If it still doesn't start, please provide a logcat of the bootloop.

**Comment by humza10** [comment]
phone works fine when no modules are enabled but when i enable them and reboot phone gets stuck on cm logo. How can i get the log when the phone is not turning on?

Thank you

**Comment by rovo89** [comment]
Ok, then it's most likely not an issue with the Xposed framework itself and therefore I can't help you.
I suggest you enable your modules one by one. By this, you should be able to find out which module is causing the issue and therefore whom to contact. Obviously, you should make sure that they're all updated before. In order to get a log, I always suggest `adb logcat -v time > logcat.txt"`
