### ISSUE TITLE
"unfortunately, nfc service has stopped" error message keeps pooping up after installing xposed framework

### ISSUE THREAD

**Issue by hao19** [rovo89/Xposed#113]
When installing xposed framework on a nexus 6 with android 6.0.1, build mmb29s, there is a constant error message saying the nfc service has stopped and the message keeps on popping up repeatedly.

**Comment by rovo89** [comment]
This is most likely a duplicate of https://github.com/rovo89/android_art/issues/28, which is also about failing compilation of the NfcService.

**Comment by JayVx** [comment]
same error on nexus 5x on latest marshmallow build
flashed twrp
rooted
install zip "xposed v80 arm64..."
loop on nfc error
