### ISSUE TITLE
Reboot on Bluboo Xtouch after installing xposed-v79-sdk22-arm64.zip

### ISSUE THREAD

**Issue by nJoy-Android** [rovo89/Xposed#115]
I have rooted the Bluboo Xtouch with SuperSU with TWRP-2.8.7.1 collected from needrom.
After flashing xposed-v79-sdk22-arm64.zip and wipe dalvik/cache > normal boot > after 1 minute freezing - no input possible > restart.
I've made a log with adb logcat -v long > xposed-log.txt
Started logging until reboot after flashing  xposed-v79-sdk22-arm64.zip.
Logged about 12 minutes, about 22MB. What i have to looking for?
I still know the basics:
V — Verbose (lowest priority)
D — Debug
I — Info (default priority)
W — Warning
E — Error
F — Fatal
S — Silent (highest priority, on which nothing is ever printed)

https://www.dropbox.com/s/5utfvrpq5kzf6ol/xposed-log.txt?dl=0

**Comment by rovo89** [comment]
Your ROM seems to include stuff from MTK. Could you please try this? https://github.com/rovo89/Xposed/issues/81#issuecomment-171011266

**Comment by nJoy-Android** [comment]
Stilll testing. But looks gold. N reboot until yet ;-)
Thx a lot!
