### ISSUE TITLE
Bootloop on Samsung S4 i9515

### ISSUE THREAD

**Issue by shakee93** [rovo89/Xposed#118]
I am Having Bootloop on i9515. is there a way to roll back ? i tried the uninstaller on twrp it says Failed to sysmap file

Any Suggestion ?

**Comment by rovo89** [comment]
I haven't seen this message before, it's definitely not an output of the uninstaller zip itself. Anyway, I can't really help you with this. My builds are clearly marked as incompatible with Samsung, make sure that you use @wanam's builds and also his uninstaller: http://forum.xda-developers.com/xposed/unofficial-xposed-samsung-lollipop-t3180960
If everything else fails, restore your backup, or as a last resort flash the system image again.

**Comment by wanam** [comment]
I guess he is running a TW 5.0 Rom, which is supported by @arter97_dev for deodexed Roms only.
http://forum.xda-developers.com/showthread.php?t=3113463

**Comment by shakee93** [comment]
Thanks for your response ill take a look at it

[image: Freshpixl Creative Agency] <http://www.freshpixl.com/>

Shakeeb Sadikeen / Web Developer
service@freshpixl.com / +94 77 333 45 45

Freshpixl Creative Agency
+94 777 112 772
211/52, 2/3, Jummah Masjid Road, Maligawatte, Colombo-10.
http://www.freshpixl.com

[image: Facebook]  <https://www.facebook.com/freshpixl>[image: Twitter]
<https://twitter.com/freshpixl>[image: Google Plus]
<https://plus.google.com/+Freshpixlca/>[image: Linkedin]
<https://lk.linkedin.com/in/freshpixl>
