### ISSUE TITLE
System Crash

### ISSUE THREAD

**Issue by malitech** [rovo89/Xposed#119]
Hello, I freshly installed xposed on a stock rooted marshmallow without any modifications. I always see these same files in my system > dropbox folder. I don't know what this means. They appear always. Something is crashing internally. Can you please fix this? I have tested with many fresh installs.

[system_server_wtf@1452161453078.txt](https://github.com/rovo89/Xposed/files/104268/system_server_wtf.1452161453078.txt)
[system_server_wtf@1452161659034.txt](https://github.com/rovo89/Xposed/files/104269/system_server_wtf.1452161659034.txt)

Also, after installing xposed for the first time, some system apps like captiveportallogin, calculator, dialer....etc. gives a message "calculator stopped working". This happens because the dalvik cache is not created for these items. When I restart, android optimises the apps that gave an error, just 2 to 3 apps. Please fix this too.

Thanks a lot.

**Comment by rovo89** [comment]
Sorry, but the logs you provided are very short and don't seem to be related to Xposed at all.
What do you mean with the other error - these 2-3 apps weren't optimized on the first boot and therefore crashed, but a reboot fixed it?

**Comment by malitech** [comment]
But those same logs keep appearing in the dropbox folder. I haven't installed any apps. Just the normal ones like whatsapp to test what's causing it. It doesn't happen without xposed.

When I first flash xposed, and the phone starts, it optimises apps right? "Optimising 53 of 53 apps..." So, when the phone is booted, some system apps like calculator, captiveportallogin, google feedback...etc. crash when they're run with ".....stopped working". To fix this, I have to restart my phone and it says, "Optimising 2 of 2 apps..." (The 2 apps are those that crashed before) and now the crash is gone. I have tested this with different phones. But the crashed apps automatically optimise themselves after a restart.

**Comment by malitech** [comment]
Please tell me how to gather info, I'll do whatever you need. :)

**Comment by CzBiX** [comment]
Looks like It's just time issue caused system_server crash in your logs.
I don't think it's related to Xposed.

**Comment by malitech** [comment]
Time? My time shows right. I just had saved the logs to report it. I did it later.

**Comment by malitech** [comment]
[system_app_crash@1454783073344.txt](https://github.com/rovo89/Xposed/files/120520/system_app_crash.1454783073344.txt)

This happens after the first boot for some apps like downloads UI, calculator, dialer...etc. like I mentioned before. I hope this log helps you find the issue.

**Comment by malitech** [comment]
[system_app_crash@1455047843706.txt](https://github.com/rovo89/Xposed/files/123730/system_app_crash.1455047843706.txt)


[system_server_crash@1455047874668.txt](https://github.com/rovo89/Xposed/files/123731/system_server_crash.1455047874668.txt)
[system_app_crash@1455047840298.txt](https://github.com/rovo89/Xposed/files/123733/system_app_crash.1455047840298.txt)

More logs. I flashed system image of February on my nexus 5. I got these errors. "...stopped working" Fixes itself on second restart.

**Comment by rovo89** [comment]
Could you please post full logs taken using `adb logcat -v time > logcat.txt`? The files you keep posting here aren't very useful as they only show the crash itself, not the events before it. Please execute the command as early as possible during the initial boot. Then execute one of the apps to let it crash and press Ctrl+C. Btw, does this also happen during the first boot after clearing the Dalvik cache?

**Comment by malitech** [comment]
I didn't know how to take them. Thanks for letting me know. When the march security updates are released, I will flash the new system image and take this log.

I didn't know that. Is it ok if I save a log from liveboot app?

This happens only after the first boot and sometimes after second boot if xposed missed creating dex for any system app. So, usually I have to restart two to three times until everything is alright.

**Comment by rovo89** [comment]
> Is it ok if I save a log from liveboot app?

I haven't used it myself, but from what I've heard, it's a good way to save logs during early boot, yes.

> This happens only after the first boot

And if you clear the Dalvik cache now, does the issue reappear? Or did you already try this?

**Comment by malitech** [comment]
Very well. :) I will take both the logs then. 

If I clear the dalvik cache it optimises apps again and one or two apps crash again and I have to restart again so that it optimises those crashed apps again.

**Comment by malitech** [comment]
[logcat.txt](https://github.com/rovo89/Xposed/files/221834/logcat.txt)

Hello, hope this has something useful.

**Comment by rovo89** [comment]
Could you please check if v83 fixes this issue?

**Comment by rovo89** [comment]
Closed due to the lack of feedback.
