### ISSUE TITLE
Not working on Sony Xperia C4 5.1 

### ISSUE THREAD

**Issue by eoinkennedy** [rovo89/Xposed#120]
Not working on new Stock 5.1 firmware from Sony on the C4.

Flashed v79 sdk 22 arm64 through TWRP recovery.

Get an "optimising application" loop.
this runs through each app on the phone and then restarts.

If I run the uninstaller script in Recovery, bootloop disappears.

Works just fine on Sony Stock 5.0 FW, using v79 SDK 21.

**Comment by eoinkennedy** [comment]
https://drive.google.com/file/d/0B7ZLjfig4jTHRmxmeXd6RHJ0V2s/view?usp=sharing

Logcat here

**Comment by rovo89** [comment]
Probably a duplicate of #81, please try this: https://www.dropbox.com/s/8lddtv03riu8a1r/xposed-v80-sdk23-arm64-test2.zip?dl=0,

**Comment by eoinkennedy** [comment]
Not flashable, need an SDK v22 version for the 5.1 ROM.

**Comment by eoinkennedy** [comment]
Installed v80 SDK22 Test 1 and all is well. Thanks.

**Comment by xXCooL69GuYXx** [comment]
Just downloaded the xposed installer app and it'd tell you if it work on
your phone or not .
