### ISSUE TITLE
Stuck on boot-Huawei P8 lite (ALE-L21)

### ISSUE THREAD

**Issue by surfercoats** [rovo89/Xposed#121]
It seems not easy to make work Xposed on huawei devices. I tried on the P8 lite (Ale-L21). I install the installer (3.0 alpha4 and also tried the versions from v28 to v32) then flash with Twrp the framework (v79-sdk21-arm64 and tried also the v78) wipe cache and dalvik,restart.The result is always a boot,then stuck for a while, 3-5 minutes about then reboot itself and stuck again but indefinitely. I wait also over 40 minuts because I read that on some device needs also 20 minutes to optimize the dalvik. I also tried to edit the build.prop changing the rows  ro.config.hwtheme=0 or to disable the hook resources, but doesn't work.I tried also after a factory reset, to be sure that there wasn't some conflict with some linking 2 sd app. Any advice is welcome. I'm available for any further information. Thanks

**Comment by RenjarP7** [comment]
Without log? 
But it seems like the same issue like #72

**Comment by surfercoats** [comment]
[logcat.txt](https://github.com/rovo89/Xposed/files/110759/logcat.txt)

**Comment by surfercoats** [comment]
it seems to be ForcenotDex condition problem, right?

**Comment by surfercoats** [comment]
[logcat-2.txt](https://github.com/rovo89/Xposed/files/110763/logcat-2.txt)

**Comment by surfercoats** [comment]
framework folder   https://mega.nz/#!oopEULZS
