### ISSUE TITLE
Xperia Z3 stock 5.1,  xposed working fine, but system lags

### ISSUE THREAD

**Issue by MohamedHashem** [rovo89/Xposed#123]
HI sir, I got to flash Xposed properly and it's working,  and modules are working fine, but I noticed  a lag in the whole system, but actually it's the worst lag when it comes to settings-->apps, 
I tested my theory multiple times, and  I'm certain it's related to the system/xposed relationship,
As you see, no bootloops at all. Just lags
Thanks.

**Comment by MohamedHashem** [comment]
this issue happens not from just installing the framework or the apk, it only happens when I check at least one module whatever it is, the problem disappeard just after I checked both modules I had, and there was no need to uninstall the apk or the framework itself.

**Comment by wanam** [comment]
This should not be reported here, report this to the module author and provide your xposed logs.

**Comment by MohamedHashem** [comment]
It's not a problem with a particular module sir, please read my issue carefully

**Comment by rovo89** [comment]
There's not really much logic that is only executed if there's at least one module. So there's only a small chance that it's actually an issue with the framework itself. Which modules do you have issues with? If they're big all-in-one modules, I suggest you try it with a very small module that just provides one little tweak.

**Comment by MohamedHashem** [comment]
Well, I tried it once with only one module that only hides my dual sim icon,
And after a full wipe and reinstall I tried with the same module again, and the problem seemed solved, then I checked XStana + soft reboot and the problem happened again and here is my log:

02-07 21:26:20.983 I/Xposed  (  618): -----------------
02-07 21:26:20.983 I/Xposed  (  618): Starting Xposed version 80, compiled for SDK 22
02-07 21:26:20.983 I/Xposed  (  618): Device: D6633 (Sony), Android version 5.1.1 (SDK 22)
02-07 21:26:20.983 I/Xposed  (  618): ROM: 23.4.A.1.232
02-07 21:26:20.983 I/Xposed  (  618): Build fingerprint: Sony/D6633/D6633:5.1.1/23.4.A.1.232/2925005669:user/release-keys
02-07 21:26:20.983 I/Xposed  (  618): Platform: armeabi-v7a, 32-bit binary, system server: yes
02-07 21:26:20.983 I/Xposed  (  618): SELinux enabled: yes, enforcing: yes
02-07 21:26:20.989 I/Xposed  (  618): -----------------
02-07 21:26:20.989 I/Xposed  (  618): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
02-07 21:26:21.328 I/Xposed  (  618): Detected ART runtime
02-07 21:26:21.351 I/Xposed  (  618): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
02-07 21:26:21.634 I/Xposed  (  618): Loading modules from /data/app/org.ast11.hidesimicons-1/base.apk
02-07 21:26:21.832 I/Xposed  (  618):   Loading class org.ast11.hidesimicons.HideSimIcons
02-07 21:26:21.844 I/Xposed  (  618): Loading modules from /data/app/lfprodev.xposed.xstana-1/base.apk
02-07 21:26:23.701 I/Xposed  (  618):   Loading class lfprodev.xposed.xstana.EngineXstana
02-07 21:26:45.838 I/Xposed  ( 1637): HideSimIcon: Detected LP 5.0/5.1, changing margin
02-07 21:26:53.039 I/Xposed  ( 2065): HideSimIcon: Detected LP 5.0/5.1, changing margin
02-07 21:27:46.933 I/Xposed  ( 4388): HideSimIcon: Detected LP 5.0/5.1, changing margin
02-07 21:27:55.716 I/Xposed  ( 1259): HideSimIcon: Detected LP 5.0/5.1, changing margin
02-07 21:34:24.727 I/Xposed  ( 8836): HideSimIcon: Detected LP 5.0/5.1, changing margin

**Comment by MohamedHashem** [comment]
OK now I tried exactly the opposite,  and I unchecked XStana then installed 2 really big all-in-one module + the hide sim of course, and the issue didn't exist anymore!, so now the problem is with XStana I suppose, sorry for taking your time, but I really tried alot not to make a trouble, but is there any ideas why XStana causes this issue ? Sorry again for your time.

**Comment by MohamedHashem** [comment]
Update: the developer of XStana recognised the problem, thanks.
