### ISSUE TITLE
Xiaomi Redmi Note 2 miui 7.1.x.0 bootloop

### ISSUE THREAD

**Issue by dissidius** [rovo89/Xposed#124]
please any news for xiaomi redmi note 2 helio mtk 6795 i tried on latest miui 7.1.x.0 but still bootloop even with v80

**Comment by rovo89** [comment]
Logcat?

**Comment by dissidius** [comment]
thanks for replying I've made logcat but it's unfiltered sorry it was very tricky to get logcat durin bootloop here it is I've made two 
1 for the 7.1.3.0 multilanguage xiaomi.eu
2 for the multirom.me miui 7.1.4.0 China
thank you 
https://mega.nz/#!1E1CzRZJ!dkwwmXLWiB5t3uKe2P-N1Qk6VxJK3ODn9Ygng-uuG2M

**Comment by andusatria** [comment]
thanks for opening this issue as i want to open this too..
please fix error Fatal signal 11 (SIGSEGV) 
and make it more adaptable for MIUI rom Sir.. 

here is my log, but i assume this was the same as above.
[http://bit.ly/bootlog_xposedv80](url)

**Comment by rovo89** [comment]
I didn't check the link posted by @dissidius yet, but at least in the log by @andusatria, I found this crash:
```
02-06 02:07:11.921 I/DEBUG   (  909): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-06 02:07:11.921 I/DEBUG   (  909): Build fingerprint: 'Xiaomi/hermes/hermes:5.0.2/LRX22G/V7.1.4.0.LHMCNCK:user/release-keys'
02-06 02:07:11.921 I/DEBUG   (  909): Revision: '0'
02-06 02:07:11.921 I/DEBUG   (  909): ABI: 'arm64'
02-06 02:07:11.921 I/DEBUG   (  909): pid: 769, tid: 769, name: system_server  >>> system_server <<<
02-06 02:07:11.921 I/DEBUG   (  909): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1708d9857
02-06 02:07:11.934 I/DEBUG   (  909):     x0   0000007f94c074c8  x1   0000000070e95c38  x2   00000000708d9858  x3   00000000ffffffff
02-06 02:07:11.934 I/DEBUG   (  909):     x4   0000000000000004  x5   000000558c65ec70  x6   0000000000000004  x7   0000000000000004
02-06 02:07:11.934 I/DEBUG   (  909):     x8   0000000000000004  x9   000000558c3154ff  x10  000000000000003b  x11  0000000000000001
02-06 02:07:11.934 I/DEBUG   (  909):     x12  0000000000000001  x13  0000000000000029  x14  000000558c65ec64  x15  000000000000004c
02-06 02:07:11.934 I/DEBUG   (  909):     x16  0000007f94c06c28  x17  0000007f94bee4c4  x18  0000000000000000  x19  000000558c589d50
02-06 02:07:11.934 I/DEBUG   (  909):     x20  00000000708d9858  x21  0000007f94c06000  x22  0000000000000000  x23  0000000070e95c38
02-06 02:07:11.934 I/DEBUG   (  909):     x24  0000007fe332ca90  x25  0000007fe332cbc0  x26  0000007fe332cb90  x27  000000558c6ef960
02-06 02:07:11.934 I/DEBUG   (  909):     x28  000000558c6ef978  x29  0000007fe332c9a0  x30  0000007f94beccb8
02-06 02:07:11.934 I/DEBUG   (  909):     sp   0000007fe332c9a0  pc   0000007f94bee4f8  pstate 0000000060000000
02-06 02:07:11.934 I/DEBUG   (  909): 
02-06 02:07:11.934 I/DEBUG   (  909): backtrace:
02-06 02:07:11.934 I/DEBUG   (  909):     #00 pc 000000000000f4f8  /system/lib64/libmiuiclassproxy.so (miui::art::ArtProxy::OnProxyMethod(_JNIEnv*, miui::art::MethodItem*)+52)
02-06 02:07:11.934 I/DEBUG   (  909):     #01 pc 000000000000dcb4  /system/lib64/libmiuiclassproxy.so (miui::art::ArtProxy::AddMethod(_JNIEnv*, std::string const&, std::string const&)+632)
02-06 02:07:11.934 I/DEBUG   (  909):     #02 pc 000000000000cc5c  /system/lib64/libmiuiclassproxy.so (miui::InitMiuiSdkHookClasses(_JNIEnv*, int, _jstring*)+796)
02-06 02:07:11.934 I/DEBUG   (  909):     #03 pc 0000000002836e44  /data/dalvik-cache/arm64/system@framework@boot.oat
```

As you can see, it's crashing in libmiuiclassproxy.so, not in Xposed. It looks as if MIUI has once again done big modifications compared to AOSP and even added their own library to hack the ART runtime.

There's a saying "too many cooks spoil the broth" - when two parties (i.e. Xposed and MIUI) try to do such modifications, there's a high risk of conflicts. I'm tired of being the one who has to react on their (closed-source!) modifications. Sorry, but I will close this as "wontfix".

**Comment by dissidius** [comment]
great now we should  kill ourselves haha

thanks anyway

**Comment by devnoname120** [comment]
@rovo89 Yes, MIUI's team is unresponsive. From their perspective, it is a third-party issue, so they keep answering on the bug tracker that it is up to the author of the tool to fix it. Furthermore, they are evasive about the fact that they have the code, so seeing why it doesn't work is way easier for them. (Oh and they once ripped Xposed's code without giving credit, so they know what fixes to do in order to make it work.)
Meanwhile, people are actively distributing outdated and vulnerable Android libraries on their forums in order to make it work with an older port of Xposed...
Do you think that it would be possible for you to create a bug report on MIUI's bug tracker? By explicitly stating that you are the author of Xposed, and that you need their help for fixing the problem, they might eventually address the issue.
