### ISSUE TITLE
Force Close Weather app LG G4

### ISSUE THREAD

**Issue by Slim80** [rovo89/Xposed#125]
Hi. In my LG G4 odex fw with Android MM 6.0, everything works fine but the Weather app.
Here the Logcat:
https://www.dropbox.com/s/n1xy7m1sisenrmf/Log_2016-02-07_15-30-00.txt?dl=0

**Comment by rovo89** [comment]
@Slim80 @Lupus-Dei @ciro73
Could you please check if there's a "lgalmond.so" or similar file in /system/lib and/or /system/lib64 and upload these files if they exist? Thanks!

**Comment by Lupus-Dei** [comment]
Yes, there is in lib64. Please find it in the attachment.
[liblgalmond.zip](https://github.com/rovo89/Xposed/files/239156/liblgalmond.zip)

**Comment by rovo89** [comment]
I have ported https://github.com/rovo89/android_art/commit/b3675bf669f3a770cf48d12decffeef0420be26e to Marshmallow with a few modifications.

Could you please test this? I can use dex2oat and oatdump on an encrypted file.
https://www.dropbox.com/s/6i59kg2wplwi6rs/xposed-v84-sdk23-arm64-test1.zip?dl=0

**Comment by Slim80** [comment]
Hi. Unfortunately, with the v83 and v84 i have a persistent SystemUI Force Close. No problem with the v82. I can't make a logcat now. I need adb and now i don't have my pc. I will sent you the logcat in the next hours

**Comment by rovo89** [comment]
> Unfortunately, with the v83 and v84 i have a persistent SystemUI Force Close. No problem with the v82.

Oh OK... it would have been good if you had reported this on GitHub as soon as v83 was out. Bug reports on XDA drown in the massive amount of unrelated posts.

**Comment by Slim80** [comment]
I'm sorry. But i tried the v83 only now. I installed the v84 over the v82 (i wiped cache and dalvik-cache/art and flashed the uninstaller zip before to flash the new version).

**Comment by ciro73** [comment]
@rovo89 v84 installed over v83 without uninstaller. Weather app still crashing.
Everything else is like with v83. Not quite sure if I get it right.
Let me know if I can do something else to help

**Comment by kevintongg** [comment]
I don't have a G4, but I feel my issue is also related so I'm posting here for consolidation.

I just updated my stock rooted LG G3 to the Marshmallow update last night. 

It seems the update got rid of xposed which I reinstalled and then after that it started giving me: `Unfortunately, Weather Service has stopped` which seems to be the same as everybody else in here; their weather isn't working right.

**Comment by rovo89** [comment]
> I'm sorry. But i tried the v83 only now.

No worries, this was more a general statement. It's not really helpful for me if people just say "it's not working" or even tell others to stick to older versions. Issues don't magically get fixed, I need a good bug report.

> Let me know if I can do something else to help

Too bad that it doesn't work yet. Could you please post a log of the crash, ideally reaching back to the start of the device?

> I just updated my stock rooted LG G3 to the Marshmallow update last night.

Sounds like the same issue, yes. Would you need the arm version (instead of arm64) for testing?

**Comment by kevintongg** [comment]
@rovo89 Yeah, I believe so. I don't believe the G3 has 64bit support.

**Comment by ciro73** [comment]
@rovo89 here the logcat with v84 on a full reboot and crash of LGweather App [logcat.zip](https://github.com/rovo89/Xposed/files/243635/logcat.zip)

**Comment by rovo89** [comment]
Thanks, that helps. There are two rather similar ways how an odex file can be opened and one other, slightly different way. I knew that the latter one can't the decryption (yet), but I wasn't sure if it's used in these cases. The log shows that it is used, so I'll prepare a new patch.

**Comment by rovo89** [comment]
This should work better: https://www.dropbox.com/sh/8t4ij61k50lgdnq/AADiKvYlInYJ9VSPb8PiB6xOa?dl=0

**Comment by ciro73** [comment]
it worked better 😉
LG weather app is starting now without crashing.

**Comment by kevintongg** [comment]
I'll try it in a sec and report back.

**Comment by kevintongg** [comment]
@rovo89 Weather/Weather Service is now no longer force closing. Thanks!

**Comment by Slim80** [comment]
I solved the issue with my SystemUI. And i tried the v84 test3. Meteo app works fine now. 
Thank you very much!

**Comment by rovo89** [comment]
Great, thanks for testing! I need to verify a few other things, then I will release an official version with the fix.

@Slim80: How did you solve the SystemUI issue?

**Comment by Slim80** [comment]
I deodexed again the LGSystemUI with the updated "oat2dex.jar" tool and i applied again the 3Minit battery mod using the last apktool 2.1.1 snapshot compiled myself from the source. Now works.
But I do not know why it works the same in the V82. It's possible that i have made some mistake..
:)

**Comment by rovo89** [comment]
Fixed in v84.
