### ISSUE TITLE
ViaPlay app force closing when Xposed is installed

### ISSUE THREAD

**Issue by CrilleTheBoss** [rovo89/Xposed#130]
When Xposed Is installed the ViaPlay app force closes when trying to play a video.
When i uninstall Xposed framework ViaPlay works again. 

Here is the log:
http://pastebin.com/Us5qu39u

**Comment by rovo89** [comment]
It's a bug in the app. This might fix it: http://repo.xposed.info/module/de.robv.android.xposed.mods.irdetofix

**Comment by CrilleTheBoss** [comment]
The irdetofix didn't fix it sadly. Is there any way to use the app with xposed framework installed? I really don't want to remove Xposed from my phone. I tried hiding root and xposed with rootcloak but that didn't work either.

**Comment by rovo89** [comment]
> Is there any way to use the app with xposed framework installed?

I don't think so, expect maybe creating `/data/data/de.robv.android.xposed.installer/conf/disabled` and rebooting to use the app, then delete the file and reboot again...

Is it still the same error message? The problem here is that they (for some reason) look at all the classes in the current stack trace and load them by their name. But the `XposedBridge` class can't be retrieved like that because it's in a different classloader. They don't catch this case and therefore it crashes.

**Comment by wanam** [comment]
I think the irdetofix won't work on the latest updates, the added path (https://github.com/rovo89/IrdetoFix/blob/master/src/de/robv/android/xposed/mods/irdetofix/IrdetoFix.java#L24) is outdated since the bridge has been moved to "/system/framework".

**Comment by CrilleTheBoss** [comment]
> maybe creating /data/data/de.robv.android.xposed.installer/conf/disabled and rebooting to use the app

That won't work because im using (wanam's Xposed for samsung). Xposed safe mode is disabled there.

> the added path is outdated since the bridge has been moved to "/system/framework".

Is it possible to fix the path in the irdetofix to make it work again?

**Comment by wanam** [comment]
Try this: https://www.dropbox.com/s/r6rlyqu0cv29do6/IrdetoFix.1.1.test.apk?dl=0

**Comment by CrilleTheBoss** [comment]
It's not installing. (there was a problem while parsing the package)

**Comment by wanam** [comment]
Uninstall the old one, my test version is not signed.

**Comment by CrilleTheBoss** [comment]
I tried the irdetofix 1.1 and it's working now, the app is not crashing anymore. But Videos are not playing at all. The videos are just loading and nothing is happening.
Here is the new log if you can take a look at it: http://pastebin.com/cNj7aw7q
Thanks mate :+1:

**Comment by wanam** [comment]
The dexpath is set according to the logs:
> 02-24 21:23:46.457 I/IrdetoFix(26240): Set dexPath to /system/framework/XposedBridge.jar:/data/app/com.viaplay.android-2/base.apk

But there is a silent crash while trying to find the class "VPProductParcelData":
> 02-24 21:23:58.817 E/Parcel  (15590): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.viaplay.android.vc2.model.VPProductParcelData" on path: DexPathList[[zip file "/system/framework/XposedBridge.jar"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]

The app dex got removed from the DexPathList somewhere later, the app sources are mostly proguarded so i don't think i can go deeper on this issue.

**Comment by CrilleTheBoss** [comment]
Okey wanam, thank you for your help I really appreciate it

**Comment by rovo89** [comment]
> The app dex got removed from the DexPathList somewhere later

That seems to be in the system_server process though when it tries to read an object from a Parcel which it received from the app. I'm not sure how that *should* work, it would at least need to have the app's classloader, I just noticed it.

**Comment by CrilleTheBoss** [comment]
I contacted ViaPlay about this issue with Xposed, and they fixed the problem in V. 4.7. Viaplay is now working with Xposed Framework installed
