### ISSUE TITLE
Nexus 4 5.1.1 Ocassional Bootloop

### ISSUE THREAD

**Issue by CalculatedRisk23** [rovo89/Xposed#135]
Hello,

I recently clean flashed stock 5.1.1 lollipop on my nexus 4, installed xposed and re-installed all my modules, set them all up, etc. And noticed that at the end of it all I experience boot loops on approximately every other boot.

I uninstalled and re-installed xposed, wiped dalvik and cache, and disabled all my modules and enabled them one by one to see if I could catch the culprit, but it seems to happen completely random.. I can't find anything online about it, so I'm not sure if anyone knows the cause for this or how to fix it.

I managed to pull the logs. A bunch of errors pop up near the end, unfortunately I don't know what they mean. Any help would be appreciated, thanks.

Log: http://pastebin.com/kdLFw9uf

**Comment by rovo89** [comment]
The log you posted is very short and doesn't show a bootloop, just the beginning of the boot sequence. I see that com.n0n3m4.gltools runs into issues and that you have many modules enabled. 

Sorry, but with so many possible reasons and without a log that clearly shows that the Xposed framework is the culprit, I can't help. Feel free to reopen with a better log, ideally without any modules enabled and without apps like GLTools that might also interfere.
