### ISSUE TITLE
Xposed hooking with parameter as a custom user defined class

### ISSUE THREAD

**Issue by anantshri** [rovo89/Xposed#138]
User might have created there own class structure and that object might be passed as an argument in the function. As for generic classes we can use something like String.class or int.class. Any suggestions how i can handle custom classes.

**Comment by rovo89** [comment]
I'm not sure if I understood you correctly, an example would have been helpful. With "user", do you mean the developer of the app that you're trying to hook?

If you have a method in the app like this:
```java
public void doSomething(String abc, SomeClass xyz) {
}
```

Then you can hook it this way:
```java
findAndHookMethod("com.example.TheClass", lpparam.classLoader, String.class, "com.example.SomeClass", new XC_MethodHook() {
...
});
```

I.e. just mention the full-qualified class name as a string.

Does it answer your question?

**Comment by samitanwer** [comment]
"com.example.SomeClass" would not resolve unless we add it in the build path right? How do you suggest to resolve the custom class?

**Comment by rovo89** [comment]
What do you mean with "resolve"? In the example I gave, the class only needs to be resolved at runtime, and that will be done with `lpparam.classLoader` (assuming you put this into `handleLoadPackage()`. This has nothing to do with your build path.

If you mean something else, please provide more details about what you're trying to do and what you (unsuccessfully) tried.

**Comment by samitanwer** [comment]
Thanks. This was helpful. :)
