### ISSUE TITLE
Mediatek Plugin System (FWKPlugin.apk) failure on MIUI Global Stable 7.1.3 (Android 5.0.2).

### ISSUE THREAD

**Issue by SergPhantom** [rovo89/Xposed#140]
After installing xposed v.80 (works fine in a whole, btw) on MIUI Global Stable 7.1.3 (Android 5.0.2) on Xiaomi Redmi Note 2 phone I found that embedded video in KinoPoisk application stoped working. Some other users found this problem with Facebook application with the same sympthoms on other firmwares, all are **Android Lollipop made by Mediatek**.
How to reproduce: install Facebook or KinoPoisk application and try to view any video embedded into application (e.g., see any trailer in KinoPoisk).
Error that happened:
**E/MPlugin ( 5564): 	Caused by: java.io.IOException: Failed to open file '/data/dalvik-cache/arm/system@plugin@FwkPlugin@FwkPlugin.apk@classes.dex': Permission denied**
In some cause the system try to use a non-existent file from arm32 dalvik cache, though this application is _odexed_.
Logcat output is attached.
[out.txt](https://github.com/rovo89/Xposed/files/171252/out.txt)
What information more needed to investigate the problem?

**Comment by SergPhantom** [comment]
Btw, the application itself installed to /system/plugin firectory.
That is the directory structure:
/system/plugin/FwkPlugin
  arm/FwkPlugin.odex
  arm64/FwkPlugin.odex
  FwkPlugin.apk
  FwkPlugin.mpinfo

**Comment by SergPhantom** [comment]
I won this fight. The cause of problem is that **xposed** considers that odexed applications may be located in /system/app, /system/framework, /system/prov-app and, may be, somewhere else, but **not** in /system/plugin directory. So it tries to load classes for /system/plugin/FwkPlugin/FwkPlugin.apk from dalvik cache, **not** from FwkPlugin.odex, which is located near the apk file in the arm64 directory.
That's why the error message, shown in my first post, appeared in system log.
What had I done? I've just deodexed and sign FwkPlugin.apk, replaced old apk file with it, removed its odex files and reboot phone. The system had generated appropriate dex file at boot time, and it appears at the location expected by xposed. And now it's working!
I think, xposed core library is needed just to add one more place where it supposed to meet odexed apk's: /system/plugin. It seems that this will resolve the reported problem.

**Comment by rovo89** [comment]
Actually Xposed (or better: ART) doesn't contain a list of odex directories. ART (even on AOSP) constructs the path relative to the APK file.

Usually, apps are already compiled before they're used. But that's not always the case, like here. The app tries to trigger its compilation, but that can't succeed due to missing permissions. In v83, I think I have fixed this case by allowing the app to run directly from the .odex file in interpretation mode.
