### ISSUE TITLE
Stuck on boot screem after flashing xposed

### ISSUE THREAD

**Issue by nelson0521** [rovo89/Xposed#141]
Hi rovo89,

My device is rooted nextbit robin (Android 6.0, official software version 00WW_1_19E)
I tried to flash xposed (xposed-v80-sdk23-arm64.zip) on my device.

At first, there was something wrong shown on the screen :

```
Updating partition details...
...done
Full SElinux support is present
MTP Enableed
Installing zip file '/sdcard/APK/xposed-v80-sdk23-arm64.zip'
Checking for MD5 file...
Skipping MD5 check: no MD5 file found
******************************
Xposed framework installer zip
******************************
- Mounting /system and /vendor read-write
- Checking environment
Xposed version: 80
- Placing files
gzip: short write
Updater process ended with ERROR: 1
Error installing zip file '/sdcard/APK/xposed-v80-sdk23-arm64.zip'
Updating partition details...
...done 
```

And it was success after several trying but now stuck on the boot screen.
Could you please help me ?   Thanks a lot !!!
Following link is log file.
https://www.dropbox.com/s/xza1siwtzlz8pa5/logcat.txt?dl=0

**Comment by rovo89** [comment]
"Short write" might mean that there wasn't enough space on /system. Can you verify that please? l

**Comment by nelson0521** [comment]
There is 1.42 GB available on /system.

**Comment by rovo89** [comment]
It's the only explanation I have for the `gzip: short write` though. Maybe check again after the failed installation (in case you already restored your backup). If you have the chance to "adb shell" into the device, please check if you can create a file somewhere in /system.

**Comment by nelson0521** [comment]
I was success after several trying but now stuck on the boot screen and system crash after few minute.
Could you please help me ? Thanks a lot !!!
Following link is log file.
https://www.dropbox.com/s/xza1siwtzlz8pa5/logcat.txt?dl=0

**Comment by nelson0521** [comment]
Hi rovo89,
I restore the "boot" with TWRP and now it is working, thank you so much.

**Comment by DanielHeretic** [comment]
solved : Manager files /system/app delete some app you don't use (that work for my)

**Comment by cc1072027237** [comment]
step1：
adb root
adb disable-verity
adb reboot

step2：install xposed

it's works for me...
