### ISSUE TITLE
编译不了

### ISSUE THREAD

**Issue by liumengdeqq** [rovo89/Xposed#143]
[armeabi] Compile++ thumb: xposed <= app_main.cpp
./app_main.cpp:17:26: error: operator '>=' has no left operand
 #if PLATFORM_SDK_VERSION >= 16
                          ^
In file included from ./app_main.cpp:24:0:
./xposed.h:47:26: error: operator '>=' has no left operand
 #if PLATFORM_SDK_VERSION >= 21
                          ^
./app_main.cpp:171:26: error: operator '>=' has no left operand
 #if PLATFORM_SDK_VERSION >= 16
                          ^
In file included from ./app_main.cpp:16:0:
D:/android-ndk-r10d/platforms/android-3/arch-arm/usr/include/android_runtime/AndroidRuntime.h:101:18: error: unused parameter 'code' [-Werror=unused-parameter]
     virtual void onExit(int code) { }
                  ^
cc1plus.exe: all warnings being treated as errors
/cygdrive/d/android-ndk-r10d/build/core/build-binary.mk:457: recipe for target 'obj/local/armeabi/objs/xposed/app_main.o' failed
make: *** [obj/local/armeabi/objs/xposed/app_main.o] Error 1

**Comment by rovo89** [comment]
Du kannst Xposed nicht mit dem NDK kompilieren, siehe hier: https://github.com/rovo89/XposedTools
