### ISSUE TITLE
Screen flicker and can't run any app

### ISSUE THREAD

**Issue by NicholasKK** [rovo89/Xposed#144]
Hi,

I tried everything I could. however adb does not work when this problem happens. So I don't really know how else I can get hang of logcat.
I have a tv box, Tronsmart/beelink R68G with android 5.1.1 and need to flash xposed on it. It is a arm64 chip but android 32bit on it. I tried to flash the arm64 version but I got an error that I should use the correct version.

Ok, so I use sdk v80 arm and everything goes as expected. I get "done" and then "android is optimizing...". So far so good, however after loging in to android, I get a black background (not the typical launcher background) with icons of the launcher on it. No matter what I click on, screen flickers once and nothing more. I am unable to run any app. I noticed that I could run two apps, netflix and youtube, may be because they are full screen apps (which do not show nav bar). However, running these two apps show that the wifi is disconnected, because nothing happens other than "the refreshing circle" at the center of the apps.
I tried to open settings, or swipe the nav bar down, but again nothing. Adb which was activated before flashing won't connect too.
Can you help me or even guess what is the cause of this issue?

Android 5.1.1, Kernel 3.10.0_204

**Comment by rovo89** [comment]
Regarding 32/64bit: It depends on the ROM. As an indicator, does /system/lib64 exist? If not, then your CPU might be able to handle 64bit, but the ROM is not.

Apart from that, I don't thing I can't do anything without a logcat. I can just assume that it's missing to compile some important apps: https://github.com/rovo89/android_art/issues/28

Maybe this will help to get a log, but I have no idea whether it's compatible with your TV box: http://forum.xda-developers.com/android/apps-games/liveboot-t2976189

**Comment by NicholasKK** [comment]
Thank you very much for your reply. 
No, I don't have lib64 and flashing arm64 version confirms that when I get a message to flash the correct version. 
I will try the live boot during weekend and post the news here, however I would also ask if it will help if I upload the system.img dump of the firmware somewhere? This TV box is one of the popular Chinese TV boxes with many users on freaktab. So it will also help the community to solve this issue.

**Comment by rovo89** [comment]
I don't think the system dump would help at this time, as we don't even have a hint where the issue might be.

**Comment by NicholasKK** [comment]
Ok, It worked, however choosing the option to save the logcat in cache partition didn't work (0 kb file). So there is no way to copy the log. However there are other logs inside the cache partition inside the recovery folder and I don't really know if they are of any use, specially the one named last_kmsg.
Here are the logs:
https://drive.google.com/folderview?id=0B-Q29md8NWCZOENQSks0N3FXMWM&usp=sharing

by the way, thank you :)

**Comment by rovo89** [comment]
Unfortunately, the recovery logs aren't helpful as this seems to be an issue with the running system, not with the installation in recovery mode.

Could you try v83 though, maybe one of the fixes helps you as well...

Otherwise, I don't know how you could get a logcat if neither adb nor Liveboot are working, but I really need the log to investigate. Maybe, but only maybe, the Xposed log also contains some information, you should find it at `/data/data/de.robv.android.xposed.installer/log/error.log`.

**Comment by rovo89** [comment]
Closed due to the lack of feedback. If you still have the issue, please post a proper log: https://github.com/rovo89/XposedBridge/wiki/Bugs#how-can-i-get-logs
