### ISSUE TITLE
Nexus 7 Error: 1

### ISSUE THREAD

**Issue by labskaus** [rovo89/Xposed#146]
Nexus 7 (2013) LTE
install orderlist
1) razorg-mmb29o-factory-8b9c0c1c
2) TWRP 3.0.2
3) UPDATE-SuperSU-v2.65-20151226141550
4) xposed-v81-sdk23-arm

Prozess Updater ended with Error: 1

**Comment by rovo89** [comment]
Please post the exact message that you see when installing the zip, or even better the recovery log.

**Comment by labskaus** [comment]
`******************************
Xposed framework installer zip
******************************
- Mounting /system and /vendor read-write
- Checking environment
  Xposed version: 81
- Placing files
cp: write error: No space left on device
Prozess Updater endete mit FEHLER: 1
I:Legacy property environment disabled.
Fehler beim Installieren von ZIP '/sdcard/Download/xposed-v81-sdk23-arm.zip'
Partitions-Informationen werden aktualisiert...
I:Data backup size is 1293MB, free: 25636MB.
I:Unable to mount '/usb-otg'
I:Actual block device: '', current file system: 'vfat'
...Fertig
I:Set page: 'flash_done'
I:operation_end - status=1
I:Set page: 'confirm_action'
I:Set page: 'action_page'
I:operation_start: 'Format'
Formatiere Cache mit make_ext4fs...
Creating filesystem with parameters:
    Size: 587202560
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 7168
    Inode size: 256
    Journal blocks: 2240
    Label: 
    Blocks: 143360
    Block groups: 5
    Reserved block group size: 39
Created filesystem with 11/35840 inodes and 4616/143360 blocks
I:Recreating /cache/recovery folder.
I:Copying file /etc/recovery.fstab to /cache/recovery/recovery.fstab
I:Version number saved to '/cache/recovery/.version'
Partitions-Informationen werden aktualisiert...
I:Data backup size is 1293MB, free: 25636MB.
I:Unable to mount '/usb-otg'
I:Actual block device: '', current file system: 'vfat'
...Fertig
I:Set page: 'action_complete'
I:operation_end - status=0
I:operation_start: 'Format'
Dalvik Cache-Verzeichnisse bereinigen...
Bereinigt: /data/dalvik-cache...
-- Dalvik Cache-Verzeichnisse bereinigt!
Partitions-Informationen werden aktualisiert...
I:Data backup size is 1293MB, free: 25636MB.
I:Unable to mount '/usb-otg'
I:Actual block device: '', current file system: 'vfat'
...Fertig
I:operation_end - status=0
I:Set page: 'rebootcheck'
I:Copying file /cache/recovery/log to /cache/recovery/last_log
Neustart...
I:InfoManager saving '/data/media/0/TWRP/.twrps'
I:Saved settings file values`

1.1GB free of 1,8GB

**Comment by rovo89** [comment]
Xposed is installed on `/system`, and that partition is full:
`/system | /dev/block/mmcblk0p22 | Size: 827MB Used: 827MB Free: 0MB Backup Size: 827MB`

**Comment by krokofant** [comment]
For anyone getting here via Google I'll suggest trying to install Xposed systemlessly.
