### ISSUE TITLE
v80 and v81 in LG G4 lollipop can cause boot stuck problem

### ISSUE THREAD

**Issue by liyafe1997** [rovo89/Xposed#147]
After installed v80 or v81 xposed in LG G4 Android 5.1 lollipop, sometimes cant boot into system(with blue LED flashing and black screen or stuck in LOGO, And I must to remove the battery to restart). It's happen ramdomly.

**Comment by rovo89** [comment]
Please try to take a logcat the next time that this happens, without it I can't help you. Also, does a reboot fix it?

**Comment by liyafe1997** [comment]
xposed's log?
Yes, it stuck ramdomly. So if stucked I must reboot and it may can enter system, if no, reboot agagin until boot succeed.

**Comment by liyafe1997** [comment]
Seems cant take any log when stucked. I try to connect adb when stucked but failed.

**Comment by rovo89** [comment]
You could try LiveBoot to get logs: http://forum.xda-developers.com/android/apps-games/liveboot-t2976189
Enable the option to save the logs, then you can fetch it in recovery when the boot got stuck again.

**Comment by rovo89** [comment]
There's a good chance that this random boot stuck issue is fixed with v85. If not, you can try to get logs with one of the methods mentioned here: https://github.com/rovo89/XposedBridge/wiki/Bugs#how-can-i-get-logs
