### ISSUE TITLE
SystemUI crash on HTC M8 DS

### ISSUE THREAD

**Issue by Falseclock** [rovo89/Xposed#149]
Hi.

There is an issue with Xposed on HTC One M8 Dual Sim version.

SystemUI and some other apks crash after dex2oat

Full logcat after xposed installation is here
https://drive.google.com/file/d/0B2lAfZOYZcTxOVAxcEw2U2VUdnM/view?usp=sharing

ready to test anything and provide everything you want ))

**Comment by Falseclock** [comment]
there are four packages failed with dex2oat

de.robv.android.xposed.installer
SystemUI
Bluetooth
Exchange3Google

with error like:

`04-17 00:59:21.835  8448  8448 E dex2oat : Failed to create oat file: /data/dalvik-cache/arm/system@priv-app@SystemUI@SystemUI.apk@classes.dex: Permission denied

04-17 00:59:21.835  8448  8448 I dex2oat : dex2oat took 621.562us (threads: 4) 

04-17 00:59:21.837  8436  8436 W art     : Failed execv(/system/bin/dex2oat --runtime-arg -classpath --runtime-arg /system/framework/XposedBridge.jar --instruction-set=arm --instruction-set-features=smp,-div,-atomic_ldrd_strd --runtime-arg -Xnorelocate --boot-image=/system/framework/boot.art --runtime-arg -Xms64m --runtime-arg -Xmx512m -j4 --instruction-set-variant=krait --instruction-set-features=default --dex-file=/system/priv-app/SystemUI/oat/arm/SystemUI.odex --oat-file=/data/dalvik-cache/arm/system@priv-app@SystemUI@SystemUI.apk@classes.dex) because non-0 exit status

04-17 00:59:21.839  8436  8436 W art     : Entry not found

04-17 00:59:21.840  8436  8436 W System  : ClassLoader referenced unknown path: /system/priv-app/SystemUI/lib/arm`



Last three apks attached here 

https://drive.google.com/file/d/0B2lAfZOYZcTxUHdWMV9YWGFackE/view?usp=sharing

**Comment by Falseclock** [comment]
Here is logcat of original system rom without root or xposed

https://drive.google.com/file/d/0B2lAfZOYZcTxWTNlNUtKbHZXRUU/view?usp=sharing

**Comment by rovo89** [comment]
Could you try the test2 version for your platform from here please? https://www.dropbox.com/sh/gketc1pry8ovy33/AACEqJME6LijmlFzrRlkAnwja?dl=0

**Comment by Falseclock** [comment]
Hi.

it works now and xposed modules also work, but error like written above still in logcat.

here it is.
https://drive.google.com/file/d/0B2lAfZOYZcTxQUlvZTNYQmVLd0k/view?usp=sharing

and every restart system tries to optimize 7 applications.

https://drive.google.com/file/d/0B2lAfZOYZcTxZ2dhVHVWc092N0k/view?usp=sharing

**Comment by rovo89** [comment]
Could you please upload the /system/framework folder or at least the boot.oat file as well? Odex files are meaningless without them.

**Comment by Falseclock** [comment]
Here it is

https://drive.google.com/file/d/0B2lAfZOYZcTxLU5ZYi1jZnJBSE0/view?usp=sharing

**Comment by rovo89** [comment]
Could you try this one please? https://www.dropbox.com/s/lqxrwljoknalh12/xposed-v83-sdk23-arm-test3.zip?dl=0

**Comment by Falseclock** [comment]
It seems ok now.

this is log after install
https://drive.google.com/file/d/0B2lAfZOYZcTxTlFYOTByNXNHOTA/view?usp=sharing

this is log after reboot
https://drive.google.com/file/d/0B2lAfZOYZcTxODA2OWxQQkZmckE/view?usp=sharing

**Comment by rovo89** [comment]
Fixed in v83.
