### ISSUE TITLE
Xposed Framework crashing after App update

### ISSUE THREAD

**Issue by SecUpwN** [rovo89/Xposed#15]
Hi @rovo89, first things first: HATS OFF to the awesome work you've been doing to create the magic tool! Here's an Issue I've been monitoring for quite a while now: Upon updating Apps, Xposed tends to crash at times - especially when updating [Greenify](http://forum.xda-developers.com/showpost.php?p=38192418). Here is my [logcat](https://privatepaste.com/875be0d607). Let me know of you need anything.

**Comment by rovo89** [comment]
This bug report is quite old and the log is no longer available. If this still occurs, please reopen with a new log.
