### ISSUE TITLE
There is a problem to run xposed v82 on x86 emulator API level 23

### ISSUE THREAD

**Issue by shugaoye** [rovo89/Xposed#150]
I did a test using the xposed v82 for API level 23 using x86 emulator. I can run emulator without problem. However, when I check the xposed status. It shows that it is installed, but it cannot link to library "libdvm.so". Does this mean that xposed still use Dalvik in Lollipop and Marshmallow ?

http://s2.sinaimg.cn/mw690/001KVvQQgy711R7wpOh21&690

**Comment by rovo89** [comment]
No, this simply means that you're trying to use Xposed Installer 2.x on Lollipop/Marshmallow. The repo contains a clear hint that you need a different version from here instead, flashable via recovery: http://forum.xda-developers.com/showthread.php?t=3034811

As for getting Xposed running on the emulator, there's a different issue: https://github.com/rovo89/XposedTools/issues/7
