### ISSUE TITLE
false alarm how do I delete this issue?

### ISSUE THREAD

**Issue by Xstar97** [rovo89/Xposed#153]
FALSE ALARM...I was being stupid

**Comment by rovo89** [comment]
GitHub issues can't be deleted, you can just close them. By the way, even if it was a mistake, it would be good to keep the original text and just add a comment what the mistake (and the solution) was. That would help me and others in case somebody runs into the same mistake.

**Comment by Xstar97** [comment]
Sorry, I did brick, but wasnt because of the framework..it was because of a module called XHFW3...I was using it on my shield prior to v84, but when I flashed v84 with all modules still activated I became bricked...I then came here & state that, but then decided to reflashed xposed after unbricking so i disabled all modules & reflashed v84 & I did NOT brick:) so I kept enabling module after module until XHFW3..bricked:( me again!
so I completely forgot until now...I been very busy...
side note:
also dont get mad, I was going to tell you before releasing on google play, but I made a tool for android to install the xposed framwork on devices without a custom recovery...I couldnt wait to someone to build a custom recovery for my device...& I also wanted to support xposed for the devices without custom recoveries.
I been following up on error reports & made sure to block the incompatible devices
you can check it out here....https://play.google.com/store/apps/details?id=com.mcs.txi
