### ISSUE TITLE
re-Boot time increased after flashing xposed for lolipop 

### ISSUE THREAD

**Issue by Iamthedarkknight** [rovo89/Xposed#156]
Sir,
I have been using xposed since I started using Android.
Never had any issue before.
Recently I upgraded from cm11 to cm12.1 (sdk22/arm) and I found a very serious problem.
My phone didn't took much time to do a reboot before (30-50secs)
But right after installing xposed framework by recovery, it taking so much time when rebooting.
(Like I flashed a new rom and this is 1st reboot).
U wont believe, it almost taking 8  minute to complete a usual reboot now.
I searched on FAQ and found nothing about it.

Samsung Galaxy Star GTS5282
CYANOGENMOD 12.1
ARM V7
32BIT
(This happens on every reboot)

Regards,BatDroid

**Comment by Iamthedarkknight** [comment]
Sir, @rovo89
Little help here :-)

**Comment by Iamthedarkknight** [comment]
Sir, @rovo89
Little help here :-)

**Comment by rovo89** [comment]
It's totally normal that the first boot takes much longer, the whole ROM and all apps have to be recompiled.

Do further reboots also take that long? Could you please try it with all modules deactivated to ensure that it's really caused by the framework?

**Comment by Iamthedarkknight** [comment]
@rovo89
Sir,
Not only first re-boot,that happens always(on every reboot).

NO MODULE INSTALLED..

**Comment by rovo89** [comment]
Could you please post a logcat of the bootloop then?

**Comment by Godwinakansake** [comment]
Can someone helped?? I installed exposed framework on my itel1408 lollipop5.1 phone after which it keeps rebooting automatically every time a boot my phone!! Can someone helped
