### ISSUE TITLE
Cannot install on Xiaomi Mi 4S (Android 5.1-based)

### ISSUE THREAD

**Issue by CrisBarreiro** [rovo89/Xposed#159]
05-22 23:28:13.404 I/Xposed  (  470): -----------------
05-22 23:28:13.404 I/Xposed  (  470): Starting Xposed version 84, compiled for SDK 22
05-22 23:28:13.404 I/Xposed  (  470): Device: MI 4S (Xiaomi), Android version 5.1.1 (SDK 22)
05-22 23:28:13.404 I/Xposed  (  470): ROM: LMY47V
05-22 23:28:13.404 I/Xposed  (  470): Build fingerprint: Xiaomi/aqua/aqua:5.1.1/LMY47V/6.5.12:user/release-keys
05-22 23:28:13.404 I/Xposed  (  470): Platform: arm64-v8a, 64-bit binary, system server: yes
05-22 23:28:13.404 I/Xposed  (  470): SELinux enabled: yes, enforcing: yes
05-22 23:28:13.424 I/Xposed  (  470): -----------------
05-22 23:28:13.424 I/Xposed  (  470): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
05-22 23:28:14.034 I/Xposed  (  470): Detected ART runtime
05-22 23:28:14.054 I/Xposed  (  470): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
05-22 23:28:14.194 E/Xposed  (  470): Error while loading XResources class 'android/content/res/XResources':
05-22 23:28:14.194 E/Xposed  (  470): java.lang.IncompatibleClassChangeError: android.content.res.XResources
05-22 23:28:14.194 E/Xposed  (  470):   at java.lang.Class dalvik.system.DexFile.defineClassNative(java.lang.String, java.lang.ClassLoader, long) (DexFile.java:-2)
05-22 23:28:14.194 E/Xposed  (  470):   at java.lang.Class dalvik.system.DexFile.defineClass(java.lang.String, java.lang.ClassLoader, long, java.util.List) (DexFile.java:226)
05-22 23:28:14.194 E/Xposed  (  470):   at java.lang.Class dalvik.system.DexFile.loadClassBinaryName(java.lang.String, java.lang.ClassLoader, java.util.List) (DexFile.java:219)
05-22 23:28:14.194 E/Xposed  (  470):   at java.lang.Class dalvik.system.DexPathList.findClass(java.lang.String, java.util.List) (DexPathList.java:321)
05-22 23:28:14.194 E/Xposed  (  470):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:54)
05-22 23:28:14.194 E/Xposed  (  470):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:511)
05-22 23:28:14.194 E/Xposed  (  470):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:469)
05-22 23:28:14.194 E/Xposed  (  470):   at boolean de.robv.android.xposed.XposedBridge.initNative() (XposedBridge.java:-2)
05-22 23:28:14.194 E/Xposed  (  470):   at void de.robv.android.xposed.XposedBridge.main(java.lang.String[]) (XposedBridge.java:115)
05-22 23:28:14.194 I/Xposed  (  470): Errors during native Xposed initialization
05-22 23:28:23.244 I/Xposed  (  472): -----------------
05-22 23:28:23.244 I/Xposed  (  472): Starting Xposed version 84, compiled for SDK 22
05-22 23:28:23.244 I/Xposed  (  472): Device: MI 4S (Xiaomi), Android version 5.1.1 (SDK 22)
05-22 23:28:23.244 I/Xposed  (  472): ROM: LMY47V
05-22 23:28:23.244 I/Xposed  (  472): Build fingerprint: Xiaomi/aqua/aqua:5.1.1/LMY47V/6.5.12:user/release-keys
05-22 23:28:23.244 I/Xposed  (  472): Platform: arm64-v8a, 32-bit binary, system server: no
05-22 23:28:23.244 I/Xposed  (  472): SELinux enabled: yes, enforcing: yes
05-22 23:28:23.244 I/Xposed  (  472): -----------------
05-22 23:28:23.244 I/Xposed  (  472): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
05-22 23:28:23.484 I/Xposed  (  472): Detected ART runtime
05-22 23:28:23.504 I/Xposed  (  472): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
05-22 23:28:23.594 E/Xposed  (  472): Error while loading XResources class 'android/content/res/XResources':
05-22 23:28:23.594 E/Xposed  (  472): java.lang.IncompatibleClassChangeError: android.content.res.XResources
05-22 23:28:23.594 E/Xposed  (  472):   at java.lang.Class dalvik.system.DexFile.defineClassNative(java.lang.String, java.lang.ClassLoader, long) (DexFile.java:-2)
05-22 23:28:23.594 E/Xposed  (  472):   at java.lang.Class dalvik.system.DexFile.defineClass(java.lang.String, java.lang.ClassLoader, long, java.util.List) (DexFile.java:226)
05-22 23:28:23.594 E/Xposed  (  472):   at java.lang.Class dalvik.system.DexFile.loadClassBinaryName(java.lang.String, java.lang.ClassLoader, java.util.List) (DexFile.java:219)
05-22 23:28:23.594 E/Xposed  (  472):   at java.lang.Class dalvik.system.DexPathList.findClass(java.lang.String, java.util.List) (DexPathList.java:321)
05-22 23:28:23.594 E/Xposed  (  472):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:54)
05-22 23:28:23.594 E/Xposed  (  472):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:511)
05-22 23:28:23.594 E/Xposed  (  472):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:469)
05-22 23:28:23.594 E/Xposed  (  472):   at boolean de.robv.android.xposed.XposedBridge.initNative() (XposedBridge.java:-2)
05-22 23:28:23.594 E/Xposed  (  472):   at void de.robv.android.xposed.XposedBridge.main(java.lang.String[]) (XposedBridge.java:115)
05-22 23:28:23.594 I/Xposed  (  472): Errors during native Xposed initialization

**Comment by rovo89** [comment]
Is that a MIUI-based ROM?

**Comment by CrisBarreiro** [comment]
Yes, I am using Miui 7.4 beta

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.5.28&pv=5.1.1&source=email_footer_2] On Mon, May 23, 2016 at 2:27 PM, rovo89 < notifications@github.com [notifications@github.com] > wrote:
Is that a MIUI-based ROM?

**Comment by rovo89** [comment]
OK, then I won't look into it, I'm tired of making Xposed compatible with MIUI. If anyone has a fix, please let me know and I'll see if I can incorporate it.
