### ISSUE TITLE
How does Xposed Hook ART

### ISSUE THREAD

**Issue by mingwayzhang** [rovo89/Xposed#160]
This might not be a new question. But I feel my understanding on Xposed framework still remains in uncertainty. So, for each function of java code, ART maintains two version: 1) dalvik version and 2) native version. Specifically, how does Xposed hook these two versions respectively? Any feedback or pointers to code will be helpful. Thanks!

**Comment by rovo89** [comment]
The general idea is to turn the method into something similar as a proxy method. The most relevant parts in the code are here:
- https://github.com/rovo89/android_art/blob/3417f07d4c1c48cc6621cab79e43d06bff42be2c/runtime/art_method.cc#L603 (creates a backup of the method information and replaces the entry point of the method to `artQuickProxyInvokeHandler`)
- https://github.com/rovo89/android_art/blob/3417f07d4c1c48cc6621cab79e43d06bff42be2c/runtime/entrypoints/quick/quick_trampoline_entrypoints.cc#L725 (modified to call `InvokeXposedHandleHookedMethod`)
- https://github.com/rovo89/android_art/blob/3417f07d4c1c48cc6621cab79e43d06bff42be2c/runtime/entrypoints/entrypoint_utils.cc#L322 (copy of `InvokeProxyInvocationHandler`, adjusted to call `XposedBridge.handleHookedMethod`)

The native bytecode is usually executed, and Xposed forces it to be recompiled without a few of the optimizations like inlining, which would skip the call to the hooked method. The Dalvik bytecode is used in interpreter mode and for compiling to native code. There's not a big difference for hooking though, both modes will go through the proxy handling.
