### ISSUE TITLE
Android Pay doesn't work with Xposed

### ISSUE THREAD

**Issue by discipuloosho** [rovo89/Xposed#162]

**Comment by rovo89** [comment]
Yes. It's not a bug though - Android Pay simply makes sure that the system is unmodified to ensure that payments are safe. Xposed definitely is a big modification, so it's expected that Android Pay refuses to work. There are unofficial "systemless" versions of Xposed which don't modify the /system partition, but even that doesn't seem to make it work (it's only easier to temporarily deactivate Xposed). As I don't see it as the framework's task to hide Xposed from apps, I close this as "wontfix".

**Comment by discipuloosho** [comment]
Ok. Thanks very much. :)
