### ISSUE TITLE
Next Xposed release and SuperSU requirement

### ISSUE THREAD

**Issue by pizzadude** [rovo89/Xposed#168]
Sorry if this doesn't belong here, but I am concerned about the next update. The change log says that the next update will require SuperSU for systemless mode. Is systemless mode going to be optional? Will I be able to use my Superuser by phhusson (which works better for my phone) and opt not to use systemless mode? Just confused by the wording.

**Comment by rovo89** [comment]
Please ask such questions on XDA in the future, GitHub should be used for development. Anyway, systemless will be optional.
