### ISSUE TITLE
Samsung Stuck on Carrier Screen

### ISSUE THREAD

**Issue by PGMacDesign** [rovo89/Xposed#172]
Good day, as per this thread, http://forum.xda-developers.com/showthread.php?t=3034811 , it seems like this is still an issue with Samsung Devices. I am rooted, twrp installed, and ready to go, but (as it mentions in the thread), it gets stuck on the carrier screen and will not proceed past the Verizon Logo. 

Just wanting to check on an update for this to see if any new developments have occurred that allow Samsung devices to work with this framework. 

-PGMacDesign

(PS, running SM-N900, Samsung Galaxy Note 3, on Android 5.0, API 21. Also, bootloader is unlocked as per this thread - http://forum.xda-developers.com/verizon-galaxy-note-3/general/official-note-3-verizon-bootloader-t3359370 )

**Comment by aviraxp** [comment]
I think that you have to use the unofficial build by arter97.

http://forum.xda-developers.com/xposed/unofficial-xposed-samsung-lollipop-t3113463

**Comment by rovo89** [comment]
Indeed, you have to use an unofficial build. I think there are multiple ones, not sure which one is the best for your device.
