### ISSUE TITLE
Honor 6 stuck on boot screen after install

### ISSUE THREAD

**Issue by Ionaru** [rovo89/Xposed#175]
Hello,

Installing Xposed v86 on my Honor 6 will cause it to be stuck on the boot screen (I left it for ~10 minutes to make sure), is this common and/or fixable?

Info:
Honor 6 - L04 
Stock EMUI 4.0, build number B820 (H60-L04C432B820)
Trying to install Xposed Framework v86 sdk23 ARM
Used TWRP as recovery and install tool
Bootloader unlocked & rooted

**Comment by juanro49** [comment]
Same problem in Honor 6 Plus with EMUI 4.0 and Marshmallow

**Comment by Ionaru** [comment]
Turns out you just need to wait a little longer, my phone eventually booted after 20-25 minutes.

**Comment by juanro49** [comment]
Thanks, after 25 minutes, the phone start sucesfully! 😊

**Comment by rovo89** [comment]
Good to know. It's usual that the first boot takes longer because it has to recompile everything, but 25 minutes are long. Not sure what the reason is, can't say more without a full logcat of those 25 minutes.
