### ISSUE TITLE
Xposed on G4 marshmallow

### ISSUE THREAD

**Issue by G4forpresident** [rovo89/Xposed#180]
Hello. I found several threads on xda saying that xposed does not work on g4 with marshmallow. Earlier you gave a zip file which seems to work (as commented by most people here https://github.com/rovo89/Xposed/issues/100 )

But the link to te zip file now gives a 404 error. 
Can u reupload it?

My device

**Comment by rovo89** [comment]
That issue says:
> Fixed in v83. 

And obviously, any later version should have the fix as well, so try the latest version (currently v86).

**Comment by G4forpresident** [comment]
Where do i get that from? The xposed installer app says that it is only for devices runnig ics to kk. Sorry for being so stupid.

**Comment by rovo89** [comment]
If you're not able to find that out, you should better not use Xposed.

**Comment by G4forpresident** [comment]
Well till yesterday i was using xposed on my mobile which was stuck on jb. Today i got my new g4 and im confused. Mind helping me? Please.

**Comment by G4forpresident** [comment]
Never mind. I found it. I guess i was so used to installing xposed using the app i completely ignored the idea of flashing the framework using twrp.
