### ISSUE TITLE
SM G901F do not boot after installing 

### ISSUE THREAD

**Issue by 07AF** [rovo89/Xposed#181]
i installed the .zip with tprw and my 901f didn´t boot 

what can i do to get the xposed framework with sdk 23 

please help me

**Comment by rovo89** [comment]
Is that a Samsung ROM with TouchWiz?

**Comment by 07AF** [comment]
No it is a custom Rom android 6.0.1

Am 16.08.2016 06:06 schrieb "rovo89" <notifications@github.com>:
