### ISSUE TITLE
Not work 

### ISSUE THREAD

**Issue by intawad** [rovo89/Xposed#183]
i can't flash on wiko pulp 3g  Android 5.1 Lollipop
flash with twrp and file arm, arm64 and x86 or me do wrong method help me please

**Comment by rovo89** [comment]
This is not a support forum. Find out what platform you have and flash the correct ZIP from http://dl-xda.xposed.info/framework/sdk22/. If there's really a bug, follow https://github.com/rovo89/XposedBridge/wiki/Bugs
