### ISSUE TITLE
Not  Working in SM-N9005 Note 3 Bootloop

### ISSUE THREAD

**Issue by panchalvivek007** [rovo89/Xposed#184]
Dear  Xposed

Stock firmware

its  not  Working in Samsung Galaxy Note 3 SM-N9005  sdk 21
lollipop  armv7   I try  Install  zip  But  My  Phone gets bootloop

Please  help  out

Give  Me Linkk For My Phone

**Comment by RenjarP7** [comment]
https://github.com/rovo89/XposedBridge/wiki/Bugs

**Comment by rovo89** [comment]
Most likely, it's a TouchWiz ROM, which isn't supported by official Xposed versions.
