### ISSUE TITLE
forcing image recompilation

### ISSUE THREAD

**Issue by Grzec** [rovo89/Xposed#189]
I know i did something wrong but that went too far and need help please :)

I was on old android 5.1.1 with OxygenOS 2.0.2, xposed installer 3.0 alpha4
Did update last night, now OOS 3.1
I thought i uninstalled xposed and installed proper version but now im lost.

Help? :)

[error.log.txt](https://github.com/rovo89/Xposed/files/504115/error.log.txt)

**Comment by aviraxp** [comment]
Ask @topjohnwu for help. For now, you can clear cache and dalvik cache and try.

**Comment by Grzec** [comment]
That log is just after dalvik cache/cache wipe :/

**Comment by Grzec** [comment]
Got some sleep. 
Now it clearly seems that somehow I flashed two different (slightly) versions. One for 32bit (arm), one for 64 bit (ARM64). Hmmm since Im on OPT, need to uninstall 32 bit, methinks.  Going to look for Uninstaller now, but if anyone got ready link, I'd appreciate ;)

**Comment by aviraxp** [comment]
http://forum.xda-developers.com/xposed/unofficial-systemless-xposed-t3388268

**Comment by Grzec** [comment]
Oh snap. Can't use topjohwu's bc it says I don't have magisk... Well it might be true, I have never installed it ;) 

Tried every other Uninstaller but nothing. No idea what next...

**Comment by aviraxp** [comment]
But what you have flashed is topjohnwu's version. That is strange. And this version need Systemless SuperSU rather than magisk.

**Comment by Grzec** [comment]
Yeah, that's what I wanted and what I have. Systemless SU... :/

**Comment by rovo89** [comment]
Sorry, but I can't support unofficial versions. Besides that, GitHub isn't a good support platform as 237 watchers of this repository get an email for every single comment.
