### ISSUE TITLE
Respect Android Safe Mode

### ISSUE THREAD

**Issue by pylerSM** [rovo89/Xposed#19]
Disable Xposed in Android Safe Mode. Check for property "persist.sys.safemode" maybe?

**Comment by rovo89** [comment]
If it's as simple as checking one property, then yeah, why not. I have rarely reached safe mode myself though - how do you activate it? And how do you escape from it (which I hope would reset the property as well)?

One thing to note is that I can only imagine to check this during very early startup (in addition to the conf/disabled file). So it would effect the next start then.

**Comment by pylerSM** [comment]
http://www.talkandroid.com/guides/beginner/how-to-boot-your-android-phone-or-tablet-into-safe-mode-for-troubleshooting/

**Comment by pylerSM** [comment]
This wouldn't be so easy as I see. When restating to safe mode, persist.sys.safemode is set to 1. After reboot, persist.sys.safemode becomes null or 0 so we can't find out whether we are in safe mode or not (basically, we can, but not so early as Xposed needs)

I thought about restart/shutdown receiver and if we get intent, we can check for persist.sys.safemode and then create conf/disable file. @rovo89 ?

Others, any better idea?

**Comment by pylerSM** [comment]
Impossible to do. Closed.
