### ISSUE TITLE
bootloop for Android 6.0

### ISSUE THREAD

**Issue by zayan031** [rovo89/Xposed#191]
hi ,
I have a bootloop after flashing xposed-v86-sdk23-arm
please help!!!
how can I fixed it!!!

**Comment by rovo89** [comment]
Read and follow: https://github.com/rovo89/XposedBridge/wiki/Bugs

**Comment by thypon** [comment]
latest XposedInstaller 3.1 and xposed framework version: the problem starts since the last CyanogeMOD 13 merge of 6.0.1

http://pastebin.com/d11Q61SP

**Comment by wanam** [comment]
Same as https://github.com/rovo89/XposedBridge/issues/129 I guess.

**Comment by thypon** [comment]
Yep, same bug for me.
