### ISSUE TITLE
XSharedPreferences.edit() can not write data to application's SharedPreferece?

### ISSUE THREAD

**Issue by UltramanTIGA** [rovo89/Xposed#193]
I use XSharedPreferences.edit() to get a Editor.class and then use it to change sharedpreference's data,but it is not useful!
I can only read data from the SharedPreference,but can't write and change it's data!
Anyone konw about it?Please help me!Thanks a lot.

**Comment by C3C0** [comment]
XSharedPreferences is readonly. You cannot use it to update preferences.

**Comment by rovo89** [comment]
Indeed, here's the API documentation: http://api.xposed.info/reference/de/robv/android/xposed/XSharedPreferences.html

Writing the preferences is not possible for various reasons (especially with SELinux) and can cause issues. Sorry, I don't have time to explain all the technical details... Anyway, I think someone built an implementation that's backed by a ContentProvider, not sure if that would work for you.
