### ISSUE TITLE
How to make Xposed module A to hide its own behavior (API calls) to module B?

### ISSUE THREAD

**Issue by mingwayzhang** [rovo89/Xposed#195]
Hi rovo89,

I have a question on the making API call invisible to to the other module. In fact, my situation is that I have two modules A and B (Priority(A) > Priority(B)). A hooks an API and do something. However, this module will generate some sensitive API calls that will be visible to B (B is a logger module). So, how do I do to make B not logging A's behavior? Thanks.

**Comment by rovo89** [comment]
First off - https://github.com/rovo89/XposedBridge would have been the better place for such a question.

Your question means that you want to call that method without B's hooks being fired. There's a [invokeOriginalMethod()](http://api.xposed.info/reference/de/robv/android/xposed/XposedBridge.html#invokeOriginalMethod(java.lang.reflect.Member,%20java.lang.Object,%20java.lang.Object[])) which calls a method without invoking any of the hooks. However, that works only if you're calling exactly the method that B has hooked. If method X calls method Y, module A calls method X and module B hooks method Y, then that hook would still fire.
