### ISSUE TITLE
Latest security update

### ISSUE THREAD

**Issue by arter97** [rovo89/Xposed#200]
I guess you'd be already aware of this issue, but latest security update from Google seems to break Xposed.

https://github.com/android/platform_frameworks_base/commit/b8be33b0bedec211708c4525b9d3f3b4effb385c
Added from android-6.0.1_r71 and upward, now Zygote has a whitelisting policy for which files are allowed to be opened(core/jni/fd_utils-inl.h line 50).

Since Xposed opens up files from /data/app, IsWhitelisted() from core/jni/fd_utils-inl.h returns false and aborts.

I added a dirty hack for my CM ROM, which admittedly is not the best solution :
https://github.com/arter97/android_frameworks_base/commit/35724b039e7a990950100354d01467c05756de37

I'm curious how you can fix this for upcoming OSS/Manufacturer's ROMs.

Cheers :)

**Comment by rovo89** [comment]
https://github.com/rovo89/XposedBridge/issues/129
Feel free to comment if you have an idea how this can be solved in Xposed. :)
