### ISSUE TITLE
grorkmod_v1.1 lite.zip

### ISSUE THREAD

**Issue by Amidius64** [rovo89/Xposed#205]
After flashing successfully the above file in order to gain functioning all my modules (none was working)
within Xposed, now i am finding ( i am not sure that there is a relationship, but at the moment i can't think of anything else) that when i try to install any apk from a SD external card using ES explorer, it gets stuck on the pop up offering to install and it forces ES to shut. i have to use  Root Browser instead to install from the storage an apk. How weird?
Is it possible that every app has its own permissive/forcing status in a way that what is good from some apps is not working for others? Something has been altered, i guess
In fact now i have Viper4Android app working where previously the driver was shown as 'abnormus' then not enabling the app. Just wondering...
Would you mind to shed some light on this?

**Comment by rovo89** [comment]
I don't know that file, you better ask the one who uploaded it.
