### ISSUE TITLE
Oneplus 2 (oxygenos 3.5.6) boot loop

### ISSUE THREAD

**Issue by j3dd4h** [rovo89/Xposed#208]
The xposed version 86/87 is not working (boot loop)  on oxygenos 3.5.6

**Comment by rovo89** [comment]
Have you tried to do something differently? Maybe that will fix it.

**Comment by c6opuc** [comment]
I have the same issue when using Xposed with Magisk. I was told that oxygenos update breaks Xposed somehow and the guys told me to report an issue here. See details: https://forum.xda-developers.com/apps/magisk/problems-magisk-xposed-oxygenos-3-5-5-t3525038/post70248888#post70248888

**Comment by c6opuc** [comment]
Is there any news on this?

**Comment by rovo89** [comment]
Without logs, that's not possible: https://github.com/rovo89/XposedBridge/wiki/Bugs

**Comment by rovo89** [comment]
Oh, and please make sure to install Xposed normally. I didn't know what Magisk does and how it might contribute to the boot loop.

**Comment by josh598208** [comment]
First of all thank you for your work rovo89. I'm having the same issue trying to install Xposed on oxygen os 3.5.6. how would I go about getting the logs you need? I'd be more than happy to send them to you.

**Comment by josh598208** [comment]
Nevermind, I'm reading your link now. I'll figure it out.
