### ISSUE TITLE
[LP] ART inlines very simple methods

### ISSUE THREAD

**Issue by DavisNT** [rovo89/Xposed#21]
In current Xposed for Lollipop alpha it is not possible to hook very simple methods (e.g. `method2()` from unmodified code sample https://github.com/DavisNT/XposedLollipopTests/ ). 
Most likely this happens due to inlining of very simple methods (when uncommenting `Log.i()` inside `method2()` the method becomes hookable).

**Comment by rovo89** [comment]
This issue was moved to rovo89/android_art#4
