### ISSUE TITLE
Segmentation fault with specific apks

### ISSUE THREAD

**Issue by ltkatana** [rovo89/Xposed#210]
Environment Information:
Google Android Emulator (QEMU-based)
Android API Level 19 Dev Build
Kernel Goldfish 3.4.67 with COMMIT-Level: 2011b1c083fe4913aa458e22b050b7186f1d28ae
Used Xposed-Installer-Version: 2.6.1
Architecture: x86

Specific Settings:
JIT_CACHE_OFFSET: 148 (Tried 148 and it fixed my Seg-Faults after framework installation)

Affected APKs:
flv.mobile.android.apk ([Logcat PasteBin-URL](http://pastebin.com/ZhJG4YtFl))
com.onkyo.onkyoRemote.apk ([Logcat PasteBin-URL](http://pastebin.com/K3hQR2JS))
epiktest.apk (is a own developed apk)

Only three of fifteen tested apks are affected.
If running the emulator without xposed even with the three affected apks, the segmenation fault does not occur. If xposed is installed the segmentation fault occurance is repeatable.

Segmentation faults are reproduceable.

I have access to the libdvm.so and a proper decompiler. What is the complete offset to the jit-flag?

Error does not occur while using API Level 19 with arm architecture with installed Xposed-Installer-Version: 2.6.1.

**Comment by ltkatana** [comment]
Any idea on this? i still hope i got the cache offset wrong.

**Comment by rovo89** [comment]
It's the offset for `codeCacheFull` in the `gDvmJit` variable. You can check the Dalvik source code here to see where it's used: https://github.com/android/platform_dalvik/tree/kitkat-mr2.2-release
Then you can try to locate some usage of that variable and look up what the disassembly looks like for these statements. Not sure which ones I checked back then, this was like years ago.

**Comment by rovo89** [comment]
But if you're using the official emulator, I can hardly imagine that the offset needs to be modified from the default (120)... this was only necessary for a rare issues with a few ROMs that were modified by the vendor.

**Comment by ltkatana** [comment]
I am using a self built system.img with architecture x86 i don't know why but if not modifying the offset i get instant segfaults after emulator bootup, it seems like the system.img i use with arm architecture and the system.img i use with x86 are not the same. But thanks for the info i will check that and report as fast as possible.

**Comment by ltkatana** [comment]
rovo89, i finally found the difference.
The problem with my x86 image is that i have included libhoudini which replaces libdvm.so
Thats the reason why offset 148 was necessary and these three apks don't work.
You can close this issue with the note "libhoudini incompatibility"

**Comment by ltkatana** [comment]
Addition: Trying to manually patch the Dalvik-VM for libhoudini-Usage also results in Segmentation faults, although the offset is no longer needed
