### ISSUE TITLE
Extremely long boot times and slow phone with Xposed installed

### ISSUE THREAD

**Issue by Pswado** [rovo89/Xposed#211]
My boot times would usually be around 40 seconds, but with Xposed it takes around 15 minutes and everything is extremely slow to load. Scrolling is also stuttery and the phone gets very hot. The phone im using is a Samsung Galaxy A7 (A700-FD) on CM13. I dont have any modules installed yet, so modules should not be the issue. Is it a compatibility issue? I really want Xposed on my phone. Im using the latest version of the Xposed framework. When using liveboot after Xposed is installed there are a lot of I/thermal engine( 392): Mitigation:CLUSTER[1]: $$$$$$$ khz ($ stands for numbers) lines when booting up and they keep going on and on and on.

**Comment by rovo89** [comment]
Can you please post a full log? https://github.com/rovo89/XposedBridge/wiki/Bugs
The line you mentions seems to fit to "the phone gets very hot", but it's not related to Xposed.

**Comment by Pswado** [comment]
I have already removed xposed because my phone would take just too long to boot, and it would always restart randomly when im in the middle of something.
