### ISSUE TITLE
Question about xposed nougat version.

### ISSUE THREAD

**Issue by JustAkan** [rovo89/Xposed#212]
We appreciate your use of Google Translator.

I am a bullhead user who is interested in Xposed.
Lastly, the last time I saw it on the Xda forum, rovo89 is working on a version of xposed nougat, and I'm finally getting feedback that I'm trying to fix it because of the jit problem. Since then, we have been unable to hear the news from google + etc since the security patch response in November. Please let me know if you have the most recent progress on the current Xposed nougat version and if there is anything we can help you with.
Thank you.

**Comment by newstart** [comment]
Per this: https://forum.xda-developers.com/showthread.php?t=3034811&page=5

He told us to do the math ourself....

14 days * 24 hours = 336 hours of work he estimates Android N needs. He only devotes 5 hours a week, so divide 336/5 and he needs 67.2 weeks. There are 52 weeks in a year. So he practically just told us he needs more than year to finish xPosed on N.

I gave up on the project. N has been out for a long time and now he says he needs about another year? Screw that. By then, Android O will be out and I am sure there will be another waiting game.

**Comment by Boliye** [comment]
Maybe you can push your current progress on nougat to github so other developers with more spare time could contribute to your work @rovo89?

**Comment by MartinX3** [comment]
@Boliye @rovo89 
Yes please!

**Comment by Radzhab** [comment]
@rovo89 Open crowdfunding company, please.

**Comment by rovo89** [comment]
Guys, it's done when it's done. Many people offer their help, but keep in mind that you'll need much in-depth knowledge about how compilers work in general and how ART works in particular. It's not just about the amount of work, it's mainly about the complexity. Yesterday, I worked maybe 3-4 hours on Xposed, and I've written just a few lines of code. The rest of the time was spent to do even more research on how certain things work internally and what edge cases could occur. I still believe it's worth it though, as only this way, I can integrate Xposed properly into ART.

**Comment by JustAkan** [comment]
@rovo89 Yes. But the problem I'm talking about is that rovo89 alone takes a lot of time to integrate Nougat's ART. Actually, there are a lot of advanced developers besides new arter97 who corrected the art problem of Samsung devices. I think that it is good for those advanced developers to help nougat ART + Xposed once you release some xposed nougat sources.

**Comment by jerdog** [comment]
I'm going to throw my 2 cents in here. @rovo89 isn't saying he's against help as much as he's saying the amount of work needed to do the work he's doing _and_ code review everyone else's work that would be trying to contribute (with varying levels of code quality and experience into the deeper levels) would negatively affect the outcome of the project. For lack of a better phrase, "it'll be done when it's done."

**Comment by andreasxD** [comment]
Xposed on 7.1 release or not ??

**Comment by andreasxD** [comment]
Xposed on 7.1 release or not ??

**Comment by newstart** [comment]
@AndreasxD, I already addressed this.

He told us to do the math ourself....

14 days * 24 hours = 336 hours of work he estimates Android N needs. He only devotes 5 hours a week, so divide 336/5 and he needs 67.2 weeks. There are 52 weeks in a year. So he practically just told us he needs more than year to finish xPosed on N.

**Comment by andreasxD** [comment]
Can we help on something to finish faster ??

**Comment by newstart** [comment]
> Can we help on something to finish faster ??

He said no. He'll be done when he is done. To be fair though, N has been out for a long time now and we have lived without xPosed. Just move on and forget it. 

Gonna unsubscribe to this thread now. Adios.

**Comment by MartinX3** [comment]
Or we don't upgrade from Marshmallow to a later version, because of the lack of XPosed...

**Comment by newstart** [comment]
>Or we don't upgrade from Marshmallow to a later version, because of the lack of XPosed...

... and miss security updates? Before with CM maintaining CM 13 and CM 14.1, it was possible. Now LOS only maintains 14.1 for many devices. So if you want to run M, good luck staying updated, unless you have a phone company that actually cares about you as a customer.

**Comment by rovo89** [comment]
I'll close this now because it's leading nowhere. With an unknown amount of remaining work and an unknown amount of time that I can spend, it's impossible to give even a rough estimation when it will be done. All I wanted to say it's a highly complex topic that takes its time. Now if you could let me concentrate on development instead of reading speculations, that would be great. Thanks.
