### ISSUE TITLE
can you compile and release x86_64 version

### ISSUE THREAD

**Issue by LinBoLen** [rovo89/Xposed#213]
currently there are no ./system/lib64/*.so in released framework.

**Comment by AnClark** [comment]
Source code is provided here. Remember this is Github, you can compile your own version for your own platform.

**Comment by xsilen** [comment]
actually, i can't. it will take my to learn how to compile

**Comment by brainvision** [comment]
did you make some progress man?

**Comment by LinBoLen** [comment]
noop. I use compiled x86_64 from other's contribution.
