### ISSUE TITLE
Xposed framework version 87 not install ing

### ISSUE THREAD

**Issue by nazgol20** [rovo89/Xposed#214]
Dear Sir,

Good morning 

First of all I should appreciate your great ​great​ work , I have now problem with installing version 87. I always got error 1.  What is this error, and Where is the source of problem , please advise.

I am using a rooted note 4 with magisk installed.

**Comment by rovo89** [comment]
Could you please post the exact error message? Are you using the official ZIP or some customized version?

**Comment by Ridwanhidayat** [comment]
Enable
