### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by liumengdeqq** [rovo89/Xposed#218]
frameworks/base/cmds/xposed/libxposed_art.cpp:189: error: undefined reference to 'art::mirror::Object::Clone(art::Thread*, unsigned int)'
   frameworks/base/cmds/xposed/libxposed_art.cpp:189: error: undefined reference to 'art::mirror::Object::Clone(art::Thread*, unsigned int)'
   frameworks/base/cmds/xposed/libxposed_art.cpp:189: error: undefined reference to 'art::mirror::Object::Clone(art::Thread*, unsigned int)'
   frameworks/base/cmds/xposed/libxposed_art.cpp:85: error: undefined reference to 'art::mirror::ArtMethod::xposed_callback_class'
   collect2: error: ld returned 1 exit status
   make: *** [out/target/product/s900_96board/obj/SHARED_LIBRARIES/libxposed_art_intermediates/LINKED/libxposed_art.so] 错误 1
   make: *** 正在等待未完成的任务....

**Comment by rovo89** [comment]
https://github.com/rovo89/Xposed/issues/217
