### ISSUE TITLE
[LP] Sometimes app crashes after update without reboot

### ISSUE THREAD

**Issue by DavisNT** [rovo89/Xposed#22]
The code sample https://github.com/DavisNT/XposedLollipopTests/ starts to crash on opening with 
```
I/ActivityManager( 2446): Process lv.id.dm.xposedlollipoptests (pid 11033) has died
I/Zygote ( 1951): Process 11033 exited due to signal (11)
W/ActivityManager( 2446): Force removing ActivityRecord{35967343 u0 lv.id.dm.xposedlollipoptests/.MainActivity t1002}: app died, no saved state
W/WindowManager( 2446): Failed looking up window
W/WindowManager( 2446): java.lang.IllegalArgumentException: Requested window android.view.ViewRootImpl$W@3e2ab333 does not exist
W/WindowManager( 2446): at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8504)
W/WindowManager( 2446): at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8495)
W/WindowManager( 2446): at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2604)
W/WindowManager( 2446): at com.android.server.wm.Session.remove(Session.java:186)
W/WindowManager( 2446): at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:2927)
W/WindowManager( 2446): at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5397)
W/WindowManager( 2446): at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3230)
W/WindowManager( 2446): at android.os.Handler.dispatchMessage(Handler.java:102)
W/WindowManager( 2446): at android.os.Looper.loop(Looper.java:135)
W/WindowManager( 2446): at android.os.HandlerThread.run(HandlerThread.java:61)
W/WindowManager( 2446): at com.android.server.ServiceThread.run(ServiceThread.java:46)
```
after repeatedly uncommenting/commenting `Log.i()` inside `method2()` and launching the app (without reboot).
Reboot usually solves this issue (probably cases when reboot does not help is a different issue). It is unclear whether this happens due to changed Xposed module or target app.

**Comment by rovo89** [comment]
Is there anything more in the log, especially a native crash log for signal 11? I assume that the crash shown in the log excerpt above is just a follow-up error.

**Comment by DavisNT** [comment]
There is: 
```
I/ActivityManager( 2446): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=lv.id.dm.xposedlollipoptests/.MainActivity} from uid 10083 on display 0
I/ActivityManager( 2446): Start proc lv.id.dm.xposedlollipoptests for activity lv.id.dm.xposedlollipoptests/.MainActivity: pid=10025 uid=10333 gids={50333, 9997} abi=armeabi-v7a
I/art     (10025): Late-enabling -Xcheck:jni
W/art     (10025): Failed to find OatDexFile for DexFile /data/app/lv.id.dm.xposedlollipoptests-1/base.apk ( canonical path /data/app/lv.id.dm.xposedlollipoptests-1/base.apk) with checksum 0x2fee99f4 in OatFile /data/dalvik-cache/arm/data@app@lv.id.dm.xposedlollipoptests-1@base.apk@classes.dex
I/Zygote  ( 1951): Process 10025 exited due to signal (11)
I/ActivityManager( 2446): Process lv.id.dm.xposedlollipoptests (pid 10025) has died 
```
and before it there are also these lines:
```
W/art     ( 2446): Long monitor contention event with owner method=void com.android.server.pm.PackageManagerService.removePackageDataLI(com.android.server.pm.PackageSetting, int[], boolean[], com.android.server.pm.PackageManagerService$PackageRemovedInfo, int, boolean) from PackageManagerService.java:11583 waiters=0 for 194ms
I/PackageManager( 2446): Package lv.id.dm.xposedlollipoptests codePath changed from /data/app/lv.id.dm.xposedlollipoptests-1 to /data/app/lv.id.dm.xposedlollipoptests-2; Retaining data and using new
I/art     ( 2446): DexFile_isDexOptNeeded failed to open oat file '/data/dalvik-cache/arm/data@app@lv.id.dm.xposedlollipoptests-2@base.apk@classes.dex' for file location '/data/app/lv.id.dm.xposedlollipoptests-2/base.apk': Failed to open oat filename for reading: No such file or directory
I/art     ( 2446): DexFile_isDexOptNeeded failed to open oat file '/data/app/lv.id.dm.xposedlollipoptests-2/arm/base.odex' for file location '/data/app/lv.id.dm.xposedlollipoptests-2/base.apk': Failed to open oat filename for reading: No such file or directory
I/art     ( 2446): DexFile_isDexOptNeeded failed to open oat file '/data/dalvik-cache/arm/data@app@lv.id.dm.xposedlollipoptests-2@base.apk@classes.dex' for file location '/data/app/lv.id.dm.xposedlollipoptests-2/base.apk': Failed to open oat filename for reading: No such file or directory
I/art     ( 2446): DexFile_isDexOptNeeded failed to open oat file '/data/app/lv.id.dm.xposedlollipoptests-2/arm/base.odex' for file location '/data/app/lv.id.dm.xposedlollipoptests-2/base.apk': Failed to open oat filename for reading: No such file or directory
I/PackageManager( 2446): Running dexopt on: /data/app/lv.id.dm.xposedlollipoptests-2/base.apk pkg=lv.id.dm.xposedlollipoptests isa=arm vmSafeMode=false
E/cutils-trace( 8560): Error opening trace file: No such file or directory (2)
I/dex2oat ( 8560): /system/bin/dex2oat --zip-fd=11 --zip-location=/data/app/lv.id.dm.xposedlollipoptests-2/base.apk --oat-fd=12 --oat-location=/data/dalvik-cache/arm/data@app@lv.id.dm.xposedlollipoptests-2@base.apk@classes.dex --instruction-set=arm --instruction-set-features=default --runtime-arg -Xms64m --runtime-arg -Xmx512m
```

**Comment by Maxr1998** [comment]
Love you!!!
Only issue: they didn't fix only on reboot, a second install worked as well. But I am really thankful this is fixed :)

**Comment by zeezoo788** [comment]
> The code sample https://github.com/DavisNT/XposedLollipopTests/ starts to crash on opening with
> 
> ```
> I/ActivityManager( 2446): Process lv.id.dm.xposedlollipoptests (pid 11033) has died
> I/Zygote ( 1951): Process 11033 exited due to signal (11)
> W/ActivityManager( 2446): Force removing ActivityRecord{35967343 u0 lv.id.dm.xposedlollipoptests/.MainActivity t1002}: app died, no saved state
> W/WindowManager( 2446): Failed looking up window
> W/WindowManager( 2446): java.lang.IllegalArgumentException: Requested window android.view.ViewRootImpl$W@3e2ab333 does not exist
> W/WindowManager( 2446): at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8504)
> W/WindowManager( 2446): at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8495)
> W/WindowManager( 2446): at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2604)
> W/WindowManager( 2446): at com.android.server.wm.Session.remove(Session.java:186)
> W/WindowManager( 2446): at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:2927)
> W/WindowManager( 2446): at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5397)
> W/WindowManager( 2446): at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3230)
> W/WindowManager( 2446): at android.os.Handler.dispatchMessage(Handler.java:102)
> W/WindowManager( 2446): at android.os.Looper.loop(Looper.java:135)
> W/WindowManager( 2446): at android.os.HandlerThread.run(HandlerThread.java:61)
> W/WindowManager( 2446): at com.android.server.ServiceThread.run(ServiceThread.java:46)
> ```
> 
> after repeatedly uncommenting/commenting `Log.i()` inside `method2()` and launching the app (without reboot).
> Reboot usually solves this issue (probably cases when reboot does not help is a different issue). It is unclear whether this happens due to changed Xposed module or target app.

Duplicate of #

**Comment by DavisNT** [comment]
@zeezoo788 If this bug has reappeared in recent unofficial ports of Xposed framework, I suggest to report the bug to authors of those ports.
