### ISSUE TITLE
Xposed v87 causes some Google account preferences menu entries to fail on clean flash

### ISSUE THREAD

**Issue by AuroraWright** [rovo89/Xposed#220]
Hi, I'm using SultanXDA's CAF-based CM for the OnePlus One: https://forum.xda-developers.com/oneplus-one/orig-development/rom-kernel-unofficial-cyanogenmod-13-0-t3242700 (which integrates all the latest security patches, if that might be of interest) and the latest ARM build of xposed for API23 (v87).
On a clean ROM flash (weirdly enough the issue doesn't manifest if those menus were already opened before installing xposed), selecting Settings -> Google -> Sign-in & Security/Account Preferences/Personal info & Privacy leads to the error "An error has occurred, please try again later". The issue doesn't occur without installing xposed.

Logcat is as follows:
``` 
02-27 16:40:09.247  1936  3389 W GLSUser : [AppCertManager] IOException while requesting key: 
02-27 16:40:09.247  1936  3389 W GLSUser : java.io.IOException: Invalid device key response.
02-27 16:40:09.247  1936  3389 W GLSUser : 	at evk.a(:com.google.android.gms:274)
02-27 16:40:09.247  1936  3389 W GLSUser : 	at evk.a(:com.google.android.gms:4238)
02-27 16:40:09.247  1936  3389 W GLSUser : 	at evk.a(:com.google.android.gms:170)
02-27 16:40:09.247  1936  3389 W GLSUser : 	at evj.a(:com.google.android.gms:63)
02-27 16:40:09.247  1936  3389 W GLSUser : 	at evh.onTransact(:com.google.android.gms:58)
02-27 16:40:09.247  1936  3389 W GLSUser : 	at android.os.Binder.transact(Binder.java:387)
02-27 16:40:09.247  1936  3389 W GLSUser : 	at bxp.onTransact(:com.google.android.gms:35)
02-27 16:40:09.247  1936  3389 W GLSUser : 	at android.os.Binder.execTransact(Binder.java:453)
02-27 16:40:09.248  1936  3389 W GLSUser : [DeviceKeyStore] Cannot load key: Device key file not found.
02-27 16:40:09.282  2128  2638 W System.err: java.lang.Exception: Error converting session
02-27 16:40:09.283  2128  2638 W System.err: 	at wzb.log(:com.google.android.gms:359)
02-27 16:40:09.283  2128  2638 W System.err: 	at wzb.toSession(:com.google.android.gms:314)
02-27 16:40:09.283  2128  2638 W System.err: 	at com.google.android.gms.org.conscrypt.ClientSessionContext.getSession(:com.google.android.gms:85)
02-27 16:40:09.283  2128  2638 W System.err: 	at com.google.android.gms.org.conscrypt.SSLParametersImpl.getCachedClientSession(:com.google.android.gms:790)
02-27 16:40:09.283  2128  2638 W System.err: 	at com.google.android.gms.org.conscrypt.SSLParametersImpl.getSessionToReuse(:com.google.android.gms:413)
02-27 16:40:09.283  2128  2638 W System.err: 	at com.google.android.gms.org.conscrypt.OpenSSLSocketImpl.startHandshake(:com.google.android.gms:323)
02-27 16:40:09.283  2128  2638 W System.err: 	at com.google.android.gms.common.net.SSLCertificateSocketFactory.verifyHostname(:com.google.android.gms:214)
02-27 16:40:09.284  2128  2638 W System.err: 	at com.google.android.gms.common.net.SSLCertificateSocketFactory.createSocket(:com.google.android.gms:504)
02-27 16:40:09.284  2128  2638 W System.err: 	at axzu.run(:com.google.android.gms:345)
02-27 16:40:09.284  2128  2638 W System.err: 	at axyi.run(:com.google.android.gms:154)
02-27 16:40:09.284  2128  2638 W System.err: 	at llt.run(:com.google.android.gms:450)
02-27 16:40:09.284  2128  2638 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
02-27 16:40:09.284  2128  2638 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
02-27 16:40:09.284  2128  2638 W System.err: 	at lqc.run(:com.google.android.gms:17)
02-27 16:40:09.285  2128  2638 W System.err: 	at java.lang.Thread.run(Thread.java:818)
02-27 16:40:09.285  2128  2638 W System.err: Caused by: java.io.IOException: error:100000a0:SSL routines:OPENSSL_internal:INVALID_SSL_SESSION
02-27 16:40:09.286  2128  2638 W System.err: 	at com.google.android.gms.org.conscrypt.NativeCrypto.d2i_SSL_SESSION(Native Method)
02-27 16:40:09.286  2128  2638 W System.err: 	at com.google.android.gms.org.conscrypt.OpenSSLSessionImpl.<init>(:com.google.android.gms:87)
02-27 16:40:09.286  2128  2638 W System.err: 	at wzb.toSession(:com.google.android.gms:311)
02-27 16:40:09.286  2128  2638 W System.err: 	... 13 more
02-27 16:40:09.310  2128  2638 W Conscrypt: Could not set socket write timeout: null
02-27 16:40:09.365  2128  2638 W Conscrypt: Could not set socket write timeout: null
02-27 16:40:09.463  2128  9073 E AccountSettings: [Operation,GetScreensFromBackend] Unable to retrieve screen from backend
02-27 16:40:09.463  2128  9073 E AccountSettings: axuq: INVALID_ARGUMENT: Application credential header not valid. Please fix the client to pass a valid application credential header.
02-27 16:40:09.463  2128  9073 E AccountSettings: 	at axum.c(:com.google.android.gms:505)
02-27 16:40:09.463  2128  9073 E AccountSettings: 	at lgb.a(:com.google.android.gms:168)
02-27 16:40:09.463  2128  9073 E AccountSettings: 	at cxi.a(:com.google.android.gms:2079)
02-27 16:40:09.463  2128  9073 E AccountSettings: 	at lin.run(:com.google.android.gms:111)
02-27 16:40:09.463  2128  9073 E AccountSettings: 	at llt.run(:com.google.android.gms:450)
02-27 16:40:09.463  2128  9073 E AccountSettings: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
02-27 16:40:09.463  2128  9073 E AccountSettings: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
02-27 16:40:09.463  2128  9073 E AccountSettings: 	at lqc.run(:com.google.android.gms:17)
02-27 16:40:09.463  2128  9073 E AccountSettings: 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by rovo89** [comment]
Could this be the same as #207? Do you have any modules installed?

**Comment by AuroraWright** [comment]
No, zero modules. It happens just after a clean flash (ROM + gapps + xposed). Disabling xposed from the app doesn't fix it either.

**Comment by AuroraWright** [comment]
I found out it can be reproduced reliably by emptying Google Play Services' data while Xposed is installed (maybe the play services compile something in their /data folder, and it's affecting that/those binary/ies).

**Comment by taxilof** [comment]
Thanks for the report. Google account preferences now work again on my Nexus 4 with CM12.1 (5.1.1). I have disabled Xposed. This bug also lead to a lot of battery usage by Googe Play services.

This bug was already present on Xposed V79.

**Comment by ChristophHeilmann** [comment]
I have exactly the same issue with KitKat AOSP and Xposed 2.6.1

**Comment by ChristophHeilmann** [comment]
I decompiled Google Play Services with Apktools and found in evk.smali:

Line 30-73:

# direct methods
.method static constructor <clinit>()V
    .locals 5

    .prologue
    .line 51
    new-instance v0, Lled;

    const-string v1, "GLSUser"

    const/4 v2, 0x1

    new-array v2, v2, [Ljava/lang/String;

    const/4 v3, 0x0

    const-string v4, "AppCertManager"

    aput-object v4, v2, v3

    invoke-direct {v0, v1, v2}, Lled;-><init>(Ljava/lang/String;[Ljava/lang/String;)V

    sput-object v0, Levk;->a:Lled;

    .line 54
    const-string v0, "UTF-8"

    invoke-static {v0}, Ljava/nio/charset/Charset;->forName(Ljava/lang/String;)Ljava/nio/charset/Charset;

    move-result-object v0

    sput-object v0, Levk;->b:Ljava/nio/charset/Charset;

    .line 65
    new-instance v0, Ljava/lang/ref/WeakReference;

    const/4 v1, 0x0

    invoke-direct {v0, v1}, Ljava/lang/ref/WeakReference;-><init>(Ljava/lang/Object;)V

    sput-object v0, Levk;->j:Ljava/lang/ref/WeakReference;

    return-void
.end method


Line 346:

const-string v2, "Invalid device key response."


Line 1199:

const-string v7, "device_key"

**Comment by ChristophHeilmann** [comment]
Line 242:

const-string v3, "HMACSHA256"

Line 1000:

const-string v8, "dg_androidId"

maybe the androidid changes when you install xposed

**Comment by ChristophHeilmann** [comment]
No, i think this is wrong. dg means probably delegate.

So I suppose the HMAC is generated by:

[(dg_androidId dg_session dg_gmsCoreVersion dg_sdkVersion device_key)SHA256] -> Server

**Comment by ChristophHeilmann** [comment]
The server needs the device key for authentication so when you sign in the Google account for the first time the key will be generated, submitted to the server and if it's a valid key it will be stored. If the key is stored the client knows that the server has a valid key and will not generate and submit it once more.

When you install xposed before that you will get an invalid key which will not be stored.

**Comment by AuroraWright** [comment]
Why does xposed get you an invalid key? Which one of those variables isn't valid?

**Comment by ChristophHeilmann** [comment]
I don't know. The key is generated with a randomized byte array:



new-instance v0, Ljava/security/SecureRandom;

invoke-direct {v1, v2, v3}, Ljavax/crypto/spec/SecretKeySpec;-><init>([BLjava/lang/String;)V

invoke-virtual {v0, v1}, Ljavax/crypto/Mac;->init(Ljava/security/Key;)V
:try_end_0
.catch Ljava/security/InvalidKeyException; {:try_start_0 .. :try_end_0} :catch_0

.line 299
sget-object v1, Levk;->b:Ljava/nio/charset/Charset;

invoke-virtual {p1, v1}, Ljava/lang/String;->getBytes(Ljava/nio/charset/Charset;)[B

move-result-object v1

 invoke-virtual {v0, v1}, Ljavax/crypto/Mac;->doFinal([B)[B

**Comment by ChristophHeilmann** [comment]
I suppose the client requests a json string. So it could be an issue with libjavacore.so

**Comment by zputnyq** [comment]
I experience it too on my rooted kitkat stock  with xposed 2.6.1 & 2.7 ecperimental 1, I don't know for the previous xposed.
I think most xposed's users experience it but they don't realize it, since most of them rarely touches google play service setting eventhough they touch it, they won't know because the notification on play service is looked like a connection problem.

**Comment by AuroraWright** [comment]
This seems to be fixed on Nougat + Xposed v89 (not sure if due to Xposed or Google's changes). Closing.
