### ISSUE TITLE
Can't activate or see any downloaded modules

### ISSUE THREAD

**Issue by rhysh43** [rovo89/Xposed#224]
03-26 21:35:54.885 I/Xposed  (  277): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
03-26 21:35:55.150 I/Xposed  (  277): Detected ART runtime
03-26 21:35:55.161 I/Xposed  (  277): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
03-26 21:35:55.452 E/Xposed  (  277): Cannot load any modules because /data/data/de.robv.android.xposed.installer/conf/modules.list was not found
03-26 21:51:37.918 I/XposedInstaller(22533): Downloaded http://dl.xposed.info/repo/partial/11852.xml.gz with status 0 (error: null), size 1304 bytes
03-26 21:51:37.941 I/XposedInstaller(22533): Updated repository http://dl.xposed.info/repo/full.xml.gz to version 11859 (4 new / 0 removed modules)

**Comment by rovo89** [comment]
That sounds more like an issue with the installer than with the framework itself.
Anyway, from the title and the little part of the log, I have no idea what your issue is. Could you please explain more, and maybe add a screenshot?

**Comment by rhysh43** [comment]
I can't activate or see downloaded modules and when I install new modules they don't show up

**Comment by rhysh43** [comment]
![screenshot_20170331-191021](https://cloud.githubusercontent.com/assets/26696658/24563442/3606c22a-1646-11e7-87db-e9844afb2021.png)

**Comment by rhysh43** [comment]
![screenshot_20170331-191032](https://cloud.githubusercontent.com/assets/26696658/24563461/41f898d8-1646-11e7-96c2-36bb9117c7a3.png)

**Comment by Jiikuy** [comment]
Seems like a bug with the installer, try updating it.
