### ISSUE TITLE
Pokemon Go doesn't work with active Xposed

### ISSUE THREAD

**Issue by szamuka** [rovo89/Xposed#228]
Pokemon Go doesn't work with active Xposed. How to fix it? 

xposed-v87-sdk23-Magisk-MIUI-edition-by-SolarWarez-20161127 
Magisk 
Xiaomi Redmi Note 3 
Android 6.0.1

**Comment by rovo89** [comment]
Some apps - including Pokemon Go - are actively refusing to work with Xposed, root or even just a custom ROM. This isn't a bug in Xposed, it's their decision, and I don't see it as task for the Xposed framework to try and hide itself from such apps. There might be third-party modules or apps which try to do that, but I can't offer support for that.
