### ISSUE TITLE
Xposed not running after update. Help me

### ISSUE THREAD

**Issue by wak66** [rovo89/Xposed#232]
Xposed and all modules not running after auto update. Framework installed but not running.
Log error file:

07-25 23:21:17.703 I/Xposed  ( 1357): -----------------
07-25 23:21:17.703 I/Xposed  ( 1357): Starting Xposed version 80.1 (by dkcldark / non-requestConcurrentGC-type / 20160218), compiled for SDK 21
07-25 23:21:17.703 I/Xposed  ( 1357): Device: SM-G900F (samsung), Android version 5.0 (SDK 21)
07-25 23:21:17.703 I/Xposed  ( 1357): ROM: LRX21T.G900FXXU1BOJ1
07-25 23:21:17.703 I/Xposed  ( 1357): Build fingerprint: samsung/kltexx/klte:5.0/LRX21T/G900FXXU1BOJ1:user/release-keys
07-25 23:21:17.703 I/Xposed  ( 1357): Platform: armeabi-v7a, 32-bit binary, system server: yes
07-25 23:21:17.703 I/Xposed  ( 1357): SELinux enabled: yes, enforcing: yes
07-25 23:21:17.853 E/Xposed  ( 1375): Error -2147483646 while adding app service user.xposed.app
07-25 23:21:22.703 E/Xposed  ( 1357): Zygote service is not running, Xposed cannot work without it
07-25 23:23:23.945 I/XposedInstaller( 6480): Downloaded http://dl.xposed.info/repo/full.xml.gz with status 0 (error: null), size 1266557 bytes
07-25 23:23:27.975 I/XposedInstaller( 6480): Updated repository http://dl.xposed.info/repo/full.xml.gz to version 12424 (1102 new / 0 removed modules)

**Comment by wak66** [comment]
Im using samsung galaxu s5 rooted. Lollipo 5.0

**Comment by wak66** [comment]
SM-G900F

**Comment by Massi-X** [comment]
You have to write to dkcldark, because you using a custom Xposed version
