### ISSUE TITLE
Xposed in qiku f4（360-1501_A02）problem appear

### ISSUE THREAD

**Issue by funnypro** [rovo89/Xposed#233]
When the qiku f4 (360-1501_A02) installed Xposed and hard reboot, there will be a fingerprint module failure

**Comment by rovo89** [comment]
Please post a log: https://github.com/rovo89/XposedBridge/wiki/Bugs

**Comment by funnypro** [comment]
@rovo89 It may take some time to collect the log

**Comment by rovo89** [comment]
Closed due to lack of feedback, please reopen once you have the log.
