### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by Jedarc** [rovo89/Xposed#235]
## **Take my money and give me a version for Android N. :moneybag:**

Yes! Many people are willing to donate to help you with this project.

**I know money doesn't buy everything, I just wanted to be funny.**

I am a developer, and I would like to contribute to researching and programming.
But I think I'm not at the level you need.

But if there are ways to be able to help you, even financially, show us the way, please.
Thank you so much for everything you've already done!

I love you, even without knowing you! Oh really.
You have no idea how much you've helped me.

@rovo89

**Comment by harrysummer** [comment]
There is a donation link in rovo89's xda post, which links to here: http://repo.xposed.info/donate

Let's together keep the issue list unpolluted and just go ahead donating :)
