### ISSUE TITLE
Cannot hook with DownloadManager.class

### ISSUE THREAD

**Issue by athulantonynp** [rovo89/Xposed#237]
I tried to hook a method "request(Uri);" in DownloadManager class of android.app package. But it is not calling the method logic implemented by me.  I am posting my code here. Please do a look on this. Other modules are working well

` Class<?>download=XposedHelpers.findClass("android.app.DownloadManager",loadPackageParam.classLoader);

XposedHelpers.findAndHookMethod(download, "request", Uri.class, new XC_MethodHook() {
                @Override
                protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
                    Uri request=(Uri)param.args[0];
                    Log.e("WTKLV",new Gson().toJson(request).toString());
                }
            });`

**Comment by rovo89** [comment]
As no further info was given, assuming this was a typo or something.
