### ISSUE TITLE
Cannot hook with Intent class. 

### ISSUE THREAD

**Issue by athulantonynp** [rovo89/Xposed#240]
I tried to hook some methods in Intent.java class in android.content package. For checking purpose i made a loop for getting names in the class. But it is not working. I am pasting my code below. Since I am a beginner I had followed your documentation. So I couldn't find anything related to this issue. 

```java
if(loadPackageParam.packageName.equals("android")&&loadPackageParam.processName.equals("android"))
{
            Class<?> packageParserClass = XposedHelpers.findClass(
                    "android.content.pm.PackageParser", loadPackageParam.classLoader);
           try{
               //This code is not getting executed.
               Class<?> intentClass = XposedHelpers.findClass(
                       "android.content.Intent", loadPackageParam.classLoader);
               for(Method method:intentClass.getMethods()){
                   Log.e("WTKLV",method.getName());
               }
           }catch (Exception e){
               Log.e("WTKLV",e.getLocalizedMessage());
           }
```

**Comment by rovo89** [comment]
Is there anything in the logs? Please try adding another log line before all of this code, to ensure that your `handleLoadPackage()` function is actually called.

**Comment by Massi-X** [comment]
processName? Are you sure you want this?

**Comment by rovo89** [comment]
Closed due to lack of feedback.
