### ISSUE TITLE
Bootloop after install on Lg l3 ii (E435) running Android 6.0.1 / LineageOS-13.0

### ISSUE THREAD

**Issue by wokawoka** [rovo89/Xposed#241]
[logcat_.txt](https://github.com/rovo89/Xposed/files/1289794/logcat_.txt)

I'm attaching a logcat file (sorry if it's too big).

After more than 45 minutes the logcat was still showing activity, but it looked like the phone was repeating the same things over again. 
Frankly I don't know how much abut the meaning of all those dex2oat verification and compilation messages, other than guessing that they are liked with the ART Runtime therefore I'm pretty lost.

The right Xposed version for the platform was installed via the xposed installer.

I can imagine that providing help to everybody is impossible for you, but I just hope that you may find the time to send me a suggestion, I would be really grateful!

Thank you for your great work!

EDIT: I did try to boot the phone again and after waiting more than one hour the phone booted to the OS and xposed was correctly installed.
I believe that flashing xposed did trigger a cache wipe and the phone took a really long time to rebuilt it.
Sorry for opening the issue without a real need.

**Comment by rovo89** [comment]
No problem, glad you replied back once the issue was solved. The log clearly shows that many, many methods took > 100ms to compile. That's usually only the case for a few methods, so I assume that either your device is very slow, or it ran at slow CPU speed at that time.
