### ISSUE TITLE
XPosed and notorious Lineage compatibility.

### ISSUE THREAD

**Issue by Avamander** [rovo89/Xposed#243]
Small question really, do you (maintainer) or anyone reading this know what commits break the easy installation support in LineageOS (CyanogenMod) 11? 

XPosed installer just outputs an error that `CANNOT LINK EXECUTABLE: cannot locate symbol "_ZN7android14AndroidRuntime5startEPKcS2_" referenced by "/data/data/de.robv.android.xposed.installer/cache/app_process"...`, last I remember it allowed to be installed like that on CyanogenMod11.

(Demangled it says that it can't find "android::AndroidRuntime::start(char const*, char const*)" if someone's googling this.)

**Comment by rovo89** [comment]
That's the one: https://github.com/LineageOS/android_frameworks_base/commit/d8130142f875f2d9b4853765ed50bee9cc0f7046
