### ISSUE TITLE
Unable to activate modules

### ISSUE THREAD

**Issue by Jedarc** [rovo89/Xposed#245]
Am I doing something wrong?

![screenshot_20171009-114346](https://user-images.githubusercontent.com/10923617/31344078-0666ed5e-ace8-11e7-8dc7-92536c281be6.png)

![screenshot_20171009-112716](https://user-images.githubusercontent.com/10923617/31344118-1c2edb60-ace8-11e7-92b4-4f4ecf03d7d9.png)

![screenshot_20171009-113042](https://user-images.githubusercontent.com/10923617/31344133-236b5e08-ace8-11e7-9ba1-ddd345977205.png)

![screenshot_20171009-113148](https://user-images.githubusercontent.com/10923617/31344138-281cb05a-ace8-11e7-808d-9f9c7ce1109b.png)

> Cannot write /data/user_de/0/de.robv.android.xposed.installer/conf/modules.listjava.io.FileNotFoundException: /data/user_de/0/de.robv.android.xposed.installer/conf/modules.list (No such file or directory)

**Comment by rovo89** [comment]
How much of the path displayed in the last screenshot does actually exist? For example does /data/user_de exist? Please check also for the subdirectories and let me know which the first missing one is.

**Comment by Jedarc** [comment]
First of all thank you for the tool, thank you so much for the attention so fast.
I can only get to this directory:
`/data/user_de/0/`


![image](https://user-images.githubusercontent.com/10923617/31350457-a93f7194-acfd-11e7-8433-a239cac69257.png)

**Comment by rovo89** [comment]
Strange, it should be created during installation of the app (by the system, not by the app itself!). Do you have any other app directories inside `/data/user_de/0`? Can you retry as root, just to be sure?

**Comment by Jedarc** [comment]
There are several application directories, here are a few examples.

![image](https://user-images.githubusercontent.com/10923617/31353532-4e06fe76-ad09-11e7-9ad8-fd09fc3e35c8.png)

I found it interesting that I found another path with application directories as well.

![image](https://user-images.githubusercontent.com/10923617/31353653-b2911e8a-ad09-11e7-9c7f-d726536166c5.png)

**Comment by rovo89** [comment]
Yes, `user_de` is for device-encrypted files, i.e. files available before the user has logged in. the `user` folder is encrypted per user. What I'm wondering about is: Why did the Xposed Installer directory not get created? And are those two directories maybe linked on your device, or is it by chance that both contain exactly the same subfolders?

**Comment by Jedarc** [comment]
I found the path:

![image](https://user-images.githubusercontent.com/10923617/31353894-b2bdc402-ad0a-11e7-98cf-7bf3cfeeb185.png)

I don't understand how he might have stopped here.
Is there a way I can configure this?

**Comment by rovo89** [comment]
That's a different path, it must be in /data/user_de/0.

**Comment by Thunder07** [comment]
I've also noticed something that might be related to this. I've had Xposed v88 sdk25 running for about 24hours, during which I was working on debugging a module, but even now I don't have a logs folder, I've been debugging purely through logcat.

**Comment by Jedarc** [comment]
I was able to get the application to create the path!
I uninstalled it on my phone and reinstall via adb.

![image](https://user-images.githubusercontent.com/10923617/31354839-52beac34-ad0e-11e7-9f09-2c9322e7c327.png)

![image](https://user-images.githubusercontent.com/10923617/31354869-6b89438c-ad0e-11e7-8d15-7b1b1fe81507.png)

**Comment by Jedarc** [comment]
Would not it be nice to have root access before creating the directories?
When I did the installation I do not remember him asking me for access.

**Comment by rovo89** [comment]
There should be no need to create this directory with root permissions, it should simply exist already! I could put up simple test app, just to check whether this directory gets created, but it seems like the reinstallation fixes it as it should.

Could you give me more info about the past? Did you already have Xposed Installer installed and then upgraded? Or installed newly? If you already had it, when did you install it? Did you upgrade Android since then? I could imagine that maybe this directory doesn't exist if you install the app on Marshmallow and then upgrade to Nougat.

**Comment by Jedarc** [comment]
I used Exposed normally in Marshmallow. Until I decided to migrate to a [custom Nougat ROM](https://download.lineageos.org/).
I tried installing Xposed, but I saw that there was no support yet.
I tried to use [this unofficial version](https://forum.xda-developers.com/xposed/material-design-xposed-installer-t3137758), but I did not succeed.
I gave up using it, and removed it from my device.
Since then I've actually made some updates to the system.
Today I saw [this wonderful news](https://github.com/rovo89/Xposed/issues/225#issuecomment-335025955) of official support for Nougat.
First I downloaded [the .zip file](http://dl-xda.xposed.info/framework/sdk25/arm/) and installed it through [my custom recovery](https://twrp.me/).

After that, I downloaded and installed xposed v3.1.1, but it did not work. Then I saw my error and I downloaded and installed version v3.1.2 of the [uptodown site](https://xposed-installer.br.uptodown.com/android).

I did not succeed once again. So I uninstalled the framework retaining the application. Then I installed the framework again via application.

I did not succeed, so I made the process through recovery.

Since I was already going crazy, I decided to open this issue.

**Comment by rovo89** [comment]
OK, thanks! So basically, you had uninstalled the app completely before today. So in your case, installing 3.1.1 on Nougat and then upgrading to 3.1.2 caused this situation?

**Comment by Jedarc** [comment]
When I migrated from 3.1.1 on Marshmallow to 3.1.2 on the Nougat I cleaned my cell phone completely. There is no way trash to be left behind.
I'm not sure how this problem could have happened, but today I mistakenly installed 3.1.1 on Nougat, uninstalled and correctly installed 3.1.2, but it did not work unless via adb.

**Comment by DMSalesman** [comment]
The version of my Xposed app is 3.1.1. I just Installed it, and then downloaded and installed the framework via the app itself.

No issues while enabling modules, but my phone rebooted by its own shortly after installing the framework.

**Comment by Jedarc** [comment]
Look how interesting!
I formatted again my cell phone completely. There are no trash left behind.
I tried to install Exposed and it did not create the folders again, so I uninstalled it and installed via terminal with the `pm install` command.

**Comment by rovo89** [comment]
Interesting. So if you uninstall and then reinstall normally (not via adb), those folders are missing? That would be a good and simple way to reproduce, which is the first step for finding the reason and then a fix.

**Comment by DMSalesman** [comment]
@rovo89 Any clues as to why this bug has not manifested for me?

**Comment by Jedarc** [comment]
@rovo89  that's it!
Uninstalling and normal installation is not creating the folders on my phone.
Only the installation via `adb `or `pm `command in the terminal.

**Comment by rovo89** [comment]
@DMSalesman No... it actually seems to work for most people, but enough people have issues with that.
@Jedarc Thanks, I'll try the exact same thing on my device. If everything works fine for me, I'd try to build a debug version or mini app or something like that and send it to you for testing.

**Comment by rovo89** [comment]
I uninstalled Xposed Installer, made sure that the directory is gone and then reinstalled with the official APK. The directory gets created on my device and everything is fine. So this is definitely ROM-specific.

**Comment by rovo89** [comment]
This is so strange. I installed LineageOS 14.1 on my Nexus 5, even a similar nightly (20170831), but I can't reproduce this. I tried both unencrypted and encrypted device. Any idea where the difference might be? Any special steps you have done, @Jedarc? By the way, I used the builtin file explorer for installation.

**Comment by guidot** [comment]
I think I stumpled on this in different way.

I upgraded my Galaxy Note Pro 12.2 to Lineage OS 14.1. 

- I did a full wipe
- Installed the ROM without any GAPPs, rebooted and checked if it's working at all
- Installed Framework 88.1 and Titanium Backup via TWRP
- I restored the Xposed Installer 3.1.2 and some Xposed-Modules via Titanium from a backup of the former Lineage OS 13.0
- After rebooting all modules state they are not activated.
- The log says: `Cannot load any modules because /data/user_de/0/de.robv.android.xposed.installer/conf/modules.list was not found`

In my case the actual path exists but does not contain modules.list or any other file.

**Comment by guidot** [comment]
Hm, I reeinstalled one of the modules via Xposed Installer, rebooted and found all modules working after that. BTW Lineage OS version is 20171012.

**Comment by robertosartori** [comment]
I've seen some people on the XDA thread solving the 'module.list not found problem' soft-rebooting.
I don't know if that file didn't exist because of the missing folder problem of this topic, but i think it could be related.

**Comment by rovo89** [comment]
@Jedarc Do you have multiple users enabled on your device? You would see other directories than 0 on /data/user_de in this case.

**Comment by Jedarc** [comment]
There are no other directories, but the Guest profile is enabled, although I have never used it.

**Comment by TimoJohannes** [comment]
hej, I seem to have the same problem, the folder isn´t there where it should be, I tried all named installation methods.
I´m running Paranoid Android Version 7.3.0, that is Android 7.1.2, on an Oneplus X (Onyx).

**Comment by dariusz-goc** [comment]
I have a similar problem. Because of the File Based Encryption the installer says the framework in not installed and I can't enable any module. The old installer says the framework is installed just fine, but switching modules doesn't actually turn them on. It happens no matter if I install it on the system or systemlessly in magisk. I'm using Resurrection Remix 5.8.5 (Android 7.1).

**Comment by aaronpries** [comment]
I had the same issue: modules.list (or parts of the directory) did not exist. Uninstalling XposedInstaller and installing again fixed it. I'm using a Oneplus 3T OxygenOS 4.5.1 / Android 7.1.1

**Comment by mh-g** [comment]
The same problem for me. Samsung S5 Duos (SM-G900FD) with LineageOS 14.1-20171018-NIGHTLY-klteduos. The phone was freshly set up, just the image from the LineageOS servers, open_gapps-arm-7.1-nano-20171021.zip, xposed-v88.1-sdk25-arm.zip, addonsu-14.1-arm-signed.zip. I have an microSD card added as additional memory.

I tried various things, but there was no directory under /data/user_de/0/ for xposed (many other directories, though). Uninstalling and installing via adb worked. Thanks Jedarc!

**Comment by Donmapio** [comment]
Hi, I had exactly the same problem and solved it by installing the Xposed Installer on my **internal storage** (before that it was installed on the external SD). 
This resulted in the generation of the missing directory.
Now everything works!

**Comment by rovo89** [comment]
@Donmapio How did you move the app? And how did you install it in the first place, do you have any special app or setting that allows you to do that?

**Comment by Donmapio** [comment]
I installed it by simply clicking the apk, which I downloaded from the official xda thread.
I use LineageOS 14 and during installation formatted my SD-card in order to be integrated into the system. This means that when I install apps they are sometimes automatically installed onto the SD-card. This happens without notification.
However I am able to manually move the apps into the internal storage via settings/apps, then choosing the app and clicking onto storage. There you can choose "change storage location"
I hope I could help

**Comment by rovo89** [comment]
Thanks! I tried to reproduce this with Lineage OS 14.1 on my Nexus 5 and an OTG USB stick. I activated it with `adb shell sm set-force-adoptable true` and formatted it as internal storage. I still found no way to move it to external storage from the UI though. Not even when I executed `adb shell pm set-install-location 2`. So I'm wondering how this could happen unnoticed. Note that I haven't declared a prefered [install location](https://developer.android.com/guide/topics/data/install-location.html), which is equivalent to `internalOnly`. Even when I set it to `auto` or `preferExternal`, it defaults to installing on internal storage, but allows me to move the app. I also get this option when enabling "Force allow apps on external" in the debug options, but it didn't change the default location for me.

The only way I found was `adb shell pm move-package de.robv.android.xposed.installer <uuid>`. With that, `/data/user_de/0/de.robv.android.xposed.installer` is indeed gone.

So what I can do is check that the data path provided by the system is actually  `/data/user_de/0/de.robv.android.xposed.installer`, and show a warning if not.

**Comment by rovo89** [comment]
Here's a test APK: https://www.dropbox.com/s/7tjtlanm7hmdar5/XposedInstaller_3.1.3-test1-release.apk?dl=0
It will detected if the directory is missing or differs from the fixed location. Can some of those who experienced this issue please test it? It also logs the actual data directory, maybe that helps to get more info.

**Comment by AndoidGameTips** [comment]
I also had this error, and I set the root acces to Allowed (before it was set on Always ask)

**Comment by AndoidGameTips** [comment]
Oh, and you need to have the app on internal storage, not on a sd-card

**Comment by rovo89** [comment]
Please check again with Xposed Installer 3.1.3, it will catch some typical situations of missing/wrong directories.

**Comment by phplbw** [comment]
### How to solve?
``` bash
12-23 19:23:19.940 I/Xposed  (  474): -----------------
12-23 19:23:19.940 I/Xposed  (  474): Starting Xposed version 81 (Nubia edition by SolarWarez / 20160409), compiled for SDK 22
12-23 19:23:19.940 I/Xposed  (  474): Device: NX518J (nubia), Android version 5.1.1 (SDK 22)
12-23 19:23:19.940 I/Xposed  (  474): ROM: NX518J_CNCommon_V1.20
12-23 19:23:19.940 I/Xposed  (  474): Build fingerprint: nubia/NX518J/NX518J:5.1.1/LMY47V/eng.nubia.20151201.162539:user/release-keys
12-23 19:23:19.940 I/Xposed  (  474): Platform: arm64-v8a, 64-bit binary, system server: yes
12-23 19:23:19.940 I/Xposed  (  474): SELinux enabled: yes, enforcing: yes
12-23 19:23:19.950 I/Xposed  (  474): -----------------
12-23 19:23:19.950 I/Xposed  (  474): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
12-23 19:23:20.550 I/Xposed  (  474): Detected ART runtime
12-23 19:23:20.570 I/Xposed  (  474): Nubia device detected... Make some patch...
12-23 19:23:20.570 I/Xposed  (  474): All done!
12-23 19:23:20.580 I/Xposed  (  474): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
12-23 19:23:20.740 W/Xposed  (  474): Found /data/data/de.robv.android.xposed.installer/conf/disable_resources, not hooking resources
12-23 19:23:20.740 E/Xposed  (  474): Cannot load any modules because /data/data/de.robv.android.xposed.installer/conf/modules.list was not found
12-23 19:23:29.370 I/Xposed  (  475): -----------------
12-23 19:23:29.370 I/Xposed  (  475): Starting Xposed version 81 (Nubia edition by SolarWarez / 20160409), compiled for SDK 22
12-23 19:23:29.370 I/Xposed  (  475): Device: NX518J (nubia), Android version 5.1.1 (SDK 22)
12-23 19:23:29.370 I/Xposed  (  475): ROM: NX518J_CNCommon_V1.20
12-23 19:23:29.370 I/Xposed  (  475): Build fingerprint: nubia/NX518J/NX518J:5.1.1/LMY47V/eng.nubia.20151201.162539:user/release-keys
12-23 19:23:29.370 I/Xposed  (  475): Platform: arm64-v8a, 32-bit binary, system server: no
12-23 19:23:29.370 I/Xposed  (  475): SELinux enabled: yes, enforcing: yes
12-23 19:23:29.370 I/Xposed  (  475): -----------------
12-23 19:23:29.370 I/Xposed  (  475): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
12-23 19:23:29.630 I/Xposed  (  475): Detected ART runtime
12-23 19:23:29.640 I/Xposed  (  475): Nubia device detected... Make some patch...
12-23 19:23:29.640 I/Xposed  (  475): All done!
12-23 19:23:29.650 I/Xposed  (  475): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
12-23 19:23:29.790 W/Xposed  (  475): Found /data/data/de.robv.android.xposed.installer/conf/disable_resources, not hooking resources
12-23 19:23:29.790 E/Xposed  (  475): Cannot load any modules because /data/data/de.robv.android.xposed.installer/conf/modules.list was not found
```

**Comment by rovo89** [comment]
@phplbw You're running a totally outdated, unofficial version of Xposed. I can't help you with that.

**Comment by zhlila** [comment]
same problem for My Android 7.1.1 device. i use XposedInstaller_3.1.5.apk & xposed-v89-sdk25-arm64.zip.
![default](https://user-images.githubusercontent.com/6738727/44774558-fa2ce580-aba5-11e8-805b-32a4ffa49695.png)
and
![default](https://user-images.githubusercontent.com/6738727/44774599-1892e100-aba6-11e8-933a-e6f23ec9cf4a.png)
and
![default](https://user-images.githubusercontent.com/6738727/44774648-36604600-aba6-11e8-984e-8ac227c02a6d.png)

it' wired, if i manually create the "conf" directory with right permission & owner,  and recheck the modules, it will work:
![default](https://user-images.githubusercontent.com/6738727/44774839-ba1a3280-aba6-11e8-85a6-ba1c262c79bb.png)

but when i reboot, the "conf" directory will disappear again!
and uninstall & reinstall XposedInstaller can't solve the problem.

**Comment by zhlila** [comment]
![default](https://user-images.githubusercontent.com/6738727/44777089-43803380-abac-11e8-8cf5-bf123b15c249.png)
when i reboot,    before i enter the XposedInstaller app, the "conf" is still here. but when i enter it, the "conf" is gone.
