### ISSUE TITLE
ART crashes on SDK 25 (Tried to mark ... not contained by any spaces)

### ISSUE THREAD

**Issue by exodius48** [rovo89/Xposed#247]
Here for the log:
https://pastebin.com/VriNKt41
Info https://forum.xda-developers.com/showpost.php?p=74101895&postcount=2334
I know this bug from this guy https://forum.xda-developers.com/showpost.php?p=74101931&postcount=2335

**Comment by rovo89** [comment]
Thanks for posting this on GitHub, makes it easier to follow up. ;)
I'll have to look into it, corrupted spaces are unfortunately hard to debug.

**Comment by Unpublished** [comment]
FYI these crashes can be worked around temporarily by manually running dex2oat but after some time jit compilation kicks in again (i guess) and forces art crashes again

**Comment by rovo89** [comment]
This should be fixed in v89.
