### ISSUE TITLE
services.odex too short

### ISSUE THREAD

**Issue by lahceneamine** [rovo89/Xposed#253]
Hi Rovo, 
I know you may be busy filtering the good and bad reports, so I'm gonna go straight to the point :
- Error : Failed to open oat /system/framework/oat/arm64/services.odex 
- The file "services.odex" is 0 bit long
[xposed_error_20171012_141648.log](https://github.com/rovo89/Xposed/files/1379477/xposed_error_20171012_141648.log)

Logs attached.
PS: Xposed works flawlessly, even if this error exist.

**Comment by rovo89** [comment]
That seems to be one of the issues mentioned here: https://github.com/rovo89/XposedBridge/issues/192#issuecomment-335055537
Did you also deodex this file? Please try to delete it, a 0 byte odex file is worthless anyway.

**Comment by lahceneamine** [comment]
I'm gonna ask the rom dev if it's deodexed.
Deleting the file resolves the error.

PS: I found something else with the installer, when I use your official v3.1.2, some modules do not detect their own activation status, but using some older installer (v3.0.1), they do.
I guess the path of enabled module list has changed ? Is there a way to add some kind of compatibility for those modules which are never gonna be updated (like unicon) ? Thank you.

**Comment by wanam** [comment]
Yes, it changed from "/data/data/apid" to "/data/user_de/apid", this change is required for fbe support on Nougat.

**Comment by rovo89** [comment]
> I guess the path of enabled module list has changed ?

Yes.

> Is there a way to add some kind of compatibility for those modules which are never gonna be updated (like unicon) ?

No. Modules shouldn't look at Xposed Installer's files to find out their activation status. One of the reasons is that they rely on internals which aren't part of the API and can change anytime. This point is proven now by the new requirements in Nougat. If they want to know whether their module has been loaded, they can use hook their own app, just like Xposed does to provide feedback to the installer.

**Comment by lahceneamine** [comment]
Thank you for your answers.
Gonna try to contact UNICON's dev, but I know it's a dead end.
And by the way, as @Pkhrl said, I also think it's related to the same magisk module "Smali Patcher".
Should I close this issue ?

**Comment by rovo89** [comment]
Is the empty services.odex file part of the generated Magisk module? Because I just read in @topjohnwu's documentation that creating a dummy file is often easier than deleting a file.

**Comment by lahceneamine** [comment]
Yes it is

**Comment by rovo89** [comment]
OK, then the case is clear. I'll simply ignore empty .odex files now, please test: https://www.dropbox.com/s/37c09h9efw7ivzd/xposed-v88.2-sdk24-arm64-test1.zip?dl=0

**Comment by lahceneamine** [comment]
I've just seen that my comment didn't pass.
Sorry I really answered you 10 minutes after you posted the zip.
Yes it fixes the error.
Thank You :)

**Comment by Pkhrl** [comment]
Thanks guys. Cheers!
