### ISSUE TITLE
Xposed is active, but modules can't see it.

### ISSUE THREAD

**Issue by rollerce** [rovo89/Xposed#254]
So, I got really excited when I saw an official xposed for Nougat has been released. Until then is been using the slapdash version that worked (ish) by purifyos.

I immediately did a full factory wipe, including internal storage, installed stock boot, stock recovery, and relocked my bootloader. In essence, I returned my phone to the state it was in when I unboxed it.

I followed up by unlocking the bootloader, installing TWRP, patching force encrypt and dm-verity. Installed root, busybox, and xposed in that order. Continued setup as normal, installing the xposed installer app once everything was done.

The xposed installer app says xposed is installed and working, but none of the modules I've tried this far have been able to tell that xposed is installed and that they're activated.

**Comment by rollerce** [comment]
![screenshot_20171011-224656](https://user-images.githubusercontent.com/5863869/31513449-426609e0-af43-11e7-9070-beee76b6f022.jpg)
![screenshot_20171011-224747](https://user-images.githubusercontent.com/5863869/31513452-4283bd50-af43-11e7-87fc-f6c03dcd8325.jpg)
![screenshot_20171012-114808](https://user-images.githubusercontent.com/5863869/31513454-429e8f0e-af43-11e7-95d6-c7fb1e5a7ff0.jpg)

**Comment by rovo89** [comment]
That's not the official installer. Please try the official one, version 3.1.2, it contains important changes for Nougat. And I just tested, MinMinGuard recognizes Xposed.

**Comment by fjsferreira** [comment]
When I use older modules like minminguard, I always get this error on xposed log: "zygote service is not accessible from PID (number) with UID (number)". Over and over again, more than once per second. Why is that? Can I safely ignore it? Modules work as normal is just that this error is filling the log a lot.

I'm on stock oos on the oneplus 5.

**Comment by rollerce** [comment]
@rovo89

I....am an idiot. Thanks for being kind.
