### ISSUE TITLE
NoSuchMethodError [Question]

### ISSUE THREAD

**Issue by SebastianZimmeck** [rovo89/Xposed#257]
When trying to hook [getNetworkOperatorName](https://developer.android.com/reference/android/telephony/TelephonyManager.html#getNetworkOperatorName()) I am getting the following error:

> I/Xposed: java.lang.NoSuchMethodError: android.telephony.TelephonyManager#getNetworkOperatorName(java.lang.String)#exact

However, I know that the method is called in the app I am observing (confirmed this via [Xprivacy](https://github.com/M66B/XPrivacy)). Below is the code I am using. What could be the issue?

>        findAndHookMethod("android.telephony.TelephonyManager", lpparam.classLoader,
>               "getNetworkOperatorName", String.class, new XC_MethodHook() {
>                            @Override
>                            protected void afterHookedMethod(MethodHookParam param) throws Throwable {
>                                XposedBridge.log("getNetworkOperatorName");
>                            }
>        });

**Comment by rovo89** [comment]
There doesn't seem to be a `getNetworkOperatorName(String xyz)` method, just `getNetworkOperatorName()`: https://developer.android.com/reference/android/telephony/TelephonyManager.html#getNetworkOperatorName()

Maybe you mixed up parameter and return type?

**Comment by SebastianZimmeck** [comment]
Thanks, @rovo89. I appreciate the help. I removed `String.class` from the code above and it works now.
