### ISSUE TITLE
Xposed show is installed but not activated after reboot

### ISSUE THREAD

**Issue by shingz96** [rovo89/Xposed#260]
Xposed was installed successfully with the installer zip file, but after a reboot quite easy to get into error of "Xposed is installed but not active".

this happened usually after a reboot (normally to activate/update when a new module installed).

A quick workaround to this problem is to click on a checkbox of a module twice (deactivate & activate) and reboot, then the problem was fixed.

Xposed Version: 88.0 & 88.1
Root Used: Magisk 14.0
Phone: OnePlus 3 with Android 7.1.2

**Comment by Primokorn** [comment]
It seems it happens after un soft reboot. I fixed it with a "full" reboot.
Here is a log.
[xposed_error_20171018_134921.log](https://github.com/rovo89/Xposed/files/1394504/xposed_error_20171018_134921.log)

**Comment by rovo89** [comment]
Please try with v88.2 and Xposed Installer 3.1.3.

**Comment by kirkhan93** [comment]
@rovo89  , tried with latest installer 3.1.4 and 88.2 framework , still inactive issue for xposed exist .

**Comment by Primokorn** [comment]
@kirkhan93 it's fixed on my end. OnePlus 3T - Android 7.1.2 - RR custom ROM
Soft reboots no longer disable Xposed.

**Comment by gianmaxfactor** [comment]
Same here with latest installer 3.1.4 and 88.2 framework (through Magisk), have inactive issue for xposed after any kind of reload/power cycle. Any fix ?Thanks

**Comment by Primokorn** [comment]
@gianmaxfactor Any log? rovo89 won't do anything if we don't provide logs.
*Logs or it didn't happen*

**Comment by andres333** [comment]
Same here: Huawei p10+, B201 fRomFuture, magisk.

Has any of you found the installer 3.1.3 as rovo recommended? I cannot seem to find it...

**Comment by walrus543** [comment]
@andres333 actually [3.1.4 is the latest version](https://forum.xda-developers.com/showthread.php?t=3034811)

**Comment by gianmaxfactor** [comment]
Please help me finding some logs to send  to rovo89 to troubleshoot tha above problem (installer 3.1.4 and 88.2 framework (through Magisk, Systemless by topjohnwu), have inactive issue for xposed after any kind of reload/power cycle).

**Comment by walrus543** [comment]
@gianmaxfactor Share the logs available from Xposed Installer app.

**Comment by gianmaxfactor** [comment]
@Primokorn Thank you dear, I supposed it, but my Logs window always says "Log  is empty"...

**Comment by walrus543** [comment]
@gianmaxfactor Xposed Installer has root access?
Xposed framework v89 is available by the way.

**Comment by gianmaxfactor** [comment]
@Primokorn I would assure you that I think that all has been made correctly. Xposed works at the moment, with root access granted. It is Magisk module, so root access is given there. But If I reload the phone then Xposed is "installed but bit active" and  Log window is empty. I discover that Xposed is not active because I have the Gravity app, and after the phone reload, the pin-scramble feature is not active (because Gravity doesn't found the Xposed framework, because it is inactive)

**Comment by walrus543** [comment]
@gianmaxfactor I you are using a systemless version of Xposed framework then report to the proper maintainer. Rovo89 doesn't deal with systemless stuff AFAIK.
