### ISSUE TITLE
Nexus 5X(bullhead) 7.1.2 xposed 88.1 bootloop issue

### ISSUE THREAD

**Issue by JustAkan** [rovo89/Xposed#263]
Hello I am a nexus 5x developer.
I think it's a great honor to have a version of xposed 88.1.
But there is a problem. If you install xposed 88.1 from magisk 14.0
I am currently using Genuine 7.1.2 on the Nexus 5x (bullhead). It does not boot at all.
Unofficial xposed is booted back to 87.3.
UnLuckily, adb also does not work and it stops at the google logo.
Please fix it as soon as possible. rovo89.
P.S My guess is that I supported some art patches for Samsung device fixes. I think it probably is not compatible with the Nexus device.

Xposed Version: 88.0 & 88.1
Root Used: Magisk 14.0
Phone: Nexus5X with Android 7.1.2

**Comment by rovo89** [comment]
Please try with the official version (not Magisk). If it still doesn't work, please try other ways to get a log: https://github.com/rovo89/XposedBridge/wiki/Bugs#how-can-i-get-logs

Without logs, I can't do anything.

**Comment by suirzes** [comment]
I have the same problem - while trying to install systemless xposed via flash/magisk, upon restart i get a bootloop. Installing normal v88.1 works well, no bootloops. Will try getting adb logs.... SM-N950F, 7.1.1, Magisk 14.3, twrp.

**Comment by JustAkan** [comment]
Unfortunately, not even the magisk version doesn't work.
Even after this version, even the adb doesn't work. Error.log is only present in the classpath
Now, I think the security patches are mixed.
Looks like nexus 5x is not compatible in art itself.
I'd like to ask you a quick action.

**Comment by C3C0** [comment]
Official Xposed Framework v88.1 works just fine on Nexus 5X running the latest stock.

**Comment by rovo89** [comment]
As confirmed by @C3C0, it should work fine with the Nexus 5X, and until you can show the logs, I'll have to close this issue.
