### ISSUE TITLE
NoSuchMethodError [Question]

### ISSUE THREAD

**Issue by SebastianZimmeck** [rovo89/Xposed#265]
I am trying to hook the [startScan](https://developer.android.com/reference/android/bluetooth/le/BluetoothLeScanner.html) method. There is probably something wrong with the parameters. I am using the `java.util.List.class` in another hook. So, that seems right. Maybe, the PendingIntent is the issue? 

@rovo89, any suggestion would be appreciated. 

>            findAndHookMethod("android.bluetooth.le.BluetoothLeScanner", lpparam.classLoader,
>                    "startScan", java.util.List.class, android.bluetooth.le.ScanSettings.class,
>                    android.app.PendingIntent.class, new XC_MethodHook() {
>                        @Override
>                        protected void afterHookedMethod(MethodHookParam param) throws Throwable {
>                        // more code
>                        }
>                    });

**Comment by rovo89** [comment]
Unless you got Xposed working on Oreo already, the method isn't available: "added in API level 26". Maybe try and hook one of the other variants of this method? Or if you want to hook all variants and don't care too much about the parameters: http://api.xposed.info/reference/de/robv/android/xposed/XposedBridge.html#hookAllMethods(java.lang.Class%3C?%3E,%20java.lang.String,%20de.robv.android.xposed.XC_MethodHook)

**Comment by SebastianZimmeck** [comment]
OK, great. Thanks for the reference. There is no difference in "finding" the method, right? I am asking as one API is called *find*AndHookMethod and the other just hookAllMethods.

**Comment by rovo89** [comment]
There is a difference. Please check the API docs, if anything is still unclear then, let me know.

**Comment by SebastianZimmeck** [comment]
I believe it is clear. My main question is whether `hookAllMethods` keeps track of whether a method was actually called (vs. simply finding the name of the method in the class). From [here](https://github.com/rovo89/XposedBridge/wiki/Helpers) I understand the former is the case. Please let me know if I am misunderstanding this.

> hookAllMethods / hookAllConstructors
> You can use these methods if you want to hook all methods with a specific name or all constructors in a class. This is useful if there are different variants, but you want to execute some code before/after any of them has been called.

**Comment by rovo89** [comment]
> My main question is whether hookAllMethods keeps track of whether a method was actually called (vs. simply finding the name of the method in the class).

I'm not sure what you mean with "keeps track". The difference is that `findAndHookMethod()` will hook exactly the method with the given name and parameter types. `hookAllMethods()` just needs a name, no parameter types, and will find and hook all methods with the given name (which could be 0, 1 or many).

**Comment by SebastianZimmeck** [comment]
By "keep track" I meant whether there is some taint flow analysis or other mechanism to detect whether the method is really called (as opposed to simply checking whether it exists; it might never be called). Your answer clarified that the former is the case. Thank you, @rovo89.
