### ISSUE TITLE
Find and hook a method independently from class [Question]

### ISSUE THREAD

**Issue by SebastianZimmeck** [rovo89/Xposed#269]
Is there a way I can detect a method regardless of the class it belongs to (e.g., the occurrence of a method "getBirthday" anywhere in an app)? It seems that [hookMethod](http://api.xposed.info/reference/de/robv/android/xposed/XposedBridge.html#) would also need to have a class specified and could not be used for such purpose, right?

**Comment by systemallica** [comment]
Not a great a idea because many classes could have a method with the same name. And then which one would you hook?

**Comment by SebastianZimmeck** [comment]
> Not a great a idea because many classes could have a method with the same name. And then which one would you hook?

I am interested in all of them. Given a sufficiently rare name, there might be only one.

Is it possible? If so, how?

**Comment by systemallica** [comment]
If there's only one, then you can easily find its class. I'm sorry but I don't understand the use case. I don't think it's possible.

**Comment by SebastianZimmeck** [comment]
OK, thanks, @systemallica.

**Comment by rovo89** [comment]
Thanks for answering this, @systemallica!

Indeed, this isn't possible. A method in Java is uniquely identified within a ClassLoader as a tuple of declaring class, method name and signature. With `findAndHookMethod()`, you give all three values and therefore find exactly the one method with this combination. `hookAllMethods()` allows you to leave out the signature. What you're asking for is also leaving out the declaring class. This would require something like this:
```
for (class in allClasses) {
  for (method in class.allMethods) {
    if (method.name == the_name) {
      hookMethod(method)
    }
  }
}
```

And there is no such thing as `allClasses`. At best, the system could enumerate the *currently loaded* classes, which wouldn't include classes loaded in the future. And even if there was a solution for this, it would still be a big loop.

Besides that, the use case would really be questionable. You might end up hooking a lot of methods (performance) or critical methods (crashes). If you're looking for some kind of app analysis, there might be better tools that single-step through the code like a debugger.
