### ISSUE TITLE
Samung-S6-Nougat Random Vibration when press back or power.

### ISSUE THREAD

**Issue by JPRO89-Cu** [rovo89/Xposed#274]
When Android System is Optimizing it self (creating de odex) and you press back or power the phone vibrates two times during the process, But the vibration stills for ever after the procces ends even working whit the phone. THERE ARE PEOPLE ON XDA WITH THIS ISSUE TOO.

**Comment by rovo89** [comment]
> THERE ARE PEOPLE ON XDA WITH THIS ISSUE TOO.

OMG!!! Please create more duplicate issues, then I'll look at it faster!
