### ISSUE TITLE
Unable to hook com.android.providers.settings.SettingsProvider in Nougat

### ISSUE THREAD

**Issue by DavisNT** [rovo89/Xposed#277]
On Android Nougat (LineageOS 14.1) with xposed-v88.1-sdk25-arm64.zip Xposed is not able to hook methods in `com.android.providers.settings.SettingsProvider`.

The following code (inside `handleLoadPackage()` of Xposed module):

    if(!"android".equals(lpparam.packageName))
        return;

    XposedHelpers.findAndHookMethod("com.android.providers.settings.SettingsProvider", lpparam.classLoader, "mutateGlobalSetting", String.class, String.class, int.class, int.class, boolean.class, new XC_MethodHook() {
        @Override
        protected void beforeHookedMethod(MethodHookParam param) throws Throwable {
            Log.i("TestApp", "DEBUG-2");
        }
        @Override
        protected void afterHookedMethod(MethodHookParam param) throws Throwable {
            Log.i("TestApp", "DEBUG-3");
        }
    });

Fails with `java.lang.ClassNotFoundException` (below is excerpt from Xposed log):

    10-29 21:23:26.444 I/Xposed  ( 5009): Loading modules from /data/app/lv.id.dm.testapp-2/base.apk
    10-29 21:23:26.898 I/Xposed  ( 5009):   Loading class lv.id.dm.testapp.XposedUtil
    10-29 21:23:28.271 E/Xposed  ( 5289): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.providers.settings.SettingsProvider
    10-29 21:23:28.271 E/Xposed  ( 5289): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:69)
    10-29 21:23:28.271 E/Xposed  ( 5289): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:258)
    10-29 21:23:28.271 E/Xposed  ( 5289): 	at lv.id.dm.testapp.XposedUtil.handleLoadPackage(XposedUtil.java:91)
    10-29 21:23:28.271 E/Xposed  ( 5289): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
    10-29 21:23:28.271 E/Xposed  ( 5289): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
    10-29 21:23:28.271 E/Xposed  ( 5289): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
    10-29 21:23:28.271 E/Xposed  ( 5289): 	at de.robv.android.xposed.XposedInit$4$1.beforeHookedMethod(XposedInit.java:165)
    10-29 21:23:28.271 E/Xposed  ( 5289): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:319)
    10-29 21:23:28.271 E/Xposed  ( 5289): 	at com.android.server.SystemServer.startBootstrapServices(<Xposed>)
    10-29 21:23:28.271 E/Xposed  ( 5289): 	at com.android.server.SystemServer.run(SystemServer.java:366)
    10-29 21:23:28.271 E/Xposed  ( 5289): 	at com.android.server.SystemServer.main(SystemServer.java:237)
    10-29 21:23:28.271 E/Xposed  ( 5289): 	at java.lang.reflect.Method.invoke(Native Method)
    10-29 21:23:28.271 E/Xposed  ( 5289): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
    10-29 21:23:28.271 E/Xposed  ( 5289): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
    10-29 21:23:28.271 E/Xposed  ( 5289): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:103)
    10-29 21:23:28.271 E/Xposed  ( 5289): Caused by: java.lang.ClassNotFoundException: com.android.providers.settings.SettingsProvider
    10-29 21:23:28.271 E/Xposed  ( 5289): 	at java.lang.Class.classForName(Native Method)
    10-29 21:23:28.271 E/Xposed  ( 5289): 	at java.lang.Class.forName(Class.java:400)
    10-29 21:23:28.271 E/Xposed  ( 5289): 	at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
    10-29 21:23:28.271 E/Xposed  ( 5289): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:67)
    10-29 21:23:28.271 E/Xposed  ( 5289): 	... 14 more
    10-29 21:23:28.271 E/Xposed  ( 5289): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.providers.settings.SettingsProvider" on path: DexPathList[[zip file "/system/framework/org.cyanogenmod.platform.jar", zip file "/system/framework/org.cyanogenmod.hardware.jar", zip file "/system/framework/services.jar", zip file "/system/framework/ethernet-service.jar", zip file "/system/framework/wifi-service.jar"],nativeLibraryDirectories=[/system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]
    10-29 21:23:28.271 E/Xposed  ( 5289): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
    10-29 21:23:28.271 E/Xposed  ( 5289): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
    10-29 21:23:28.271 E/Xposed  ( 5289): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    10-29 21:23:28.271 E/Xposed  ( 5289): 	... 18 more

**Comment by rovo89** [comment]
The error message is pretty clear, you're trying to hook a class that doesn't exist. If you did this successfully on older ROMs, you might have to research whether the class was moved. It's also possible that you're checking for the wrong process. Are you sure you want "android" (i.e. the system_server)? Maybe you can try leaving out that check and simply try to find this class in all apps. Then just log where the class could be found and you know which package you should really check for.

**Comment by DavisNT** [comment]
Sorry! This is really not a bug. As you said, the correct package is different (`com.android.providers.settings`) although it also has PID of system_server.
Fix was replacing `if(!"android".equals(lpparam.packageName))` with `if(!"com.android.providers.settings".equals(lpparam.packageName))`. 

As one of first Google results regarding this issue was issue #53 I thought this might be a bug in Xposed for Nougat. Sorry for the false heads up! 😊
