### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by sadsouler** [rovo89/Xposed#278]
Xposed framework is not working

**Comment by rovo89** [comment]
Please try if a fix helps.

No seriously, read and follow this page: https://github.com/rovo89/XposedBridge/wiki/Bugs

**Comment by sadsouler** [comment]
I'm using lineage os 7.1.2 it's showing that it is successful install but none of the application is working

**Comment by rovo89** [comment]
If Xposed shows as installed successfully, then probably your modules are not compatible with Nougat (yet). If you think otherwise, finally follow the instructions in the link.

**Comment by sadsouler** [comment]
Ok
