### ISSUE TITLE
OnePlus One reboots at 100% charge

### ISSUE THREAD

**Issue by aiolos01** [rovo89/Xposed#281]
> Fixed a crash on OnePlus devices when 100% charged (hopefully, didn't get much feedback)

I've had this issue for 2,5 years now. Didn't know it was related to xposed. All I've seen is the wifi driver crashing in kmsg (and I have wifi off).

[ 2420.750556] wcnss crash shutdown 0
[ 2420.750674] Rebooting in 5 seconds..
[ 2427.314798] SMP: failed to stop secondary CPUs
[ 2427.314913] Going down for restart now
[ 2427.315768] Calling SCM to disable SPMI PMIC arbiter

The xposed log doesn't show anything before the reboot. It starts after that.

**Comment by rovo89** [comment]
> I've had this issue for 2,5 years now. Didn't know it was related to xposed

I didn't claim that every single reboot issue was/is caused by Xposed. 😉 The one I'm talking about is only in Nougat. WiFi driver crashes are definitely not caused by Xposed, and the log clearly says that it's going to start due to this.
