### ISSUE TITLE
Magisk and xposed

### ISSUE THREAD

**Issue by Tomq2356** [rovo89/Xposed#283]
With Magisk installed, I can't get xposed (even with magisk installer and framwork installed) working with all modules. there are two particular ones not working: xprivacy and Greenify (even with magisk greenify installed). Other ones like lucky patcher and titaniiums are working fine. It's getting more complicated than ever before.

**Comment by rovo89** [comment]
Sorry, but I don't support unofficial versions of Xposed. Besides that, you say that some modules aren't working, but others work fine, so it sounds like an issue with those modules, not with the framework.
