### ISSUE TITLE
Theme app MIUI 9 crash when select theme from Tab

### ISSUE THREAD

**Issue by exodius48** [rovo89/Xposed#284]
Xposed SDK 24 v88.2

Here for the log:

*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'xiaomi/mido/mido:7.0/NRD90M/V9.0.3.0.NCFMIEI:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 7181, tid: 7181, name: id.thememanager  >>> com.android.thememanager <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x5a4c49ca
    x0   0000007f94497000  x1   0000000072eed20b  x2   0000007fd72ae7a7  x3   0000000000000001
    x4   0000000000000008  x5   0000007f8c57637c  x6   0000007f8c576384  x7   000000001eee0e84
    x8   0000000000000000  x9   00000000494c0500  x10  0000007fd72b5610  x11  7ff000fe00000000
    x12  0000000000000002  x13  0000000000000001  x14  0000000000000000  x15  000000000000004d
    x16  0000000072eed20f  x17  0000000000000049  x18  000000000000004c  x19  0000007fd72ae7c8
    x20  0000007fd72ae7a7  x21  0000007fd72b57b8  x22  0000000072eed20b  x23  0000007f945218f0
    x24  adc438ed6d59cb39  x25  adc438ed6d59cb39  x26  000000005a4c494c  x27  0000007fd72b4dd0
    x28  0000000000000001  x29  0000007fd72ae790  x30  0000007f93e51648
    sp   0000007fd72ae700  pc   0000007f93e9baf4  pstate 0000000080000000

backtrace:
    #00 pc 000000000012aaf4  /system/lib64/libart.so (_ZN3art11ClassLinker16FindOatMethodForEPNS_9ArtMethodEPb+84)
    #01 pc 00000000000e0644  /system/lib64/libart.so (_ZN3art9ArtMethod23GetOatQuickMethodHeaderEm+256)
    #02 pc 00000000002ebb94  /system/lib64/libart.so (offset 0x13b000)
    #03 pc 00000000000e1078  /system/lib64/libart.so (_ZN3artL43StackReplaceMethodAndInstallInstrumentationEPNS_6ThreadEPv+100)
    #04 pc 000000000030e18c  /system/lib64/libart.so (offset 0x13b000)
    #05 pc 00000000000e0cfc  /system/lib64/libart.so (_ZN3art9ArtMethod16EnableXposedHookERNS_18ScopedObjectAccessEP8_jobject+692)
    #06 pc 0000000000004ff8  /system/lib64/libxposed_art.so (_ZN6xposed29XposedBridge_hookMethodNativeEP7_JNIEnvP7_jclassP8_jobjectS5_iS5_+592)
    #07 pc 000000000007c884  /data/dalvik-cache/arm64/system@framework@XposedBridge.jar@classes.dex (offset 0x67000)

**Comment by rovo89** [comment]
Could you please try if it works better with v89?

**Comment by What-Zit-Tooya** [comment]
Problem solved, v89 very stable for miui, thank for bring xposed for miui after all.
Tested on my device Xiaomi Redmi Note 4X powered by MIUI 9 7.2.14 miuipro.
