### ISSUE TITLE
Google Play Error 504 after installing Xposed 88.2

### ISSUE THREAD

**Issue by chintzle** [rovo89/Xposed#288]
Hi,

After i installed Xposed 88.2 on my LG G5 i couldn't update or install any app via Play Store.
I always get an error 504. When i uninstall Xposed everything is fine again.
Clearing Data from the Play Store and Google Framework didn't help.

I have an LG G5 v20k arm64.
Android 7.0

Thank you :)

**Comment by sup3rgiu** [comment]
I'm getting the same error on my LG G4. I can't even install apk from adb command line.

I hope in a fix beacause I had to unistall xposed frameworks :/

**Comment by chintzle** [comment]
I fixed my problem yesterday...

In Lucky Patcher disable on the Xposed-Settings "deactivate APK Signature Verification" (Something like this, i have my LP in german :-/)
