### ISSUE TITLE
app often anr

### ISSUE THREAD

**Issue by nicehch** [rovo89/Xposed#293]
(Xiaomi gemini - MIUI 9 - Xposed 88.2)
MIUI Chinese community feedback message: https://www.miui.com/thread-11152927-1-1.html

The following is MIUI LOG, If you need xposed log, please let me know, thanks.

11-16 14:55:08.998 11911 11911 W MIUI-BLOCK-MONITOR: The binder call took 10794ms.
11-16 14:55:08.998 11911 11911 W MIUI-BLOCK-MONITOR: java.lang.Throwable
11-16 14:55:08.998 11911 11911 W MIUI-BLOCK-MONITOR:         at android.os.AnrMonitor.checkBinderCallTime(AnrMonitor.java:657)
11-16 14:55:08.998 11911 11911 W MIUI-BLOCK-MONITOR:         at android.os.AnrMonitor.checkBinderCallTime(AnrMonitor.java:647)
11-16 14:55:08.998 11911 11911 W MIUI-BLOCK-MONITOR:         at android.os.BinderProxy.transact(Binder.java:621)
11-16 14:55:08.998 11911 11911 W MIUI-BLOCK-MONITOR:         at android.content.pm.IPackageManager$Stub$Proxy.queryIntentServices(IPackageManager.java:3443)
11-16 14:55:08.998 11911 11911 W MIUI-BLOCK-MONITOR:         at android.app.ApplicationPackageManager.queryIntentServicesAsUser(ApplicationPackageManager.java:910)
11-16 14:55:08.998 11911 11911 W MIUI-BLOCK-MONITOR:         at android.app.ApplicationPackageManager.queryIntentServices(ApplicationPackageManager.java:924)
11-16 14:55:08.998 11911 11911 W MIUI-BLOCK-MONITOR:         at abx.a(:com.google.android.gms@11946448:9)
11-16 14:55:08.998 11911 11911 W MIUI-BLOCK-MONITOR:         at aby.onReceive(:com.google.android.gms@11946448)
11-16 14:55:08.998 11911 11911 W MIUI-BLOCK-MONITOR:         at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1143)
11-16 14:55:08.998 11911 11911 W MIUI-BLOCK-MONITOR:         at android.os.Handler.handleCallback(Handler.java:754)
11-16 14:55:08.998 11911 11911 W MIUI-BLOCK-MONITOR:         at android.os.Handler.dispatchMessage(Handler.java:95)
11-16 14:55:08.998 11911 11911 W MIUI-BLOCK-MONITOR:         at android.os.Looper.loop(Looper.java:163)
11-16 14:55:08.998 11911 11911 W MIUI-BLOCK-MONITOR:         at android.app.ActivityThread.main(ActivityThread.java:6357)
11-16 14:55:08.998 11911 11911 W MIUI-BLOCK-MONITOR:         at java.lang.reflect.Method.invoke(Native Method)
11-16 14:55:08.998 11911 11911 W MIUI-BLOCK-MONITOR:         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
11-16 14:55:08.998 11911 11911 W MIUI-BLOCK-MONITOR:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
11-16 14:55:08.998 11911 11911 W MIUI-BLOCK-MONITOR:         at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Comment by rovo89** [comment]
I don't see how this is related to Xposed.
