### ISSUE TITLE
Magisk systemless Xposed bootlooping

### ISSUE THREAD

**Issue by minhducsun2002** [rovo89/Xposed#296]
As the title says, installing Xposed systemless-ly through Magisk causes a bootloop for me. Any fix? Thank you very much.
(Lollipop 5.1, near-AOSP stock ROM, rooted with Magisk v14)

**Comment by rovo89** [comment]
Sorry, but I can't give support for unofficial versions of Xposed.

**Comment by minhducsun2002** [comment]
Oh, I thought it was your port? Or it was XDA's topjohnwu?
