### ISSUE TITLE
Different behavior on Android 6 and 7

### ISSUE THREAD

**Issue by R1p4eg** [rovo89/Xposed#297]
Hello!

First of all, @rovo89 , thank you for great work! It is really awesome!

I`ve noticed a different in behavior of hook methods in android 6 and android 7.
I try to hook "libcore.io.IoBridge" method "open" from module "droidmon" (https://github.com/idanr1986/droidmon).
I compile it for myself using the latest API for Xposed (82).
In Android 6 I get a lot of calls (about 100). But in Android 7 I can see only 6 times.

Please, would you be so kind to tell me, it is problem with module (droidmon) or something changed in Android maybe (permissions check or whatever)?

Thank you!

**Comment by rovo89** [comment]
Most likely, that function simply isn't called that often anymore on Nougat. Maybe some higher-level method is now using another implementation. I suggest you try to find out which methods used to call the open() method on Marshmallow (e.g. by logging the stack trace each time) and then check in the source code of Nougat whether everything is still as it was.
