### ISSUE TITLE
Support for Android 5.1

### ISSUE THREAD

**Issue by ckuethe** [rovo89/Xposed#30]
Android 5.1 (SDK 22) is now out, xposed-arm-20150308.zip is compiled against SDK 21 and won't install.

**Comment by rovo89** [comment]
If you want, try to change xposed.prop in the zip and increase the maxSdk version. If the device doesn't start with these files, which is quite likely, it's not just about recompiling it, but needs more work to port Xposed to Android 5.1.
I will first make sure that Xposed runs fine on 5.0 though.

**Comment by JimyKK** [comment]
Just for info
Attempted changing xposed.prop on my Nexus 5. Got caught booting, logcat loops these lines: 

14:04:29.273 Info Netd 9305  Netd 1.0 starting
14:04:29.381 Info mediaserver 9306  ServiceManager: 0xb58700c0
14:04:29.381 Info AudioFlinger 9306  Using default 3000 mSec as standby time.
14:04:29.381 Info ServiceManager 9306  Waiting for service batterystats...
14:04:30.255 Info ServiceManager 173  service 'media.audio_flinger' died

Restoring from my nand backup. Thanks for all the awesome stuff in xposed

**Comment by ckuethe** [comment]
You are correct; simply increasing the maxSdk version does not work.

Thanks for your work on Xposed.

**Comment by rovo89** [comment]
OK, thanks for the info.

So you will have to wait until I have the time to make Xposed on 5.1 more stable, and then I will work on 5.1 support. It won't take as long as the initial version (hopefully, but it seems to be a rather small update).

**Please, no begging and asking for an ETA here.** Only technical info that might support development.

**Comment by ckuethe** [comment]
No worries - I know perfectly well what alpha snapshot means.

**Comment by romracer** [comment]
So... I created a fork, merged Android 5.1 in and applied a few fixes to get the code to compile.  These changes are all pushed to my repo fork.

I also have an Xposed zip that's based on the result of that.  I hesitate to link it here without rovo89's permission.  And I haven't had time to put the 5.1 soak test leak on my Moto X 2014.  I'd be willing to provide the installer (with permission) if people want to test.

You'd better know how to recover from a non-bootable system though.

**Comment by ckuethe** [comment]
Sure, I'll try. I already had to do one recovery after just trying to crank
the sdk version number.

On Mon, Mar 23, 2015 at 3:56 PM, romracer <notifications@github.com> wrote:

> So... I created a fork, merged Android 5.1 in and applied a few fixes to
> get the code to compile. These changes are all pushed to my repo fork.
>
> I also have an Xposed zip that's based on the result of that. I hesitate
> to link it here without rovo89's permission. And I haven't had time to put
> the 5.1 soak test leak on my Moto X 2014. I'd be willing to provide the
> installer (with permission) if people want to test.
>
> You'd better know how to recover from a non-bootable system though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rovo89/Xposed/issues/30#issuecomment-85239031>.
>



-- 
GDB has a 'break' feature; why doesn't it have 'fix' too?

**Comment by romracer** [comment]
I would need a way to get it to you (email, etc).  I won't post it publicly without permission from rovo89.

**Comment by ckuethe** [comment]
ckuethe@bigfoot.com

**Comment by StrogonoffBR** [comment]
Hi, can you give me the edited Xposed that work in 5.1?

But some modules that work in 5.0 maybe don't work in 5.1, alright?

Thanks!

ikeerpbr@gmail.com

**Comment by romracer** [comment]
@StrogonoffBR I'm only interested in testing the framework itself on 5.1.  Individual modules will undoubtedly need to be updated.  Currently it is loading some modules fine but needs additional testing:

```
03-17 00:00:02.149 I/Xposed  (  392): -----------------
03-17 00:00:02.149 I/Xposed  (  392): Starting Xposed binary version 61, compiled for SDK 22
03-17 00:00:02.149 I/Xposed  (  392): Device: XT1095 (motorola), Android version 5.1 (SDK 22)
03-17 00:00:02.150 I/Xposed  (  392): ROM: LPE23.28
03-17 00:00:02.150 I/Xposed  (  392): Build fingerprint: motorola/victara_tmo/victara:5.1/LPE23.28/10:user/release-keys
03-17 00:00:02.150 I/Xposed  (  392): Platform: armeabi-v7a, 32-bit binary, system server: yes
03-17 00:00:02.150 I/Xposed  (  392): SELinux enabled: yes, enforcing: yes
03-25 07:16:55.433 I/Xposed  (  392): -----------------
03-25 07:16:55.434 I/Xposed  (  392): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
03-25 07:16:55.725 I/Xposed  (  392): Detected ART runtime
03-25 07:16:55.747 I/Xposed  (  392): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
03-25 07:16:55.866 I/Xposed  (  392): Initializing XposedBridge version 62
03-25 07:16:55.958 I/Xposed  (  392): Loading modules from /data/app/biz.underpants_gnomes.android.xposed.mods.xposedsmsabort-2/base.apk
03-25 07:16:56.226 I/Xposed  (  392):   Loading class biz.underpants_gnomes.android.xposed.mods.xposedsmsabort.XposedSMSAbort
```

**Comment by Hendrik212** [comment]
@romracer Could you send me your test version, too? I'd like to test it on a Nexus 6.
hendrikgroove@gmx.de

Thanks!

**Comment by wbedard** [comment]
I have a dedicated testing device that I am using to evaluate XPosed on the Android 5.x platform (ie, not my "daily driver").  As such, I would really like to have access to such development builds, with the full understanding that they are fully unsupported (by anyone...).  Any feedback received from them would presumably be used to support ongoing development on a "as time and interest allows" basis.

**Comment by rovo89** [comment]
@romracer In case you're still waiting for my approval: Yes, please post your test version, preferably create a separate thread on XDA or something like that to avoid that people use GitHub for discussions. Just make clear that it's not an official version and that you "just" made some adoptions for 5.1 (instead of rewriting it from scratch, which would be much more work).

I'm currently working on scripts for building and packaging (whenever my time allows it), which will hopefully make it easier for people like you to get involved. After all, this is one of the reason the project is open-source.

**Comment by poooower** [comment]
@rovo89 @romracer  Could you add some documents about how to compile the code please? 
Thanks!

**Comment by romracer** [comment]
@rovo89 Sure, I will post it.  About to head out for a "honeymooon weekend" with the wife so I'm hesitant to just throw it up there and vanish for a few days.  I'll post it up later this weekend though.

@poooower I believe @rovo89 said he's working on them just above you ;)  I'd be happy to do it too, but my method may not be "official".

**Comment by cabagekiller** [comment]
@romracer if you need someone to test it without worriea of it. I have my old nexus 5 I can flash and do whatever with it.

**Comment by pylerSM** [comment]
Great! So xposed devs will have time to update their modules :) After official release from rovo89 for 5.1, modules will just work.

**Comment by rovo89** [comment]
As @romracer mentioned, he is planning to post his version for 5.1 later this weekend. So please refrain from offering to test it or "when will it be ready" questions, as this will send emails to 120 watchers of this repository...

**Comment by Shwise** [comment]
@romracer Would you PM me the test version on XDA? Thanks! Username: shwise

**Comment by pylerSM** [comment]
Nothing published.

**Comment by RobotRoss** [comment]
I think we're all eagerly awaiting this, but be patient, i'm sure when it is published we'll be linked to the XDA thread here.

**Comment by romracer** [comment]
@pylerSM Sorry if I disappointed you.  My initial testing on my Moto X using the leaked 5.1 worked okay, but when I went to test on my Nexus 5 test phone, I found an issue.  At least my N5, freshly flashed to LMY47I, only has about 4.8MB of free space on the /system partition.  It also doesn't include the unzip command.

This complicated just dragging and dropping replacement binaries in the installer zip, because now there's not enough room to make backups of the replaced files.  And without unzip, the updater script needs to be tweaked (it relies on unzip to extract itself).

All problems relatively easily overcome and my N5 is booting right now.  But it takes time, and as I said, I was out of town for the weekend.  I'll publish once I think its relatively safe to use, but what good would it have done to rush it out there and have a forum full of people (at least those using N5s - how many devices even have 5.1?) that won't boot because some key ART libraries are zero bytes (because the device is out of space)?

I'll take the blame this time for providing an ETA I guess... Please have patience, it will come.

```
03-31 18:38:32.068 I/Xposed  (  232): -----------------
03-31 18:38:32.068 I/Xposed  (  232): Starting Xposed binary version 61, compiled for SDK 22
03-31 18:38:32.068 I/Xposed  (  232): Device: Nexus 5 (LGE), Android version 5.1 (SDK 22)
03-31 18:38:32.068 I/Xposed  (  232): ROM: LMY47I
03-31 18:38:32.068 I/Xposed  (  232): Build fingerprint: google/hammerhead/hammerhead:5.1/LMY47I/1767468:user/release-keys
03-31 18:38:32.068 I/Xposed  (  232): Platform: armeabi-v7a, 32-bit binary, system server: yes
03-31 18:38:32.068 I/Xposed  (  232): SELinux enabled: yes, enforcing: yes
03-31 18:38:32.083 I/Xposed  (  232): -----------------
03-31 18:38:32.084 I/Xposed  (  232): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
03-31 18:38:32.595 I/Xposed  (  232): Detected ART runtime
03-31 18:38:32.633 I/Xposed  (  232): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
03-31 18:38:32.801 I/Xposed  (  232): Initializing XposedBridge version 62
03-31 18:38:32.954 E/Xposed  (  232): Cannot load any modules because /data/data/de.robv.android.xposed.installer/conf/modules.list was not found
```

**Comment by meCapa** [comment]
@romracer Hah, I like it dangerous tho :P

**Comment by poooower** [comment]
@romracer   My phone is Nexus6. can i try it?  
poooower@gmail.com
Thanks!

**Comment by pylerSM** [comment]
Thanks for info. Finally rovo89 found somebody who can help him with Xposed stuff. Keep it up.

**Comment by RobotRoss** [comment]
I'd be happy to try the build too. I have a Oneplus One 64GB, email is true.robot.ross@gmail.com

**Comment by rovo89** [comment]
Please avoid asking for ETAs, test versions etc. here. I have now locked this issue. If @romracer wants to give a status update, he can contact me.
