### ISSUE TITLE
Xposed framework v87 to 89...

### ISSUE THREAD

**Issue by Zzzleepy** [rovo89/Xposed#301]
So here is my issue for today, I installed Xposed on my Infinix Hot 4 x557 and there was an option to upgrade a systemless xposed to v89. Then I got this error or something. Please help.

![screenshot_20171223-112648](https://user-images.githubusercontent.com/34257943/34316625-4e704d16-e7d5-11e7-8777-c82b288279e9.png)
[xposed_error_20171223_112724.log](https://github.com/rovo89/Xposed/files/1583834/xposed_error_20171223_112724.log)

**Comment by rovo89** [comment]
You seem to be using various unofficial Xposed versions. I can only support the official one. However, I suggest that you completely uninstall the framework, make sure everything is really gone, and then reinstall.

**Comment by cokeboyle** [comment]
Iam'cokeboyle

เมื่อ 23 ธ.ค. 2017 13:42 "rovo89" <notifications@github.com> เขียนว่า

**Comment by Zzzleepy** [comment]
Oh never mind, I got just made sure that I installed it from Magisk, and I got the Xposed Installer apk, even of older version, just needs updating. Thanks for responding.
