### ISSUE TITLE
Amplify module not working on Honor 6 (H60-L04)

### ISSUE THREAD

**Issue by Raistlin1990** [rovo89/Xposed#302]
Hey guys, 
After reading a Battery Saving Guide on XDA, I installed Framework and tried to use Amplify. It could collect the Wakelocks, so I asked for help in the threat. They told me to check my Xposed log and it was empty, so the theory is, that there is something wrong with my framework. Checking the Xposed Installer -> Framework is installed and active. So...why is the log(file) empty? Shouldnt it at least show me SOMETHING?

**Comment by wanam** [comment]
Make sure the logs are enabled on your device, they are default disabled on most of Huawei devices.

**Comment by Raistlin1990** [comment]
And how do i do this?

**Comment by Raistlin1990** [comment]
Ok, finally got them enabled. Any ideas why Amplify does not work? 

12-25 13:59:00.141 I/Xposed  ( 3739): -----------------
12-25 13:59:00.141 I/Xposed  ( 3739): Starting Xposed version 89, compiled for SDK 23
12-25 13:59:00.141 I/Xposed  ( 3739): Device: H60-L04 (HUAWEI), Android version 6.0 (SDK 23)
12-25 13:59:00.141 I/Xposed  ( 3739): ROM: H60-L04C432B860
12-25 13:59:00.141 I/Xposed  ( 3739): Build fingerprint: Huawei/H60-L04/hwH60:6.0/HDH60-L04/C432B860:user/release-keys
12-25 13:59:00.141 I/Xposed  ( 3739): Platform: armeabi-v7a, 32-bit binary, system server: yes
12-25 13:59:00.141 I/Xposed  ( 3739): SELinux enabled: yes, enforcing: yes
12-25 13:59:00.179 I/Xposed  ( 3739): -----------------
12-25 13:59:00.179 I/Xposed  ( 3739): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
12-25 13:59:00.680 I/Xposed  ( 3739): Detected ART runtime
12-25 13:59:00.721 I/Xposed  ( 3739): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
12-25 13:59:01.548 I/Xposed  ( 3739): Loading modules from /data/app/com.ryansteckler.nlpunbounce-1/base.apk
12-25 13:59:01.571 I/Xposed  ( 3739):   Loading class com.ryansteckler.nlpunbounce.hooks.Wakelocks
12-25 13:59:04.776 I/Xposed  ( 4341): Amplify: Version 4.0.1
12-25 13:59:04.776 I/Xposed  ( 4341): Amplify: Attempting 19to21 AlarmHook
12-25 13:59:04.778 I/Xposed  ( 4341): Amplify: Successful 19to21 AlarmHook
12-25 13:59:04.778 I/Xposed  ( 4341): Amplify: Attempting 21 WakeLockHook
12-25 13:59:04.782 I/Xposed  ( 4341): Amplify: Successful 21 WakeLockHook
12-25 13:59:04.782 I/Xposed  ( 4341): Amplify: Attempting 23 ServiceHook
12-25 13:59:04.783 I/Xposed  ( 4341): Amplify: Successful 23 ServiceHook
12-25 13:59:27.504 E/Xposed  ( 4341): java.lang.SecurityException: Unable to find app for caller android.app.ActivityThread$ApplicationThread@9758034 (pid=4341) when registering receiver android.app.LoadedApk$ReceiverDispatcher$InnerReceiver@4f9e5d
12-25 13:59:27.504 E/Xposed  ( 4341): 	at com.android.server.am.ActivityManagerService.registerReceiver(ActivityManagerService.java:16901)
12-25 13:59:27.504 E/Xposed  ( 4341): 	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1341)
12-25 13:59:27.504 E/Xposed  ( 4341): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1309)
12-25 13:59:27.504 E/Xposed  ( 4341): 	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1303)
12-25 13:59:27.504 E/Xposed  ( 4341): 	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:554)
12-25 13:59:27.504 E/Xposed  ( 4341): 	at com.ryansteckler.nlpunbounce.hooks.Wakelocks.setupReceiver(Wakelocks.java:495)
12-25 13:59:27.504 E/Xposed  ( 4341): 	at com.ryansteckler.nlpunbounce.hooks.Wakelocks.handleAlarm(Wakelocks.java:508)
12-25 13:59:27.504 E/Xposed  ( 4341): 	at com.ryansteckler.nlpunbounce.hooks.Wakelocks.access$300(Wakelocks.java:36)
12-25 13:59:27.504 E/Xposed  ( 4341): 	at com.ryansteckler.nlpunbounce.hooks.Wakelocks$15.afterHookedMethod(Wakelocks.java:314)
12-25 13:59:27.504 E/Xposed  ( 4341): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:374)
12-25 13:59:27.504 E/Xposed  ( 4341): 	at com.android.server.AlarmManagerService.triggerAlarmsLocked(<Xposed>)
12-25 13:59:27.504 E/Xposed  ( 4341): 	at com.android.server.AlarmManagerService$AlarmThread.run(AlarmManagerService.java:2610)
12-25 13:59:31.438 ?/SENTINEL_TAG( 5580): SENTINEL_MSG_LIBCUTILS
12-25 13:59:31.439 ?/SENTINEL_TAG( 5580): SENTINEL_MSG_LIBLOG
12-25 13:59:49.619 ?/SENTINEL_TAG( 7489): SENTINEL_MSG_LIBCUTILS
12-25 13:59:49.619 ?/SENTINEL_TAG( 7489): SENTINEL_MSG_LIBLOG
12-25 13:59:56.394 ?/SENTINEL_TAG( 8014): SENTINEL_MSG_LIBCUTILS
12-25 13:59:56.394 ?/SENTINEL_TAG( 8014): SENTINEL_MSG_LIBLOG
12-25 14:00:10.974 ?/SENTINEL_TAG( 9073): SENTINEL_MSG_LIBCUTILS
12-25 14:00:10.974 ?/SENTINEL_TAG( 9073): SENTINEL_MSG_LIBLOG
12-25 14:00:48.418 ?/SENTINEL_TAG(11148): SENTINEL_MSG_LIBCUTILS
12-25 14:00:48.419 ?/SENTINEL_TAG(11148): SENTINEL_MSG_LIBLOG

**Comment by Raistlin1990** [comment]
no ideas?

**Comment by rovo89** [comment]
The logs show that the module was loaded and successfully hooked some functions. There's another module "com.ryansteckler.nlpunbounce" which causes some errors, but that shouldn't influence Amplify. So I suggest you get back to the module author and ask what exactly the framework problem is, because I don't see any.

**Comment by tomasz1986** [comment]
Just for the record, "com.ryansteckler.nlpunbounce" _is_ Amplify.

**Comment by rovo89** [comment]
Oh OK. Well, then you can tell the module author that there's a problem with the way they try to register their receiver. The SecurityException is thrown for their module, not for the framework.

I'm going to close this for now. If the module author analyzes the issue and finds out that this indeed a problem in the framework, please reopen.
