### ISSUE TITLE
V90 Beta_1 on Xperia XZ SDK26

### ISSUE THREAD

**Issue by solirf** [rovo89/Xposed#305]
after installation first booting (boot animation) is very laggy , wipe davlik cache not helped
after that phone boots without any error/crash but very very laggy , everything is slow 
i only test Sudohide module and its worked as it should be

**Comment by rovo89** [comment]
A cache is meant to improve performance, so wiping it usually makes things slower until the cache is filled again. Please see my comments on the versions I just released, maybe those features help you: https://forum.xda-developers.com/showpost.php?p=75248580&postcount=49
If not, please reopen with more details.

**Comment by solirf** [comment]
V90 Beta_2 works well on my xperia xz sdk 26 , thanks 
Also "Optimize apps now"  has a lot of impact
