### ISSUE TITLE
SDK26 galaxyS8+ not booting(kmsg attached)

### ISSUE THREAD

**Issue by bisebi** [rovo89/Xposed#306]
[last_kmsg.txt](https://github.com/rovo89/Xposed/files/1613863/last_kmsg.txt)
the phone seems to be booting. I get feedback if i use the hard press on home but it still shows boot animation.

**Comment by rovo89** [comment]
kmsg the kernel log. Could you please post a logcat of the boot loop instead?

**Comment by bisebi** [comment]
[logcat.txt](https://github.com/rovo89/Xposed/files/1616718/logcat.txt)
this is from s8(950F), can't get one myself right now from the s8+(955F)

**Comment by roiz-git** [comment]
Does that means that all Samsung Galaxy S8 950F will boot loop? Any value with continuing testing on them?

**Comment by rovo89** [comment]
> Does that means that all Samsung Galaxy S8 950F will boot loop? Any value with continuing testing on them?

Probably. See https://github.com/rovo89/XposedBridge/issues/226 for more details.
