### ISSUE TITLE
Sony Z3 Compact bootloop

### ISSUE THREAD

**Issue by michyprima** [rovo89/Xposed#31]
install goes fine. First boot is okay. xposed works. From 2nd boot the phone will bootloop. Nothing will make the phone boot again but a factory reset.

**Comment by rovo89** [comment]
Please post a logcat of the bootloop.

**Comment by michyprima** [comment]
I can't as adb will not work anymore. Any suggestion on how I could get a logcat without adb?
Also I forgot to mention it does not loop in the "usual" way. It does a full restart after a while on the boot animation

**Comment by michyprima** [comment]
Another clue: I saw the nfc firmware updater force close when it booted. Might this be useful?

**Comment by rovo89** [comment]
Not really. I can't do anything without the logs. You could ask on XDA if someone has the same problem on your ROM and can get a logcat.

**Comment by michyprima** [comment]
Please don't close this issue. I will try again to get a logcat.

**Comment by michyprima** [comment]
Finally found a way. 
https://www.dropbox.com/s/vfmc6ooj1o5p94z/liveboot.zip?dl=0

**Comment by WedyDQ10** [comment]
Another logs:
http://x.androplus.org/1xpcVj2
[1] error.log - Xposed Log after installing and reboot. This time Xposed is working. (sorry for enabling too many modules)
[2] boot_stopped.log - Boot log after reboot and stopped booting. Bootlooped.
[3] boot_working.log - Boot log after wipe dalvik cache via recovery. Xposed is working.
[4] boot_stopped.log - Boot log after reboot and stopped booting. Bootlooped.

/system/framework:
http://x.androplus.org/1xpcXYd

some stock files in /system/lib and /bin:
http://x.androplus.org/1GFMJAq

Xposed is working only after first installation and after wiping dalvik cache...

**Comment by rovo89** [comment]
Both failing logs have a NPE in `android.app.ContextImpl.checkPermission()`. So probably `ActivityManagerNative.getDefault()` returns `null`. No idea why. Maybe someone with this ROM could create a test module to log the return value of this and related methods?

**Comment by michyprima** [comment]
So patching checkpermission might work as a temporary workaround?

**Comment by rovo89** [comment]
Probably not. Then the next method using the activity manager would most likely fail...

**Comment by michyprima** [comment]
I still don't understand why this happens only after play services are updated. I mean, shouldn't them be a separate portion of the system?

**Comment by borz93** [comment]
This is a catlog from serajr Xposed Test Module for LP in Xperia Z2 Stock Lollipop.
Source: http://forum.xda-developers.com/showpost.php?p=59653356&postcount=224
catlog: http://pastebin.com/CjeNZKsp

**Comment by rovo89** [comment]
Thanks! That's from a working system though, right? What I would need is some analysis of the situation when the bootloop occurs.

**Comment by hussainalhaddad** [comment]
here's a log from Z2 stock lollipop bootllooped running xposed with nothing but serajr's test module enable.

http://rghost.net/8ybJj7Xyr

**Comment by hussainalhaddad** [comment]
one last thing... the file app_process32 in the xposed zip is called "app_process32_xposed" and the update-binary looks for "app_process32"! is this a typo?!

**Comment by Shahar2k5** [comment]
Hey, I treid starting all from scretch, factory reset, flash Xposed, install APK and install GravityBox, everything works great, no bootloop.
I started installing app one at a time, it turnes out that there are specific apps that break it and make a Bootloop.
For example, "AnTuTu Benchmark" https://play.google.com/store/apps/details?id=com.antutu.ABenchMark&hl=en
I dont know why, is there anyway i can get a log so it will help the devs here?

**Comment by rovo89** [comment]
@hussainalhaddad The log you posted doesn't have the test module activated, but some others... 
@Shahar2k5 Your log seems to be taken too late, it probably starts after the reason for the crash has already occured.

I'm wondering whether the "Too many open files" error is just a consequence or the reason of the crash. Could anyone execute "ulimit -n" to find out how many open files are allowed?
And also, it might still be helpful to get a proper log with the test module installed.

**Comment by hussainalhaddad** [comment]
@rovo89 as i mentioned, the system crashes before loading any modules... the other modules are just listed but not loaded.

Also i'm pretty sure it has something to do with dex2oat. now i believe when we deodex the rom, this would have nothing to do right? that's why it works when deodexing!

what are the parameters you're using in your dex2oat?

**Comment by WedyDQ10** [comment]
The result of "ulimit -n" was 1024.

I deodexed system and now I don't get bootloop.
Here is logs:
http://x.androplus.org/1HQ88r5
livebootWtestmodule.log -> log with test module enabled
xposed_error_20150408_194100.log -> xposed log with test module enabled
livebootWOtestmodule.log -> log without any module including test module

java.lang.NoSuchMethodError: android.app.ActivityManagerNative#gDefault()#exact
happens but xposed works without problem when I enable some other modules... strange.

I'll try to revert back to odex (stock) system and get logs when I have enough time.

**Comment by michyprima** [comment]
I can confirm deodexing gets around the issue.

**Comment by rovo89** [comment]
dex2oat does what the name says, it converts the .dex files (usually contained in the APK/JAR as classes.dex) and compiles them to .oat files. The .dex files are still rather close to Java/Smali, whereas .oat files contain native code.

Odexed ROMs come with precompiled .oat files, which are named .odex and stored in the /system partition. This is to speed up the boot process, as it means that usually the system files don't need to be compiled on these ROMs.

However, Xposed needs to disable some ART optimizations and therefore needs to recompile the .odex files. This is possible because they still contain the original .dex files that they were compiled from. This recompilation is something that I have developed. It's strange though that the first boot (were the recompilation happens) works fine, and I didn't see dex2oat error messages for /system/framework/services.jar...

Could you create a log with the deodex'ed ROM after clearing the Dalvik cache? Just for comparison...

**Comment by hussainalhaddad** [comment]
i think when we clear the dalvik cache, the rom will start without them because they don't exist, and create them as soon as android starts past the point where it normally hangs, and then read them on the next boot and get stuck.

i also noticed that creating the dex files with xposed installed is a lot slower than without it.. the issue could be in creating the dex..or the rom simply can't read them.

i'll post some logs from a deodexed rom, and maybe deodex a full rom with xposed dex2oat?! possible??

**Comment by hussainalhaddad** [comment]
ok.. i just deodexed only the framework folder with no issues at all.. i skipped the app and priv-app so i don't get issues with google services... and of course xposed worked perfectly.. so it's probably a file or more that aren't compatible with the dex2oat modifications... i'll dig even more to find which file(s).

**Comment by WedyDQ10** [comment]
Here's log with deodexed system after clearing dalvik cache:
http://x.androplus.org/1HeLNWb

**Comment by cpurick** [comment]
Can just anybody fix this, or does it have to be rovo89? I can't develop for Android, but I'd be happy to contribute to a bounty for this. These recompiles are burning out my battery.

**Comment by Shahar2k5** [comment]
@hussainalhaddad i deodexed only the framework but i still get bootloop, can you point me to a guide or upload the deodexed framework please?
Thanks.

**Comment by hussainalhaddad** [comment]
@Shahar2k5 have you cleared the dalvik cache after deodexing?? it's important to do so.... anyway, i used JoelDroid2.3 from http://www.s4mods.ml/2015/02/deodex-android-50-lollipop.html

**Comment by Shahar2k5** [comment]
I tried using joel, deodexin only the framework, which i got out from the system.ext4 file.
I flashed a clean stock rom, clear dalvik and cache, replaced framework and got a bootloop, without xposed even…  just clean stock with deodexed framework…  :-( 
Can you give me a hand pls?
Maybe via email or skype?

**Comment by McBane87** [comment]
Deodexed Framework on Z1c was not working for me, too.
On first time starting with deodexed ROM and cleaned dalvik cahce it was booting, but all other times even after complete reinstall was never able to get the device boot again. Maybe I was one time lucky.

Only thing which seems to be different. Boot takes more time now before crashing and rebooting.

**Comment by Shahar2k5** [comment]
@McBane87 i did fix the script, didnt help…

**Comment by McBane87** [comment]
@Shahar2k5 
Yeah as I said.it is not working for me, too. deodexed framework without xposed is also causing bootloop.

**Comment by michyprima** [comment]
you cannot deodex the framework without deodexing everything.

**Comment by Shahar2k5** [comment]
@michyprima  what i did was taking out app,priv-app and framework from the system.ext4 via ext2explore, then deodex it with JoelDroid tool, flashed a stock, prerooted xzdr rom i made using prfcreator. 
Then i replaced the app, privapp and framework and got playstore and GPServices crashes...

**Comment by hussainalhaddad** [comment]
@michyprima yes you can.. why not?!

**Comment by robertosartori** [comment]
I don't know it this will be useful, but:
http://forum.xda-developers.com/showpost.php?p=60156490&postcount=5476

and

http://forum.xda-developers.com/showpost.php?p=60183314&postcount=1

**Comment by cpurick** [comment]
Roberto, that's really good. Following those threads, AndroPlus found a "too many files open" error in the logs, and uploaded a kernel with INR_OPEN_CUR bumped to 4096. (This is in post #10 of Roberto's second link.)

Gustavo RD78 applied it to his kernel in post #20 and said it fixed the problem.

Not saying everyone needs to have 4096 open files, but maybe there's a leak somewhere in the dex2oat recompiles?

**Comment by Shahar2k5** [comment]
@rovo89 when using ulimit its session only, and not system wide.
is there anyway you can call 'ulimit -n 4096' when starting the xposed process?

**Comment by MaxRink** [comment]
The issue is present on every Sony LP-ROM so far

**Comment by rovo89** [comment]
> Not saying everyone needs to have 4096 open files, but maybe there's a leak somewhere in the dex2oat recompiles?

A leak in dex2oat probably wouldn't cause this, as a) it runs only on the first boot (and works fine there) and b) terminates once one file is recompiled, which closes any open files.

But good to know that the "too many open files" error is indeed relevant and not just a side-effect of the root cause. Can someone try if `lsof` or `busybox lsof` works, in order to list the open files? This should be executed with Xposed installed and working on the second boot, so ideally by someone who has the custom kernel and many apps installed.

**Comment by michyprima** [comment]
lsof:

https://docs.google.com/file/d/0B5jGXzZa6QnMc2c3OWsxcXNjRXM/edit?usp=docslist_api

**Comment by McBane87** [comment]
Just want to confirm that the Ulimit-Workaround is also working with Z1 Compact.
I compiled new Kernel and now no Bootloops anymore.

**Comment by Shahar2k5** [comment]
Hey @rovo89 ,
can you please tell me when and where in the system the xposed starts to load ?

Thanks,

Shahar.

**Comment by rovo89** [comment]
This will be hopefully be helpful to nail down the file descriptor leak:
http://forum.xda-developers.com/showpost.php?p=60373854&postcount=417

I will look through my changes when I find the time. If I can't spot anything directly, I'll add some more logging and post a debug version here.

**Comment by WedyDQ10** [comment]
After I flash xposed-sdk21-arm-20150426.zip, some modules stopped working.
(some Xperia user already reported on Xposed discussion thread)
log:
http://x.androplus.org/1Fu57hM

The error messages are related to this commit
https://github.com/rovo89/XposedBridge/commit/55fbe258d7ff444e987fa0b971489ba9ebb455f6
Should module developers do something to prevent this error, or it's related to above leak?

**Comment by cpurick** [comment]
I'm wondering if the open file count is worth checking on some other device. Are Sony phones more sensitive to a bug that opens too many files on every phone, or is there a reason it only open too many files on Sony devices? 

If we expect every device to be limited to 1024, then it's opening too many on Sony. But if other devices only work because their default limit happens to be higher, then it's possible this is also leaking on those devices without symptoms, like it does on a Sony running some of the current workarounds.

**Comment by rovo89** [comment]
@WedyDQ10 These are just warnings. Before that commit, there would have been an exception (no such method), but now it doesn't crash anymore, it just warns. I guess I have to add the stack trace to this warning, then it's clearer which module is causing this. Most likely, it's causes by App Settings, which I have already patched for myself. When I remember it, I will post a new APK.

I think the resource leak could also happen on other devices. So far, I have an idea where the leak might happen, but I couldn't try it yet. I'm not sure though, as nearly the same code is also present in AOSP (but of course, it could also be wrong there).

**Comment by rovo89** [comment]
Could someone test this please:
https://www.dropbox.com/s/adm5npi5dlcbqqp/xposed-sdk21-arm-20150430.zip?dl=0

Note: This is just a debug version, please don't link to it. In case it works, I will post a new, official version soon.

**Comment by mionica** [comment]
This is fixed for good.

[i] waiting for boot to finish...
[i] > boot completed after 27s
[v]  
[i] system_server has only 270 open files
[i]   (and Xposed is installed)
[i] this probably means the fix is no longer required :)
[v]  

good man!

**Comment by cpurick** [comment]
Thank you!!!

**Comment by cpurick** [comment]
I swear, Lollipop runs 100% better since this went in. Thanks.

**Comment by AbdulrahmanAmir** [comment]
What about Lg weather and smartcover hall monitor plzzz can u fix it @rovo89

**Comment by antonio95arg** [comment]
Hi . I need yours help. I can't install xposed in my phone Coradir Cs 505 with android lollipop 5.1 . an this doesn't support CWM and TWRP . How i can doing? Thanks

**Comment by AbdulrahmanAmir** [comment]
Hello I can help you by saying installing flashfire this will help and
replace of custom recovery but be aware and take it in your own
responsibility
There is another method and it is by copying the xposed files through root
explorer to the required destination

You're welcome

Donation url paypal : abdulrahmanamir98@gmail.com

**Comment by antonio95arg** [comment]
Hola. Resulta que siendo root hice la instalacion pero copiando los archivos de la carpeta que viene en los zip a mi telefono pero no me fue bien porque mi telefono luego quedo en bootloop. La solucion fue llevarlo al servicio tecnico a que le reinstalara el sistema operativo ya que tiene garantia de 1 a�o mi equipo

**Comment by antonio95arg** [comment]
Hi. I doing the instalation of the framework files with root explorer and without flasfire , and having stock recovery. but my phone have a bootloop and i can�t re-install the oficial rom why the root deny the new software. How i can doing for delete the root and install again the oficial rom stock? Thank you

**Comment by rovo89** [comment]
@antonio95arg Please stop hijacking this issue. Such questions should be asked on the XDA forum for your device, not on GitHub. Make sure to mention which device/ROM you have.
