### ISSUE TITLE
Searching and Downloading in xposed v90-beta1 causes XposedInstaller 3.1.4 to crash.

### ISSUE THREAD

**Issue by doio** [rovo89/Xposed#313]
I am on OnePlus 3T 8.0. 
When searching for a xposed plugin and downloading it at plugin page, XposedInstaller would automatically FC. But it won't crash if you are just scrolling down the list of plugins available and going in the plugin page that you meant to search for. 

Logs privided.
[xposed_error_20180116_170045.log](https://github.com/rovo89/Xposed/files/1634258/xposed_error_20180116_170045.log)

**Comment by rovo89** [comment]
Known issue: https://github.com/rovo89/XposedInstaller/issues/420
Will be fixed soon.

Also, this would be the wrong repository, it's for the framework instead of the installer app.
