### ISSUE TITLE
Xposed Installed But not Active

### ISSUE THREAD

**Issue by abualeisan** [rovo89/Xposed#318]
Android version (sdk22)
ROM (STOCK AOSP)
I have tried Everything that is posted on Xda Thread 
Here Is the Log
17 12:03:33.102 I/Xposed  (  255): -----------------
01-17 12:03:33.102 I/Xposed  (  255): Starting Xposed version 89, compiled for SDK 22
01-17 12:03:33.102 I/Xposed  (  255): Device: Iris Fuel F1 (LAVA), Android version 5.1 (SDK 22)
01-17 12:03:33.102 I/Xposed  (  255): ROM: LMY47I release-keys
01-17 12:03:33.102 I/Xposed  (  255): Build fingerprint: Iris/FuelF1/IrisFuelF1:5.1/LMY47I/1442120858:user/release-keys
01-17 12:03:33.102 I/Xposed  (  255): Platform: armeabi-v7a, 32-bit binary, system server: yes
01-17 12:03:33.102 I/Xposed  (  255): SELinux enabled: yes, enforcing: no
01-17 12:03:36.280 I/Xposed  (  255): -----------------
01-17 12:03:36.284 I/Xposed  (  255): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
01-17 12:03:36.526 I/Xposed  (  255): Detected ART runtime
01-17 12:03:36.532 I/Xposed  (  255): Found Xposed class 'de/robv/android/xposed/XposedBridge', now initializing
01-17 12:03:36.704 E/Xposed  (  255): Error while loading XResources class 'android/content/res/XResources':
01-17 12:03:36.704 E/Xposed  (  255): java.lang.IllegalAccessError: xposed.dummy.XResourcesSuperClass
01-17 12:03:36.705 E/Xposed  (  255):   at java.lang.Class dalvik.system.DexFile.defineClassNative(java.lang.String, java.lang.ClassLoader, long) (DexFile.java:-2)
01-17 12:03:36.705 E/Xposed  (  255):   at java.lang.Class dalvik.system.DexFile.defineClass(java.lang.String, java.lang.ClassLoader, long, java.util.List) (DexFile.java:226)
01-17 12:03:36.705 E/Xposed  (  255):   at java.lang.Class dalvik.system.DexFile.loadClassBinaryName(java.lang.String, java.lang.ClassLoader, java.util.List) (DexFile.java:219)
01-17 12:03:36.705 E/Xposed  (  255):   at java.lang.Class dalvik.system.DexPathList.findClass(java.lang.String, java.util.List) (DexPathList.java:321)
01-17 12:03:36.705 E/Xposed  (  255):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:54)
01-17 12:03:36.705 E/Xposed  (  255):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:511)
01-17 12:03:36.705 E/Xposed  (  255):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:504)
01-17 12:03:36.705 E/Xposed  (  255):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:469)
01-17 12:03:36.705 E/Xposed  (  255):   at java.lang.Class dalvik.system.DexFile.defineClassNative(java.lang.String, java.lang.ClassLoader, long) (DexFile.java:-2)
01-17 12:03:36.705 E/Xposed  (  255):   at java.lang.Class dalvik.system.DexFile.defineClass(java.lang.String, java.lang.ClassLoader, long, java.util.List) (DexFile.java:226)
01-17 12:03:36.705 E/Xposed  (  255):   at java.lang.Class dalvik.system.DexFile.loadClassBinaryName(java.lang.String, java.lang.ClassLoader, java.util.List) (DexFile.java:219)
01-17 12:03:36.705 E/Xposed  (  255):   at java.lang.Class dalvik.system.DexPathList.findClass(java.lang.String, java.util.List) (DexPathList.java:321)
01-17 12:03:36.705 E/Xposed  (  255):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:54)
01-17 12:03:36.705 E/Xposed  (  255):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:511)
01-17 12:03:36.705 E/Xposed  (  255):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:469)
01-17 12:03:36.705 E/Xposed  (  255):   at boolean de.robv.android.xposed.XposedBridge.initXResourcesNative() (XposedBridge.java:-2)
01-17 12:03:36.705 E/Xposed  (  255):   at void de.robv.android.xposed.XposedInit.hookResources() (XposedInit.java:249)
01-17 12:03:36.705 E/Xposed  (  255):   at void de.robv.android.xposed.XposedBridge.main(java.lang.String[]) (XposedBridge.java:92)
01-17 12:03:36.705 E/Xposed  (  255): Cannot hook resources
01-17 12:03:36.891 E/Xposed  (  255): Cannot load any modules because /data/data/de.robv.android.xposed.installer/conf/modules.list was not found
01-17 12:03:39.822 E/Xposed  (  914): java.lang.IllegalAccessError: android.content.res.XResources
01-17 12:03:39.822 E/Xposed  (  914): 	at de.robv.android.xposed.XposedInit$5.afterHookedMethod(XposedInit.java:200)
01-17 12:03:39.822 E/Xposed  (  914): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:374)
01-17 12:03:39.822 E/Xposed  (  914): 	at android.app.LoadedApk.<init>(<Xposed>)
01-17 12:03:39.822 E/Xposed  (  914): 	at android.app.ContextImpl.createSystemContext(ContextImpl.java:2356)
01-17 12:03:39.822 E/Xposed  (  914): 	at android.app.ActivityThread.getSystemContext(ActivityThread.java:2034)
01-17 12:03:39.822 E/Xposed  (  914): 	at android.app.ActivityThread.attach(ActivityThread.java:5480)
01-17 12:03:39.822 E/Xposed  (  914): 	at android.app.ActivityThread.systemMain(ActivityThread.java:5531)
01-17 12:03:39.822 E/Xposed  (  914): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
01-17 12:03:39.822 E/Xposed  (  914): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
01-17 12:03:39.822 E/Xposed  (  914): 	at android.app.ActivityThread.systemMain(<Xposed>)
01-17 12:03:39.822 E/Xposed  (  914): 	at com.android.server.SystemServer.createSystemContext(SystemServer.java:399)
01-17 12:03:39.822 E/Xposed  (  914): 	at com.android.server.SystemServer.run(SystemServer.java:325)
01-17 12:03:39.822 E/Xposed  (  914): 	at com.android.server.SystemServer.main(SystemServer.java:236)
01-17 12:03:39.822 E/Xposed  (  914): 	at java.lang.reflect.Method.invoke(Native Method)
01-17 12:03:39.822 E/Xposed  (  914): 	at java.lang.reflect.Method.invoke(Method.java:372)
01-17 12:03:39.822 E/Xposed  (  914): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
01-17 12:03:39.822 E/Xposed  (  914): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
01-17 12:03:39.822 E/Xposed  (  914): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
01-17 12:03:52.491 E/Xposed  (  914): java.lang.IllegalAccessError: android.content.res.XResources
01-17 12:03:52.491 E/Xposed  (  914): 	at de.robv.android.xposed.XposedInit$5.afterHookedMethod(XposedInit.java:200)
01-17 12:03:52.491 E/Xposed  (  914): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:374)
01-17 12:03:52.491 E/Xposed  (  914): 	at android.app.LoadedApk.<init>(<Xposed>)
01-17 12:03:52.491 E/Xposed  (  914): 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1974)
01-17 12:03:52.491 E/Xposed  (  914): 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1935)
01-17 12:03:52.491 E/Xposed  (  914): 	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1907)
01-17 12:03:52.491 E/Xposed  (  914): 	at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2282)
01-17 12:03:52.491 E/Xposed  (  914): 	at android.app.ContextImpl.createPackageContext(ContextImpl.java:2269)
01-17 12:03:52.491 E/Xposed  (  914): 	at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:671)
01-17 12:03:52.491 E/Xposed  (  914): 	at android.app.ActivityThread.installProvider(ActivityThread.java:5310)
01-17 12:03:52.491 E/Xposed  (  914): 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4911)
01-17 12:03:52.491 E/Xposed  (  914): 	at android.app.ActivityThread.installSystemProviders(ActivityThread.java:5537)
01-17 12:03:52.491 E/Xposed  (  914): 	at com.android.server.am.ActivityManagerService.installSystemProviders(ActivityManagerService.java:10878)
01-17 12:03:52.491 E/Xposed  (  914): 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:610)
01-17 12:03:52.491 E/Xposed  (  914): 	at com.android.server.SystemServer.run(SystemServer.java:335)
01-17 12:03:52.491 E/Xposed  (  914): 	at com.android.server.SystemServer.main(SystemServer.java:236)
01-17 12:03:52.491 E/Xposed  (  914): 	at java.lang.reflect.Method.invoke(Native Method)
01-17 12:03:52.491 E/Xposed  (  914): 	at java.lang.reflect.Method.invoke(Method.java:372)
01-17 12:03:52.491 E/Xposed  (  914): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
01-17 12:03:52.491 E/Xposed  (  914): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
01-17 12:03:52.491 E/Xposed  (  914): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
01-17 12:03:52.842 E/Xposed  (  914): java.lang.IllegalAccessError: android.content.res.XResources
01-17 12:03:52.842 E/Xposed  (  914): 	at de.robv.android.xposed.XposedInit$6.beforeHookedMethod(XposedInit.java:222)
01-17 12:03:52.842 E/Xposed  (  914): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
01-17 12:03:52.842 E/Xposed  (  914): 	at android.app.ApplicationPackageManager.getResourcesForApplication(<Xposed>)
01-17 12:03:52.842 E/Xposed  (  914): 	at android.app.ApplicationPackageManager.getXml(ApplicationPackageManager.java:1200)
01-17 12:03:52.842 E/Xposed  (  914): 	at android.content.pm.PackageItemInfo.loadXmlMetaData(PackageItemInfo.java:279)
01-17 12:03:52.842 E/Xposed  (  914): 	at android.view.inputmethod.InputMethodInfo.<init>(InputMethodInfo.java:145)
01-17 12:03:52.842 E/Xposed  (  914): 	at com.android.server.InputMethodManagerService.buildInputMethodListLocked(InputMethodManagerService.java:2790)
01-17 12:03:52.842 E/Xposed  (  914): 	at com.android.server.InputMethodManagerService.<init>(InputMethodManagerService.java:750)
01-17 12:03:52.842 E/Xposed  (  914): 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:693)
01-17 12:03:52.842 E/Xposed  (  914): 	at com.android.server.SystemServer.run(SystemServer.java:335)
01-17 12:03:52.842 E/Xposed  (  914): 	at com.android.server.SystemServer.main(SystemServer.java:236)
01-17 12:03:52.842 E/Xposed  (  914): 	at java.lang.reflect.Method.invoke(Native Method)
01-17 12:03:52.842 E/Xposed  (  914): 	at java.lang.reflect.Method.invoke(Method.java:372)
01-17 12:03:52.842 E/Xposed  (  914): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
01-17 12:03:52.842 E/Xposed  (  914): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
01-17 12:03:52.842 E/Xposed  (  914): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
01-17 12:03:52.851 E/Xposed  (  914): java.lang.IllegalAccessError: android.content.res.XResources
01-17 12:03:52.851 E/Xposed  (  914): 	at de.robv.android.xposed.XposedInit$6.beforeHookedMethod(XposedInit.java:222)
01-17 12:03:52.851 E/Xposed  (  914): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
01-17 12:03:52.851 E/Xposed  (  914): 	at android.app.ApplicationPackageManager.getResourcesForApplication(<Xposed>)
01-17 12:03:52.851 E/Xposed  (  914): 	at android.view.inputmethod.InputMethodInfo.<init>(InputMethodInfo.java:151)

content://com.google.android.apps.docs.storage.legacy/enc%3DEGpSvwTAOfk9mv7LhDnolclwOuukRGZcBdCaYWeljoMf3Ydf%0A

**Comment by dimitrinanos** [comment]
Any solution?
