### ISSUE TITLE
Xposed v90 beta breaks camera

### ISSUE THREAD

**Issue by ghost** [rovo89/Xposed#321]
**Device:** Motorola Moto G5 Plus, (potter) (model XT1687)
**ROM:** Pixel Experience (Android 8.1), build date 20180117
**Xposed version:** v90, beta 1 and beta 2
**Description of issue:** Whenever I enter any camera app, the viewfinder is black. I cannot click the shutter button or take any pictures.
**How I've tried to resolve:**
-Disabling all modules
-Reinstalling Xposed
-Clearing cache/Dalvik
-Force-closing and clearing app data of camera apps
**Steps to reproduce:** Install Xposed v90 for SDK27 (any beta) on an Android 8.1 ROM, then open any camera app.
**Logs:** [log.txt](https://github.com/rovo89/Xposed/files/1662522/log.txt)

Just wanted to post this before the new Xposed becomes final. Thanks for all your work rovo!

**Comment by faiyazsheth** [comment]
you should be fine with latest builds of roms. you can close this issue.
