### ISSUE TITLE
xposed beta 3 samsung oreo, error

### ISSUE THREAD

**Issue by Ansuel** [rovo89/Xposed#329]
have this error... 
02-16 14:45:03.410 E/Xposed  ( 3750): java.lang.ClassNotFoundException: android.app.ApplicationThreadProxy
02-16 14:45:03.410 E/Xposed  ( 3750): 	at java.lang.Class.classForName(Native Method)
02-16 14:45:03.410 E/Xposed  ( 3750): 	at java.lang.Class.forName(Class.java:453)
02-16 14:45:03.410 E/Xposed  ( 3750): 	at me.piebridge.prevent.xposed.a.e(SystemServiceHook.java:418)
02-16 14:45:03.410 E/Xposed  ( 3750): 	at me.piebridge.prevent.xposed.a.afterHookedMethod(SystemServiceHook.java:72)
02-16 14:45:03.410 E/Xposed  ( 3750): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:375)
02-16 14:45:03.410 E/Xposed  ( 3750): 	at android.app.ActivityThread.systemMain(<Xposed>)
02-16 14:45:03.410 E/Xposed  ( 3750): 	at com.android.server.SystemServer.createSystemContext(SystemServer.java:779)
02-16 14:45:03.410 E/Xposed  ( 3750): 	at com.android.server.SystemServer.run(SystemServer.java:662)
02-16 14:45:03.410 E/Xposed  ( 3750): 	at com.android.server.SystemServer.main(SystemServer.java:543)
02-16 14:45:03.410 E/Xposed  ( 3750): 	at java.lang.reflect.Method.invoke(Native Method)
02-16 14:45:03.410 E/Xposed  ( 3750): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
02-16 14:45:03.410 E/Xposed  ( 3750): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
02-16 14:45:03.410 E/Xposed  ( 3750): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
02-16 14:45:03.410 E/Xposed  ( 3750): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.ApplicationThreadProxy" on path: DexPathList[[zip file "/system/framework/services.jar", zip file "/system/framework/ethernet-service.jar", zip file "/system/framework/wifi-service.jar", zip file "/system/framework/samsung-services.jar", zip file "/system/framework/hqm.jar", zip file "/system/framework/dmf.jar", zip file "/system/framework/ssrm.jar"],nativeLibraryDirectories=[/system/lib64, /system/vendor/lib64, /system/lib64, /system/vendor/lib64]]
02-16 14:45:03.410 E/Xposed  ( 3750): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
02-16 14:45:03.410 E/Xposed  ( 3750): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
02-16 14:45:03.410 E/Xposed  ( 3750): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
02-16 14:45:03.410 E/Xposed  ( 3750): 	... 13 more

**Comment by rovo89** [comment]
That's a problem in the module me.piebridge.prevent module, please contact the module author.
