### ISSUE TITLE
Android 5.1

### ISSUE THREAD

**Issue by menghivan** [rovo89/Xposed#33]
hi, i have a nexus 5 with Android 5.1 with root, which version works of Xposed ?? 
thank you

**Comment by Programming4life** [comment]
None please read other issues before posting. There is already a issue started talking about this.

**Comment by menghivan** [comment]
Excuse me, I do not know English well andnot lho noticed ...

**Comment by StephenBrown2** [comment]
Specifically Issue #30 , for reference.
