### ISSUE TITLE
Slow boot with Xposed installed

### ISSUE THREAD

**Issue by Y-T-G** [rovo89/Xposed#330]
Device: SPH-L720
Android Version: 8.1
ROM: AOSP
Xposed Version: v90.1-beta3(Issue also present in previous version for SDK 27)

Without Xposed, it takes less than 15 seconds to boot. But with Xposed it takes around a minute and half.
Attached the log.
[logcat.txt](https://github.com/rovo89/Xposed/files/1736815/logcat.txt)
[logcatWithoutXposed.txt](https://github.com/rovo89/Xposed/files/1736858/logcatWithoutXposed.txt)

**Comment by agushermansyah621** [comment]
Mohon bantuan ya
