### ISSUE TITLE
The module is hidden from the repository. Only moderators can edit this module at the moment.

### ISSUE THREAD

**Issue by KaLui** [rovo89/Xposed#334]
I have a xposed module that is hidden and what I need to do. Thanks.（http://repo.xposed.info/）

**Comment by sanshao27** [comment]
@rovo89 I also have such a problem, how to solve?


Thanks.

**Comment by rovo89** [comment]
Please use the contact form, choose "need help managing my own module" and mentioned which module this affects. Probably it violated the terms of service.
