### ISSUE TITLE
service.jar for 47.1.A.12.119-R9B

### ISSUE THREAD

**Issue by klcb2010** [rovo89/Xposed#353]
the service.jar  come from Sony XZ Premium  47.1.A.12.145, edit by Beetle84，it work for xposed on 47.1.A.12.119.

[services.jar.zip](https://github.com/rovo89/Xposed/files/1930096/services.jar.zip)

**Comment by li0nh3art3d** [comment]
this file will fix it?

**Comment by klcb2010** [comment]
![screenshot_20180420-082027](https://user-images.githubusercontent.com/32628414/39024474-c02ab446-4473-11e8-8775-e11af3722258.png)
![screenshot_20180420-082017](https://user-images.githubusercontent.com/32628414/39024481-c79cc73c-4473-11e8-9bff-cad72483ab00.png)yes it work on my XZ Premium Dual (G8142) 119

**Comment by klcb2010** [comment]
You should flash Magisk，then flash xposed，reboot，then copy it to system/framework，If you are lucky, you won't bootloop

**Comment by li0nh3art3d** [comment]
how did you downgrade the baseband from 47.1.A.12.145 to 47.1.A.12.119 ?

so the newer update services.jar fixes it? I'm confused.

I have the XA2, and my services.jar file is very different. I have a TWRP backup of the older firmware, I am going to test it.. But I was unable to downgrade the baseband, only the bootloader and the rest of the firmware. The baseband version stays newer when flashing the older firmware, resulting in bootloop

EDIT: ahh, you are on LOS15 correct?

**Comment by klcb2010** [comment]
you need edit from XA2，not downgrade the baseband，just use service of 145 on119  Stock firmware

**Comment by li0nh3art3d** [comment]
I will try it on the XA2... but my firmware is 50.1.A.5.59

**Comment by klcb2010** [comment]
you need edit from XA2

**Comment by klcb2010** [comment]
refer to https://forum.xda-developers.com/showpost.php?p=68001053&postcount=2
