### ISSUE TITLE
PLEASE HELP

### ISSUE THREAD

**Issue by timea-techgirl** [rovo89/Xposed#356]
Device: Nexus 5 running marshmallow and xposed 89

My xposed log is being spammed by some app's error or crash. I can't find the rogue app. Xposed log keeps growing by the minute and it has impacted my battery life. I've attached the log here. Please someone help asap.

Here's some of the log.

[error.log](https://github.com/rovo89/Xposed/files/1965790/error.log)

**Comment by rovo89** [comment]
Incompatible modules are usually pretty easy to find, just look at the crashes:
```
05-02 07:48:06.002 E/Xposed  (10009): de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.google.android.finsky.detailscomponents.DetailsTextBlock
05-02 07:48:06.002 E/Xposed  (10009): 	at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:71)
05-02 07:48:06.002 E/Xposed  (10009): 	at ---> com.p1ngu1n.playstorechangelog <--- .PlayStoreChangelog.handleLoadPackage(PlayStoreChangelog.java:72)
```

```
05-02 07:52:33.209 E/Xposed  ( 1894): java.lang.NoSuchFieldError: com.android.systemui.recents.views.TaskViewThumbnail#mTask
05-02 07:52:33.209 E/Xposed  ( 1894): 	at de.robv.android.xposed.XposedHelpers.findField(XposedHelpers.java:116)
05-02 07:52:33.209 E/Xposed  ( 1894): 	at de.robv.android.xposed.XposedHelpers.getObjectField(XposedHelpers.java:894)
05-02 07:52:33.209 E/Xposed  ( 1894): 	at ---> de.Maxr1998.xposed.maxlock <--- .hooks.SystemUI$1.afterHookedMethod(Unknown Source)
```

In doubt, just disable all modules and re-enable them one by one until the crashes come back.

**Comment by timea-techgirl** [comment]
It just started yesterday. Until yesterday everything was fine. I don't know what happened. There haven't been any updates to modules or any changes on my phone. So, I don't know why suddenly it started.

**Comment by Kronopt** [comment]
playstorechangelog hasn't been updated in a while, and as the playstore usually updates silently, you won't even notice something is different.

**Comment by timea-techgirl** [comment]
@Kronopt Yes, I know about play store and services silently updating. I removed play store changelog module but there is still no explanation for other apps crashing.

**Comment by Dark1z** [comment]
> **Kronopt** Yes, I know about play store and services silently updating. I removed play store changelog module but there is still no explanation for other apps crashing.   

@malitech ,   
You also have crash for `de.Maxr1998.xposed.maxlock` as pointed out by **rovo89** ,
I think the Xposed Mod name is `MaxLock`.

Best regards 👍

**Comment by timea-techgirl** [comment]
@dark-1 I know what apps are crashing. I don't know why suddenly all apps started crashing because there aren't any changes on my phone.

**Comment by Dark1z** [comment]
> @dark-1 I know what apps are crashing. I don't know why suddenly all apps started crashing because there aren't any changes on my phone.   

@malitech ,   
That no-one will be able to tell, as said by **Kronopt**  there can be changes that u did not noticed.

BR 👍
