### ISSUE TITLE
This is the run log feedback. Xposed-v90-Beta2-SDK26-ARM64 can work on Xiaomi Mi 5 (Gemini) with MiUi 10-8.9.20 (based on Android Oreo 8.0.0), but not very well.

### ISSUE THREAD

**Issue by Zerorigin** [rovo89/Xposed#384]
Hey, @rovo89 .
Thank you for your dedication to xposed. 
It is a special gift to all xposed users, and nothing can replace it.

This is the run log feedback.
Xposed-v90-Beta2-SDK26-ARM64 can work on Xiaomi Mi 5 (Gemini) with MiUi 10-8.9.20 (based on Android Oreo 8.0.0), but not very well.
　
```
Starting Xposed version 90-beta2, compiled for SDK 26
Device: MI 5 (Xiaomi), Android version 8.0.0 (SDK 26)
ROM: OPR1.170623.032
Build fingerprint: Xiaomi/gemini/gemini:8.0.0/OPR1.170623.032/8.9.20:user/release-keys
Platform: arm64-v8a, 64-bit binary, system server: yes
SELinux enabled: yes, enforcing: yes
```
　 
Logs: [Click to download LogCat](https://nx.gazer.win:6587/s/x3jSJmPqG42oGm6)
Passwd: Xposed6587

**Comment by Zerorigin** [comment]
@rovo89 @M66B @romracer @jclehner

**Comment by Mikanoshi** [comment]
Have you tried on MIUI 9 or 10 Stable? Every single beta I tried on them bootloops because of this crash:
https://github.com/rovo89/Xposed/issues/317#issuecomment-359238258
I use systemless though.

P.S. Your link cannot be opened in Firefox BTW, "an error occurred during a connection to nx.gazer.win:6587. SSL peer rejected a handshake message for unacceptable content. Error code: SSL_ERROR_ILLEGAL_PARAMETER_ALERT"

**Comment by Zerorigin** [comment]
Hey, @Mikanoshi . 
Both MIUI 9 Stable and Weekly Edition for Xiaomi Mi 5 (Gemini) are based on Android Nougat 7.0, and Xposed works very well on it. 
I haven't tried on MIUI 10 Stable, but I can test it and provide the logs.
About the link to download logcat, I can open it normally. I will try to adjust ssl_protocols from “TLSv1.3,TLSv1.2” to "TLSv1.3,TLSv1.2,TLSv1.1", after then you can try it again.

**Comment by Mikanoshi** [comment]
Only if MIUI 10 is on 8.0, 7.0 is of no interest to me :)

Why no TLSv1 and TLSv1.1? Anyway, FF supports 1.2, so maybe it's ssl_ciphers.

**Comment by Zerorigin** [comment]
>           Only if MIUI 10 is on 8.0, 7.0 is of no interest to me :)
> Why no TLSv1 and TLSv1.1? Anyway, FF supports 1.2, so maybe it's ssl_ciphers.

emm...
It's my private cloud disk, so I don't think it's necessary to provide TLSv1.1 and TLSv1 support.
I can open it normally with FF62/IE11/Edge42/Chrome69, I don't know what happened.
I have adjusted ssl_ciphers by the way. You can try it again.

**Comment by Zerorigin** [comment]
@Mikanoshi @rovo89 
I have tested it that Xposed-v90-Beta2-SDK26-ARM64 can works on Xiaomi Mi 5 (Gemini) with MIUI 10 Stable, but also not very well. This is the run logs.

Logs: [Click to download LogCat](https://nx.gazer.win:6587/s/nW5pKMZrXM3mMBG)
Passwd: Xposed6587

**Comment by Zerorigin** [comment]
@Mikanoshi 

I've shared the logs with OneDrive.
https://1drv.ms/f/s!Ap8FpugA1tSmt0n2eTMt3EP0RTbK

**Comment by Mikanoshi** [comment]
Second link is without port, so does not connect.
And what does "not very well" mean? :)

**Comment by Zerorigin** [comment]
>           Second link is without port, so does not connect.
> And what does "not very well" mean? :)

emm...
Sorry, I forgot to add the port.

"not very well" mean :
Can works, but Xposed logs prompt “Could not determine canonical path...” and “Failed to generate Xposed info...”.
System.UI occasionally black screen (and not responding) or frozen screen.
System runs slowly than MIUI9 (based on Android 7.0 Nougat) with Xposed.
