### ISSUE TITLE
Samsung S8+ lockscreen

### ISSUE THREAD

**Issue by oemdump** [rovo89/Xposed#393]
Hi, I have installed beta3 on my S8 Plus. Have swipe screen lock activated. All works OK **till I receive SMS message while my phone is locked and screen off**. It's impossible to unlock. Screen turns on just for breaf moment and goes off so fast, I can't unlock. I tried locking with fingerprint, pin or pattern, always same issue. With bixby button I somehow manage to unlock finally, going through several systemui FC. 
I'm on O 8.0.

**Comment by eebssk1** [comment]
Use adb on your computer to get the log when it happens so others can help you.

**Comment by oemdump** [comment]
Can't get log before christmas holidays when i'm home from college and using my own computer.

**Comment by oemdump** [comment]
Solved, it was Firefds Kit causing it.

**Comment by alialooooosh055455** [comment]
Ok
