### ISSUE TITLE
Can xposed run without root, while flash framework in recovery

### ISSUE THREAD

**Issue by huhuang03** [rovo89/Xposed#397]
In theory, can xposed run with out root? While flash xposed framework in recovery mode.

I try this on a no root phone, I flash xposed framewordk success, but my phone stock at startup screen. And there's no log in `/data/user_de/0/de.robv.android.xposed.installer/log` and `/data/data/de.robv.android.xposed.installer/`.

Maybe some step I was wrong, or xposed can't run with no root? Because If I root my phone, everything goes fine.

**Comment by ghost** [comment]
Yes, of course
