### ISSUE TITLE
xposed框架已安装但未激活，日志中找不到根目录/data/user/0/rovo.****.xposed.com/log/error.log文件，创建error.log无效

### ISSUE THREAD

**Issue by rebeleder** [rovo89/Xposed#417]

**Comment by shatian114** [comment]
> _No description provided._

你确定作者懂中文？

**Comment by eebssk1** [comment]
而且项目早就弃了

**Comment by liupeng110** [comment]
进入/data/user/0/rovo.****.xposed.com/  文件夹权限重新设置下就可以了

**Comment by liupeng110** [comment]
安卓8.0 还可以用的。

**Comment by liupeng110** [comment]
@shatian114  @eebssk1    废弃了，你们用的什么

**Comment by eebssk1** [comment]
8.1不怕bug可以用原版，9.0以上我用的EdXposed

**Comment by shatian114** [comment]
> @shatian114 @eebssk1 废弃了，你们用的什么

我用的8.0，虽然是beta版

**Comment by rebeleder** [comment]
> 安卓8.0还可以用的。

useless

**Comment by jojolfy** [comment]
> 进入/data/user/0/rovo.****.xposed.com/ 文件夹权限重新设置下就可以了

请问权限设置成什么？
