### ISSUE TITLE
LG G3s (D722) Lollipop: com.android.phone crashes with Xposed installed

### ISSUE THREAD

**Issue by ThePietn1** [rovo89/Xposed#42]
When the Xposed framework is installed on the LG G3s, calling isn't working anymore. Every second or two, there is a popup with the message that "com.android.phone has stopped". I have confirmed with a few other G3s owners to confirm this issue, it also happens to them

To reproduce this problem, dalvik-cache needs to be cleared from recovery. Not clearing the dalvik cache makes the phone work, but incredibly slow and also with the "low storage" problem. It seems like the dalvik-cache isn't recreated correctly with the Xposed framework installed, the folder (/data/dalvik-cache) gets way bigger than without Xposed. Also with Xposed there are 135 apps to be optimized, on the same system setup without Xposed there are only 49 apps to be optimized.

I do have an Xposed log file and also a logcat file, I hope it's useful for finding the problem.
Xposed log file: http://pastebin.com/Webt1f4P
Logcat (too big for pastebin): https://mega.co.nz/#!wBAFFDQL!h_Uor7Laopc-Uc1jAKQzEFFRmj7O0QTjGlspVZ0tgyc

Btw: the issue with LGWeather and LGCover also applies for the G3s, but that's of less priority for our device in my opinion. Before installing the framework, I deleted both apps. In that way the logs shouldn't be spammed with the problems those apps cause.

**Comment by rovo89** [comment]
Errors I could find in the logs:
```
05-14 12:03:09.958 F/libc    ( 1986): Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc in tid 1986 (main)
05-14 12:03:10.045 I/DEBUG   (  277): [2015-05-14 12:03:10.045]
05-14 12:03:10.045 I/DEBUG   (  277): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-14 12:03:10.045 I/DEBUG   (  277): Build fingerprint: 'lge/jagnm_global_com/jagnm:5.0.2/LRX22G.A1428918170/151031842f939:user/release-keys'
05-14 12:03:10.046 I/DEBUG   (  277): Revision: '6'
05-14 12:03:10.046 I/DEBUG   (  277): ABI: 'arm'
05-14 12:03:10.046 I/DEBUG   (  277): pid: 1986, tid: 1986, name: main  >>> /system/bin/dex2oat <<<
05-14 12:03:10.046 I/DEBUG   (  277): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc
05-14 12:03:10.063 I/DEBUG   (  277):     r0 00000000  r1 00000095  r2 00000001  r3 0000000f
05-14 12:03:10.063 I/DEBUG   (  277):     r4 b5c6d3e0  r5 b5c720a0  r6 00000001  r7 b6f40018
05-14 12:03:10.063 I/DEBUG   (  277):     r8 be9ec1cc  r9 b6f40014  sl 00000000  fp be9ec3b8
05-14 12:03:10.063 I/DEBUG   (  277):     ip b6f3feec  sp be9ec178  lr b6f35c19  pc b6d7b488  cpsr 200b0030
05-14 12:03:10.064 I/DEBUG   (  277): 
05-14 12:03:10.064 I/DEBUG   (  277): backtrace:
05-14 12:03:10.064 I/DEBUG   (  277):     #00 pc 00201488  /system/lib/libart.so
05-14 12:03:10.064 I/DEBUG   (  277):     #01 pc 00020378  [stack]
05-14 12:03:10.105 I/DEBUG   (  277): 
05-14 12:03:10.105 I/DEBUG   (  277): Tombstone written to: /data/tombstones/tombstone_00
05-14 12:10:48.519 F/libc    ( 2469): Fatal signal 11 (SIGSEGV), code 2, fault addr 0x80db9080 in tid 2471 (Compiler driver)
05-14 12:10:48.520 F/libc    ( 2469): Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc in tid 2473 (Compiler driver)
05-14 12:10:48.670 E/DEBUG   (  277): unexpected waitpid response: n=2473, status=0000000b
```

```
java.lang.VerifyError: Rejecting class com.lge.gons.Gons because it failed compile-time verification (declaration of 'com.lge.gons.Gons' appears in /system/framework/telephony-common.jar)
	at com.android.internal.telephony.RIL$1.onReceive(RIL.java:578)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1034)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5376)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
``` 

Things to be checked:
- Which function is at 0x201488 in libart.so?
- How exactly is dex2oat called so it crashes (which command line arguments)?
- Is this reproducable by calling the same command again (possibly with a different target filename)?

If it is reproducable, maybe I can try this on my own device.

**Comment by ThePietn1** [comment]
Too bad I am quite a noob for these things, I have no idea how to check those things you said. However, I can give you a copy of the libart.so file of the LG G3s, I'm not sure if it's exactly the same as the one in stock AOSP. If there is anything else I can help with, feel free to tell me (don't expect too much of me, this is only a little easier than Chinese to me).

libart.so: https://mega.co.nz/#!4dwiACbL!tvzW7jPx0GKtbW8A_spltL6B0MZWWhTtM0sWugKcggE

**Comment by duki994** [comment]
Hmmm....
Too bad I removed Xposed on my G2 Lollipop (very similar software/ROM as G3 Lollipop). Had no problems with calling (and afaik G3 and G2 have same phone app and similar, if not same RIL libs)


Had a lot of SIGSEGV errors in libc with Xposed on my G2, mostly in (main) and (Compiler driver).
Those in (main) knew to reboot my device from time to time.

I don't really know what in userspace can make these segmentation fault errors, I'm more kernel guy.


I can confirm much bigger dex cache.




When time allows me, I'll install Xposed again, test and report logs :)

**Comment by rovo89** [comment]
> Also with Xposed there are 135 apps to be optimized, on the same system setup without Xposed there are only 49 apps to be optimized.

The remaining ones might be system apps and other stuff that is precompiled on odex'ed ROMs. Usually, these files can be used as they are, without recompiling and without needing additional space. But due to some of the optimizations done by ART, hooks would work unreliably, so Xposed has to force recompiling everything with a few optimizations less than usual. That's why more apps need to be (re-)compiled, and that obviously needs storage space. I wouldn't say it's a feature, but it's a necessity.


Regarding these crashes: Do you still experience them? If yes, can you get a logcat directly from the boot attempt directly after clearing the Dalvik cache? That's probably when those errors occur. And could you send me your `/system/framework/telephony-common.jar` and `telephony-common.odex` (might be in a subfolder)?

**Comment by ThePietn1** [comment]
Yes the crashes are not gone yet, it is still impossible to run Xposed on our device with stock lollipop and working telephony. This logcat starts at boot and ends a bit after all the apps were optimized and started, I hope it's good: https://mega.co.nz/#!YV4lDD4Y!9OIZRp5vN1WUNvkLsJOX2QNbj2NHw214YCk_LRLz8YU

As for the telephony-common.jar, here is the file: https://mega.co.nz/#!cMYTnQ5K!wyg-yEpP_Lu2J6J1C3bExqTOg2BRd90uWTKCpMjOVVQ

I searched through all subfolders of system, but I could not find any telephony-common.odex file. I guess there is none on our device, is that possible?

**Comment by rovo89** [comment]
> I searched through all subfolders of system, but I could not find any telephony-common.odex file. I guess there is none on our device, is that possible?

Hm, I don't think so... isn't there a subfolder `/system/framework/arm` in which this file could be located?

**Comment by Zackptg5** [comment]
If it helps at all, this issue is not present in the verizon lg g2 lollipop

**Comment by Exigoss** [comment]
That file is right under telephony-common.jar, in system/framework folder (at least on kitkat)

**Comment by ThePietn1** [comment]
In both of those folders I had no luck finding that file, I decided to zip the full /system/framework folder so you guys can see. As you can see there is no such file present, I have no idea why that is unfortunately. Link: https://mega.nz/#!VRpGCJpY!or4Stsph43QNU7yiam8ynrMqIFZebwVSnFecKI83MM8

Also I can confirm the bugs persists on the newest Xposed update, which is probably expected. I just tried it out because you never know if some magic happened to it. ;)

**Comment by Uszkix** [comment]
Any news for Xposed on this device?

**Comment by steffenbakke** [comment]
Can confirm this also happens on LG G2 Mini running the latest lollipop

**Comment by relaxxx** [comment]
this bug exists while wifi has switched on. maybe this will help.
this is my logcat: https://www.dropbox.com/s/5t477k8epwjxo1t/logcat.txt?dl=0

**Comment by Uszkix** [comment]
When wifi will be swiched off we install xposed framework without any bugs?

**Comment by Rorroywea** [comment]
I searched telephony-common.odex in /system too but like ThePietn1 i had no luck, the file really does no exist in 5.0.2

**Comment by rovo89** [comment]
That's ok, I meanwhile found out that the file is part of boot.oat. I can reproduce the cause for this issue by recompiing boot.oat on my emulator. A few classes are rejected because single statements fail to be verified. Those statements are "invoke-virtual-quick", which can only appear in optimized dex code. It works for most of them, but for some, e.g. the number of parameters isn't correct. I have yet to find out whether the code in the file is incorrect or whether it's an issue with ART...

**Comment by Uszkix** [comment]
Hi. I find telephony.common.jar but I can not find .odex. I search in /system/framework/arm too. https://drive.google.com/file/d/0B3tJagBJsBmmMl9VVE9xN0ViX3M/view?usp=docslist_api

**Comment by rovo89** [comment]
Could you please test this? https://www.dropbox.com/s/ac9rz6sriv5gsrj/xposed-v68-sdk21-arm-debug1.zip?dl=0
You'll have to clear the Dalvik cache after flashing this ZIP to ensure that the failing class is recompiled.

**Comment by Themref** [comment]
Still not working. Problem with quick circle, also problems wit 'process com.android.systemui has stopped' :P I've got rom v20c for UK and kernel Bread and Butter v4

**Comment by relaxxx** [comment]
installed v68 debug version, and till now it seems working fine. i have g2 mini (d620r) with stock rom and kernel

**Comment by Uszkix** [comment]
I must freeze lgweather and lgsmartcover for v68?

**Comment by rovo89** [comment]
Please don't confuse this with the issue that LG's encrypted apps like weather and smart cover crash, That's a different issue and is unlikely to be fixed, at least until someone provides a well-documented way to decrypt those apps. The quick circle and system UI crashes might be related to that.

This issue is about the crashing phone process in combination with WiFi on. So this seems to be fixed then, according to @relaxxx?

**Comment by relaxxx** [comment]
after a few hours usage i can confirm, that this bug is fixed. thank you much @rovo89

**Comment by Uszkix** [comment]
I freeze applications LG by greenify?

**Comment by Uszkix** [comment]
Okay I tested this framework and WORKS FINE on D722! Thanks a lot for your hard work.

**Comment by Rorroywea** [comment]
Works fine here too, weather and smartcover crashes but once these are disabled all works good, include the phone process. Thanks rovo89!!!

**Comment by ThePietn1** [comment]
I can also confirm the issue has been fixed by installing the version you provided. Well done, now we can also enjoy the greatness of Xposed on our device! :)

**Comment by steffenbakke** [comment]
Not working on LG G2 mini - lollipop

**Comment by rovo89** [comment]
Have you cleared the Dalvik cache after flashing the new framework v69? If yes, please provide a logcat.

**Comment by steffenbakke** [comment]
I have indeed, I'll do a backup and then try again and provide logs, need the apps too? And liblgalmond.so?

**Comment by duki994** [comment]
Steffen, you have 5.0.2?

LG has mostly same kernel and ROM sources for MSM89xx SoC's with only few
drivers changed to match specific SoC.

Look in logcat if ART is showing failed loading of liblgalmond.so

You can try lib from G2 or G3 :)

**Comment by steffenbakke** [comment]
"

[ 08-04 17:51:23.537  1270: 1342 W/ActivityManager ]

Timeout executing service: ServiceRecord{162d4552 u0 com.lge.smartcover/.SmartCoverViewManagerService}



[ 08-04 17:51:23.587  1270: 1342 I/ActivityManager ]

Crashing app skipping ANR: ProcessRecord{18c4fb35 4885:com.lge.smartcover/u0a19} Executing service com.lge.smartcover/.SmartCoverViewManagerService



[ 08-04 17:51:23.587  1270: 1342 W/ActivityManager ]

Timeout executing service: ServiceRecord{162d4552 u0 com.lge.smartcover/.SmartCoverViewManagerService}



[ 08-04 17:51:23.587  1270: 1342 I/ActivityManager ]

Crashing app skipping ANR: ProcessRecord{18c4fb35 4885:com.lge.smartcover/u0a19} Executing service com.lge.smartcover/.SmartCoverViewManagerService



[ 08-04 17:51:23.587  1270: 1342 W/ActivityManager ]

Timeout executing service: ServiceRecord{162d4552 u0 com.lge.smartcover/.SmartCoverViewManagerService}



[ 08-04 17:51:23.587  1270: 1342 I/ActivityManager ]

Crashing app skipping ANR: ProcessRecord{18c4fb35 4885:com.lge.smartcover/u0a19} Executing service com.lge.smartcover/.SmartCoverViewManagerService



[ 08-04 17:51:23.587  1270: 1342 W/ActivityManager ]

Timeout executing service: ServiceRecord{162d4552 u0 com.lge.smartcover/.SmartCoverViewManagerService}



[ 08-04 17:51:23.587  1270: 1342 I/ActivityManager ]

Crashing app skipping ANR: ProcessRecord{18c4fb35 4885:com.lge.smartcover/u0a19} Executing service com.lge.smartcover/.SmartCoverViewManagerService
"
Full logcat is at
https://paste.ee/r/uOaVa
Hope it helps

**Comment by rovo89** [comment]
`Failed to open file '/data/dalvik-cache/arm/system@priv-app@LGCover@LGCover.apk@classes.dex': Permission denied`
`Failed to open file '/data/dalvik-cache/arm/system@app@LGWeather@LGWeather.apk@classes.dex': Permission denied`

It seems that either the recompiliation still didn't work or that this file wasn't deleted when you cleared the Dalvik cache.

The apps and liblgalmond.so (locations mentioned above) could be helpful, yes. Is the lib located in /system/lib on your device?
And apart from that, it would be good to see how the apps are recompiled on your device:
```
adb root
adb shell rm /data/dalvik-cache/arm/system@priv-app@LGCover@LGCover.apk@classes.dex
adb shell rm /data/dalvik-cache/arm/system@app@LGWeather@LGWeather.apk@classes.dex
adb logcat -v time > logcat.xt
adb shell stop;start (in another window)
(wait until the device has booted, then press Ctrl+C for the logcat)
```

**Comment by steffenbakke** [comment]
The lib is indeed located there. 
Tried deleting the .dex files, with the response they did not exist. So dalvik cache seems cleared. 
Here's the requested logcat:
https://paste.ee/r/GWkOo
If this doesnt help I can provide the apps and liblgalmond.so at the time I am back home

**Comment by rovo89** [comment]
`Invalid oat magic for '/system/priv-app/LGCover/arm/LGCover.odex'`

There were no odex files on other ROMs... Could you send me the whole `/system/priv-app/LGCover` folder and the liblgalmond.so file please?

**Comment by steffenbakke** [comment]
https://www.dropbox.com/sh/69fsqqjins6hp1y/AAApp3te2vYJMUYAxSXB6vRua?dl=0
There you go

**Comment by cretu01** [comment]
At https://app.box.com/s/3snrfgdy1iywsao01ot6wdyovg29fagj you can also find (from g2 mini lolipop, maybe the same files) /system/priv-app/LGCover, /system/app/LGWeather, /system/app/LGWeatherService, /system/lib/liblgalmond.so, /system/build.prop, and also my logcat here: https://app.box.com/s/xum08ovxnpo9xm2f26pnkaf1j4t4eq5a, as i noticed you in this xda thread: http://forum.xda-developers.com/showpost.php?p=62177497&postcount=8. i also noticed that the other files (LGcover etc.) from g3 which were uploaded on xda and github didn't have .odex files, so i tried deodexing them. it either failed (JoelDroid tool) or worked and gave FCs (svadev tool).

**Comment by rovo89** [comment]
@steffenbakke @cretu01 Thanks, I have reopened #27, as this issue here is about a different problem on LG devices, not about the encrypted apps. If you have time to test something in about ~9 hours from now, that would be good.
