### ISSUE TITLE
Lg G2 (Verizon) Not Booting - newer than alpha2 (4/30)

### ISSUE THREAD

**Issue by Zackptg5** [rovo89/Xposed#45]
I can't get a log because it doesn't boot but after flashing alpha4, the phone sits at the boot animation. I tried several restarts and let it sit for 10 minutes on the boot animation but it just sits there. I ended up reflashing alpha3 which works fine.

I'm on xdabbeb's stock-based lollipop rom (5.0.2)

**Comment by rovo89** [comment]
Well, without logs, there's nothing I can do... Did you try to get a logcat via adb?

**Comment by rovo89** [comment]
I just realized you wrote alpha 4. I can only support the latest official version, so please try v65.

**Comment by jesssiii** [comment]
Same here with version 65, @rovo89. I'm on the same rom. Here's a link go the recovery log. https://www.dropbox.com/s/eg6ydnw0eqz3h9o/recovery.log?dl=0

**Comment by Zackptg5** [comment]
I mean v65. It's whatever the latest version is

**Comment by rovo89** [comment]
Unfortunately, the recovery.log doesn't contain any usable information, I need a logcat of the bootloop.
It's also surprising for me that you say that alpha3 works, but alpha4 doesn't. As far as I remember, there was just a minimal change: https://github.com/rovo89/android_art/commit/55b5e0b03cdb52329568fa5d92cd381ec8cd70f1

**Comment by Zackptg5** [comment]
I'll try to get and post the logcat later today. I erred in that I have alpha 2, not 3. The version stuff is confusing me so here's what I'm using that works:

Xposed Installer version: 30-alpha2
Xposed framework version: sdk21-arm-20150430

Sorry about the confusion

**Comment by rovo89** [comment]
Ok, there are more commits since April 30... When you try again, please do so without any active modules. I.e. disable all of them in the installer before you flash the new framework. Maybe one of your modules hooks native methods, which wasn't supported before the latest update (v65).

**Comment by Zackptg5** [comment]
Ok, here's what I did:

Disabled all modules
Rebooted back into phone, verified that all was disasbled
Rebooted into TWRP
Cleared cache
Installed xposed v64, reboot
Stuck on boot like before (didn't even get to boot animation this time, guess that was a fluke)
Recorded logcat (logcat2 is with "-v long" option in case it's easier for you to read that way)
http://www.4shared.com/office/VWlBUhRMce/logcat.html
http://www.4shared.com/office/sgh0IwHtba/logcat2.html

Hard reset into TWRP and reflashed xposed 4/30 - booted back into phone (modules still disabled)
Took logcats like before (logcat4 was with "-v long" option:
http://www.4shared.com/office/EXj7Ogdvba/logcat3.html
http://www.4shared.com/office/O89GRJ8Lba/logcat4.html

**Comment by smiledexter** [comment]
LG L90 also boot loop

**Comment by smiledexter** [comment]
Have log

**Comment by smiledexter** [comment]
See boot loop log https://drive.google.com/file/d/0B8Ja1XWxA7b4NVB0ZUZ0TXpxVzQ/view?usp=sharing

**Comment by rovo89** [comment]
Similar error messages also appear in the logs provided by @Zackptg5. It seems that several files weren't installed properly. There are two things I'd like to check:
- Could you provide the output of `adb shell ls -l /system/bin`, `adb shell ls -l /system/lib` and `adb shell ls -l /system/framework`?
- Could you provide the recovery log taken exactly after the installation of the v65 zip? It should at least mention Xposed somewhere.

**Comment by smiledexter** [comment]
OK

**Comment by smiledexter** [comment]
https://drive.google.com/folderview?id=0B8Ja1XWxA7b4fnBHUWx1dW5hMDR6WVFqemNmWllwdEhwMHJSRWhTdUxaZUIwWnpvNDk5WUU&usp=sharing

Shared folder along with files

**Comment by rovo89** [comment]
Thanks, and sorry for the delay. I found messages like this:
`W/app_process32_x( 1624): type=1400 audit(0.0:710): avc: denied { read } for name="libsigchain.so" dev="mmcblk0p32" ino=98827 scontext=u:r:zygote:s0 tcontext=u:object_r:unlabeled:s0 tclass=file permissive=0`

The file doesn't seem to have any SELinux context. That's a bit strange, because usually, the context should be set automatically by the kernel. It seems that I have to build a special zip file with additional debug output...

**Comment by smiledexter** [comment]
This fix in 66 version?

**Comment by Zackptg5** [comment]
No, as stated in the update on the read only xda thread, there was no change to the framework itself

**Comment by Zackptg5** [comment]
Does CM12 use a stock based kernel? A user reported on the main thread that his d802 on cm12 has the same issue as well

**Comment by smiledexter** [comment]
Stock kernel

**Comment by rovo89** [comment]
As mentioned above:

> The file doesn't seem to have any SELinux context. That's a bit strange, because usually, the context should be set automatically by the kernel. It seems that I have to build a special zip file with additional debug output...

I will create a ZIP file, hopefully tomorrow evening. Most likely, it's some kind of incompatibility between my script, BusyBox and your recovery. But please leave everything as it is, so I can identify the issue.

**Comment by rovo89** [comment]
@Zackptg5 @smiledexter Could anyone of you please send me the recovery.log taken with this ZIP?
https://www.dropbox.com/s/i2vqdljvft5p8gf/xposed-v66-sdk21-arm-debug.zip?dl=0

The files are still the same, but the install script writes some additional debug output.

**Comment by smiledexter** [comment]
OK, please wait.

**Comment by smiledexter** [comment]
recovery.log debug https://drive.google.com/file/d/0B8Ja1XWxA7b4b1YzSVVvdUZBaFk/view?usp=sharing

**Comment by rovo89** [comment]
Thanks! In the log, it says that SELinux is disabled... 
Here's another file to try: https://www.dropbox.com/s/hdax2yjge7k0xrn/xposed-v66-sdk21-arm-debug2.zip?dl=0
It doesn't try to place the files, so you shouldn't need to create another backup.

Btw, 179 watch this repository and get emails for every comment here. So please avoid comments like "please wait".

**Comment by smiledexter** [comment]
recovery.log debug2 https://drive.google.com/file/d/0B8Ja1XWxA7b4Vl9lYjJSQi1hckk/view?usp=sharing

**Comment by Zackptg5** [comment]
Not sure if this will help diagnose the issue or not, but I tried dorimanx's kernel which is known to work with v65/66 and sure enough, it did. Here's the logcat from it with v66.

http://www.4shared.com/office/jzVQSo-vba/logcat-dorimanx.html

**Comment by rovo89** [comment]
`D/SuperSU][APK( 7056): [SuperSU][APK][Installer] selinux_enforcing == 0`
It seems that the other kernel has SELinux disabled or at least not enforced. The files are still not labeled with a, SELinux context, but the ROM doesn't bother.

Anyway, I prefer to fix issues instead of working around them. The second recovery log confirms what I read in the first one: Many things indicate that SELinux is indeed disabled in your recovery. I have checked various things that are usually present, and in your case, they're not there. Even the builtin tools don't seem to support SELinux properly. However, this is contradictory to this log line: `Full SELinux support is present`.

I'll have to look into the details a bit deeper... it seems that chcon doesn't care that SELinux is disabled, only restorecon does. So I'll have to check whether it makes sense to explicitely label all files with chcon, hoping that this will work. I'll upload a new ZIP once I have finished my investigations.

**Comment by rovo89** [comment]
OK, next attempt: https://www.dropbox.com/s/rf0zvc8h9y28tlg/xposed-v66-sdk21-arm-debug3.zip?dl=0
Please let me know if works (with the stock kernel that it previously failed with), and in any case please post the recovery.log.

**Comment by Zackptg5** [comment]
Here's the recovery log
https://www.4shared.com/file/PQgo-nbkba/recovery.html

It works! Even better, boot time is shorter than it was before. Thanks!

**Comment by smiledexter** [comment]
V66 debug3 work. Log http://1drv.ms/1HtGIbJ

**Comment by rovo89** [comment]
OK, great! I'll release an official update then. Hopefully by tomorrow at the latest.
