### ISSUE TITLE
Genymotion low system space after install. Also xposed is installed but not active.

### ISSUE THREAD

**Issue by Programming4life** [rovo89/Xposed#46]
After installing xposed in genymotion. genymotion keeps giving me a warning that ~200mb system space is left. Also if I open the xposed installer it says xposed is installed but not active. I think this is all happening because there isn't any space on the system partition. But how can I expand the system partition then? Logcat output can be found here: https://dl.dropboxusercontent.com/u/19835281/logcat.txt

**Comment by rovo89** [comment]
`execl(/system/bin/dex2oat) failed: Permission denied`

It seems that you didn't install Xposed properly. Did you follow the instructions, i.e. flash my GenyFlash scripts first?

**Comment by Programming4life** [comment]
Had to install GenyFlash again and it soled it some how.
