### ISSUE TITLE
v65-Flashable: Issue with update-binary

### ISSUE THREAD

**Issue by McBane87** [rovo89/Xposed#48]
Please have a look here:
http://forum.xda-developers.com/showpost.php?p=61640206&postcount=7965

**Comment by rovo89** [comment]
Thanks for opening the issues, I think it's easier to have to technical discussions here.

If I understood you right, you have already extracted the BusyBox executable from the ZIP, right? If not, you can also download it from here: https://github.com/rovo89/XposedTools/blob/master/zipstatic/arm/META-INF/com/google/android/update-binary?raw=true

It would be great if you could do some further testing with this. My flash script hides the output of the simple "mount /system". Could you try to unmount /system via your recovery and then execute `./busybox mount /system` (path depends on how you have saved the binary)? Does that produce any output? Is /system actually mounted afterwards? I could imagine that remounting a not mounted partition might result in the "invalid argument" error. Also, what does `./busybox mount` (without further arguments) say when you have mounted the system partition with the default fstab (via recovery)?

Actually, I think I might be able to reproduce it when I change my own device's fstab, but it would be good if you could check from your side as well.

**Comment by McBane87** [comment]
No Problem. But let's just ignore the remount error, because it's only the symptom of the first mounting, which is not working.

So here is the output:

```
/tmp # ./busybox 
BusyBox v1.22.1 bionic (2015-06-04 10:07 +0000) multi-call binary.
BusyBox is copyrighted by many authors between 1998-2012.
Licensed under GPLv2. See source distribution for detailed
copyright notices. Merged for bionic by tpruvot@github

Usage: busybox [function [arguments]...]
   or: busybox --list
   or: function [arguments]...

	BusyBox is a multi-call binary that combines many common Unix
	utilities into a single executable.  Most people will create a
	link to busybox for each function they wish to use and BusyBox
	will act like whatever it was invoked as.

Currently defined functions:
	[, [[, ash, basename, cat, chattr, chcon, chgrp, chmod, chown, cksum,
	cp, cut, date, dd, df, dirname, du, echo, egrep, grep, halt, head, id,
	ln, ls, mkdir, mount, mv, poweroff, printf, pwd, readlink, reboot,
	restorecon, rm, rmdir, stat, sync, tail, test, touch, umount, uname,
	unzip

/tmp # ./busybox mount | grep system
/tmp #

/tmp # cat /etc/fstab 
/dev/block/platform/msm_sdcc.1/by-name/system /system ext4 defaults
/dev/block/platform/msm_sdcc.1/by-name/cache /cache ext4 defaults
/dev/block/platform/msm_sdcc.1/by-name/userdata /data ext4 defaults

/tmp # ./busybox mount /system
mount: mounting /dev/block/platform/msm_sdcc.1/by-name/system on /system failed: Invalid argument

/tmp # sed -i 's/\/system ext4 defaults/\/system ext4 rw/g' /etc/fstab 
/tmp # cat /etc/fstab 
/dev/block/platform/msm_sdcc.1/by-name/system /system ext4 rw
/dev/block/platform/msm_sdcc.1/by-name/cache /cache ext4 defaults
/dev/block/platform/msm_sdcc.1/by-name/userdata /data ext4 defaults

/tmp # ./busybox mount /system
/tmp # ./busybox mount | grep system
/dev/block/platform/msm_sdcc.1/by-name/system on /system type ext4 (rw,seclabel,relatime,data=ordered)
```

**Comment by tonyp** [comment]
I believe this should get fixed by https://github.com/rovo89/android_external_busybox/pull/1 (https://github.com/romracer/android_external_busybox/commit/51af1c54fb89d10d946c497818c4a416f2dd051f precisely).

**Comment by rovo89** [comment]
Should be fixed in v66.
