### ISSUE TITLE
Zygote dying on Galaxy S6 Android 5.1

### ISSUE THREAD

**Issue by arter97** [rovo89/Xposed#49]
Now that deodexing Android 5.1 firmware is possible, I went on porting Xposed to Galaxy S6 Android 5.1 with almost the same procedures that I've done with Sammy's Android 5.0, but now with aarch64 compilation.

I managed to fix core-libart.jar to match AOSP's style until the point where Zygote completely dies without complaining which functions are missing or malfunctioning.
(PS, deodex'ed firmware without installing Xposed's new files boots just fine without issues)

Logcat - http://pastebin.com/WXvryB0m
Tombstone - http://pastebin.com/pKzb47nm

@rovo89 , I'd greatly appreciate it if you can take a look at those logs and suggest me what to do next.. as I can't figure out what to do exactly :(

**Comment by arter97** [comment]
Seems like "Class not found for preloading" messages also print from stock, untouched firmware.
That cannot be the culprit.

**Comment by wanam** [comment]
@arter97 I don't know if this can help, but did you try to have a look at what instruction is crashing at the offsets:
> I/DEBUG   ( 2867):     #00 pc 0000000000000024  /data/dalvik-cache/arm64/system@framework@boot.oat
> I/DEBUG   ( 2867):     #01 pc 000000000002aff8  /data/dalvik-cache/arm64/system@framework@boot.oat

I only have a free version of IDA on my hands and it doesn't allow to disassemble arm files, and other online services are size limited.

If someone can do that, here is the compiled boot.oat: https://www.dropbox.com/s/7ldcpvrw9lr8727/system%40framework%40boot.zip?dl=0

**Comment by arter97** [comment]
oatdump can get somewhat debuggable info but I've yet to find a relation with the crash.
https://code.google.com/p/android/issues/detail?id=173420

**Comment by arter97** [comment]
Moving to XDA thread, sorry for posting off-topic here.
http://forum.xda-developers.com/galaxy-s6/development/dev-getting-xposed-64-bit-samsung-t3153786

**Comment by rovo89** [comment]
Well, there isn't anything more I could tell you, except that you could try to build the debug variant of ART... You might have to keep the original app_process binaries though, I think Xposed is hardcoded on libart.so and might produce strange issues with libartd.so.
