### ISSUE TITLE
xposed causes sygic to crash

### ISSUE THREAD

**Issue by suljo94** [rovo89/Xposed#54]
Hey rovo

so latelly I tried using xposed(lollipop) and sygic and sygic would crash after doing some research I saw a couple of guys having the same problem (see link 1), so I used the uninstaller and sygic stopped crashing, but first I took a log(see link 2) I would be greatfull if you would at least look into it.

link1:http://forum.xda-developers.com/xposed/xposed-lollipop-sygic-causing-problems-t3114229
link2:https://www.dropbox.com/s/2ambl6xjn3bhetm/2015-08-03_00.39.zip?dl=0

**Comment by rovo89** [comment]
Could you try this please? http://forum.xda-developers.com/xposed/xposed-lollipop-sygic-causing-problems-t3114229/page9#post62331220
