### ISSUE TITLE
LG G2mini D618 Bootloop with v69 v70

### ISSUE THREAD

**Issue by numpea** [rovo89/Xposed#55]
on previous built v67 v68 i got bootloop when i clear dalvik and cache because of the low space error but with v69 v70 i doesn't even boot ! without wiping cache and dalvik, and with wiping cache and dalvik ! can you look into my logcat and tell me what is wrong ?
my logcat after flashing xposed https://drive.google.com/file/d/0BxDO1J2_PJJobzVmaWVOaENmdmc/view?usp=sharing
no way to get device boot proprely with xposed-uninstaller i just keep bootlooping 
my logcat after using xposed-uninstaller https://drive.google.com/file/d/0BxDO1J2_PJJobHdOc21BOUdubWc/view?usp=sharing

**Comment by rovo89** [comment]
File size of 0 bytes not large enough to contain ELF header of 52 bytes: '/system/framework/arm/boot.oat'

Is this file really empty? Then you probably didn't flash your ROM correctly. This file is not touched by Xposed, but is required for the system to run.

**Comment by numpea** [comment]
my ROM is flashed correctly i'm using stock rom and it's working very well until i flash xposed 
i'm not the only one with D618 that got a bootloop after flashing xposed framework

**Comment by rovo89** [comment]
So... is this file really empty or not? If it is, was it empty before flashing Xposed? I cannot imagine any way how Xposed could clear it. What I can see is that there's a different behavior in the logcats, which is expected. However, both complain about the 0 byte file.

**Comment by numpea** [comment]
no it wasn't empty before flashing Xposed it's like 72.5 Mb 
and if i take backup of that file and restore it after flashing Xposed or i can't take backup of it ?

**Comment by rovo89** [comment]
Assuming everything is working fine now (without Xposed), it would be helpful if you could flash Xposed, and immediately check the file size again (before restarting). The restart, wait a bit to make sure there's still a bootloop and check the file size again. Depending on the results, I can think about further ways to investigate.

In general, you have to ensure that there's enough free space for the Dalvik cache. Maybe the error message isn't correct and actually wants to say that the recompiled file in the Dalvik cache is empty. That could be a consequence of too little free space. But again, this is just a guess in case the file in /system isn't really empty.

**Comment by numpea** [comment]
Ok, i'll do that and report back :+1:

**Comment by numpea** [comment]
1- the boot.oat file after flashing xposed 
![capture1](https://cloud.githubusercontent.com/assets/13703117/9198004/d50f5370-4030-11e5-83e8-c7cfbf245f5e.JPG)
2- the boot.oat file after flashing xposed and wiping dalvik and cache 
![capture2](https://cloud.githubusercontent.com/assets/13703117/9198020/f0c92e4c-4030-11e5-85b5-b3266da4376c.JPG)
3- bootloop after rebooting for 15 mn then back to recovery checked the boot.oat file it was the same nothing changed it was not empty 71.7 Mb

**Comment by rovo89** [comment]
OK.. kind of expected, but still strange that you experience issues even after flashing the uninstaller. The only explanation would be that it's because the Dalvik cache gets cleared after flashing Xposed. And I assume you restore the previous cache along with your backup.

So one thing to try is deleting the Dalvik cache without flashing Xposed. I would expect that this results in a bootloop as well, as if should be the same situation as flashing Xposed and then the uninstaller.

Maybe the system also incorrectly determines the file size, but no idea what could go wrong there. I might need to build a special debug version to get more information.

**Comment by numpea** [comment]
yes i restore cache with previous backup
now i tried to clear dalvik and cache without flashing xposed and i did not result in a bootloop my device boot and actualize apps and runs normal 
in the previous built v67 v68 Xposed worked !! but i got the space error and if i cleared cache and dalvik to get rid of the error i got into bootloop
but with those two last build it doesn't even boot i got bootloop even without clearing cache and dalvik

**Comment by rovo89** [comment]
Here's another idea for further debugging. The command `adb shell ls -lRZ /system` recursively shows all files within /system, along with their attributes and SELinux contexts. Maybe comparing the output of this beween different situations (before anything, after flashing Xposed, after flashing the uninstaller) will give some hints. I still don't get why it doesn't work after flashing the uninstaller, so I would first like to find out where the difference is.

**Comment by numpea** [comment]
Ok great idea i will make that for you 
and thanks for your time and work spending on this really appreciate it

**Comment by numpea** [comment]
i don't know what was wrong i used v70 xposed worked without wiping cache i didn't got a bootloop maybe because a reflashed rom yesterday !! 

but LGCover and LG weather still FC and used a script to remove them rebooted everything fine 
still the low space error i wiped cache and dalvik and => got a bootloop 
rebooted and used uninstaller same thing => bootloop 

so here is all system files in the various situations 
before anything : https://drive.google.com/file/d/0BxDO1J2_PJJoeU1FYWJ4SGFNUnM/view?usp=sharing

after flashing exposed (without wiping cache and dalvik => no bootloop) (android updating apps on every reboot) : https://drive.google.com/file/d/0BxDO1J2_PJJoVTNGNlcxN2ZwMnM/view?usp=sharing

after flashing exposed (wiping cache and dalvik => bootloop) : https://drive.google.com/file/d/0BxDO1J2_PJJobEs0czZ6Tk5xYm8/view?usp=sharing

after flashing the uninstaller this time uninstaller worked i was waiting for 20min of bootloop but now it starts in 2 min !! : https://drive.google.com/file/d/0BxDO1J2_PJJoc18xcDVYcnpNMU0/view?usp=sharing

and here is a logcat of the bootloop after flashing xposed and wiping dalvik and cache : https://drive.google.com/file/d/0BxDO1J2_PJJoMDYzR1QtNERtSVE/view?usp=sharing

**Comment by rovo89** [comment]
OK, so something probably was wrong with your ROM... anyway, doesn't really matter if at least that is solved now. Low storage space is expected as Xposed needs to recompile more things than the original ROM. You'll have to free up some space. The remaining issue is the same as in #53, please try that.

**Comment by numpea** [comment]
thank you so much @rovo89  that worked very fine i wiped cache and dalvik and didn't got a bootloop he's booting updating apps and the low space error is gone after wiping cache 
all things are greaat thank you so much for you work and time spending with that :+1:
