### ISSUE TITLE
complie issue on 5.1.1_r9 Nexus 5

### ISSUE THREAD

**Issue by oososo** [rovo89/Xposed#57]
Hi, I copy the xposed project to framework/base/cmds/xposed.and using mmm to build.I got many errors following:
Using target GCC 4.8 disables thread-safety checks.
PRODUCT_COPY_FILES device/generic/goldfish/data/etc/apns-conf.xml:system/etc/apns-conf.xml ignored.
No private recovery resources for TARGET_DEVICE hammerhead
target thumb C++: libxposed_art <= frameworks/base/cmds/xposed/libxposed_art.cpp
frameworks/base/cmds/xposed/libxposed_art.cpp: In function 'void xposed::onVmCreated(JNIEnv*)':
frameworks/base/cmds/xposed/libxposed_art.cpp:44:19: error: 'XLOG' was not declared in this scope
         XLOG(ERROR) << "Error while loading XTypedArray class '" CLASS_XTYPED_ARRAY "'";
                   ^
frameworks/base/cmds/xposed/libxposed_art.cpp:53:19: error: 'XLOG' was not declared in this scope
         XLOG(ERROR) << "Error while loading Xposed class '" CLASS_XPOSED_BRIDGE "'";
                   ^
frameworks/base/cmds/xposed/libxposed_art.cpp:59:5: error: 'xposed_callback_class' is not a member of 'art::mirror::ArtMethod'
     mirror::ArtMethod::xposed_callback_class = classXposedBridge;
     ^
frameworks/base/cmds/xposed/libxposed_art.cpp:61:14: error: 'XLOG' was not declared in this scope
     XLOG(INFO) << "Found Xposed class " CLASS_XPOSED_BRIDGE ", now initializing";
              ^
frameworks/base/cmds/xposed/libxposed_art.cpp: In function 'void xposed::logExceptionStackTrace()':
frameworks/base/cmds/xposed/libxposed_art.cpp:78:15: error: 'XLOG' was not declared in this scope
     XLOG(ERROR) << self->GetException(nullptr)->Dump();
               ^
frameworks/base/cmds/xposed/libxposed_art.cpp: In function 'jboolean xposed::callback_XposedBridge_initNative(JNIEnv*)':
frameworks/base/cmds/xposed/libxposed_art.cpp:96:5: error: 'xposed_callback_method' is not a member of 'art::mirror::ArtMethod'
     mirror::ArtMethod::xposed_callback_method = env->GetStaticMethodID(classXposedBridge, "handleHookedMethod",
     ^
frameworks/base/cmds/xposed/libxposed_art.cpp:98:9: error: 'xposed_callback_method' is not a member of 'art::mirror::ArtMethod'
     if (mirror::ArtMethod::xposed_callback_method == nullptr) {
         ^
frameworks/base/cmds/xposed/libxposed_art.cpp:99:19: error: 'XLOG' was not declared in this scope
         XLOG(ERROR) << "ERROR: Could not find method " CLASS_XPOSED_BRIDGE ".handleHookedMethod(Member, int, Object, Object, Object[])";
                   ^
frameworks/base/cmds/xposed/libxposed_art.cpp: In function 'void xposed::XposedBridge_hookMethodNative(JNIEnv*, jclass, jobject, jobject, jint, jobject':
frameworks/base/cmds/xposed/libxposed_art.cpp:123:16: error: 'class art::mirror::ArtMethod' has no member named 'EnableXposedHook'
     artMethod->EnableXposedHook(env, javaAdditionalInfo);
                ^
frameworks/base/cmds/xposed/libxposed_art.cpp: In function 'void xposed::XposedBridge_setObjectClassNative(JNIEnv*, jclass, jobject, jclass)':
frameworks/base/cmds/xposed/libxposed_art.cpp:146:19: error: 'XLOG' was not declared in this scope
         XLOG(ERROR) << "Could not initialize class " << PrettyClass(clazz);
                   ^
In file included from art/runtime/atomic.h:25:0,
                 from art/runtime/thread.h:28,
                 from frameworks/base/cmds/xposed/libxposed_art.cpp:8:
frameworks/base/cmds/xposed/libxposed_art.cpp: In function 'void xposed::XposedBridge_dumpObjectNative(JNIEnv*, jclass, jobject)':
frameworks/base/cmds/xposed/libxposed_art.cpp:155:25: error: 'LOG_XPOSED' was not declared in this scope
     UNIMPLEMENTED(ERROR|LOG_XPOSED);
                         ^
art/runtime/base/logging.h:135:61: note: in definition of macro 'LOG'
 #define LOG(severity) ::art::LogMessage(__FILE__, __LINE__, severity, -1).stream()
                                                             ^
frameworks/base/cmds/xposed/libxposed_art.cpp:155:5: note: in expansion of macro 'UNIMPLEMENTED'
     UNIMPLEMENTED(ERROR|LOG_XPOSED);
     ^
frameworks/base/cmds/xposed/libxposed_art.cpp: In function '_jobject* xposed::XposedBridge_cloneToSubclassNative(JNIEnv*, jclass, jobject, jclass)':
frameworks/base/cmds/xposed/libxposed_art.cpp:162:73: error: no matching function for call to 'art::mirror::Object::Clone(art::Thread*, uint32_t)'
     mirror::Object* dest = obj->Clone(soa.Self(), clazz->GetObjectSize());
                                                                         ^
frameworks/base/cmds/xposed/libxposed_art.cpp:162:73: note: candidate is:
In file included from art/runtime/mirror/art_method.h:24:0,
                 from art/runtime/mirror/art_method-inl.h:20,
                 from frameworks/base/cmds/xposed/libxposed_art.cpp:10:
art/runtime/mirror/object.h:105:11: note: art::mirror::Object* art::mirror::Object::Clone(art::Thread*)
   Object* Clone(Thread* self) SHARED_LOCKS_REQUIRED(Locks::mutator_lock_);
           ^
art/runtime/mirror/object.h:105:11: note:   candidate expects 1 argument, 2 provided
build/core/binary.mk:620: recipe for target 'out/target/product/hammerhead/obj/SHARED_LIBRARIES/libxposed_art_intermediates/libxposed_art.o' failed
make: *** [out/target/product/hammerhead/obj/SHARED_LIBRARIES/libxposed_art_intermediates/libxposed_art.o] Error 1
make: Leaving directory '/home/ososo/ANDROID5.1.1_r9'

#### make failed to build some targets (9 seconds) ####

Could you help me fix them?

**Comment by rovo89** [comment]
This can't work. Xposed only compiles against the special ART version that has been modified for Xposed support. Neither the Xposed nor the android_art project in my repositories are compatible with 5.1 yet. You'll either have to use an unofficial fork or wait until I push the official update (should be within the next days, but no promises).
