### ISSUE TITLE
Jiayu S3 stock 5.1 bootloop Xposed v72-73

### ISSUE THREAD

**Issue by optstep** [rovo89/Xposed#60]
logcat - http://rghost.ru/6kjmT7vXY

**Comment by rovo89** [comment]
Can you please upload /system/priv-app/Mms/arm64/Mms.odex?

**Comment by optstep** [comment]
/system/priv-app/Mms/arm64/Mms.odex - http://rghost.ru/8fvgJW7D7

**Comment by optstep** [comment]
deodex firmvare 99%. delete \system\framework\arm\boot.oat and boot.art
logcat - http://rghost.ru/7KsF9Ljz5

**Comment by optstep** [comment]
have in firmware only \system\framework\arm64\boot.oat and boot.art

**Comment by optstep** [comment]
v73 logcat - http://rghost.ru/7nWT8GVtk

**Comment by rovo89** [comment]
Please try v74, it should fix the issue.

**Comment by optstep** [comment]
v74 - bootloop

**Comment by optstep** [comment]
bootloop It appears after installation GAPPS
