### ISSUE TITLE
can not build xposed

### ISSUE THREAD

**Issue by CwxGhost** [rovo89/Xposed#61]
error log:

target thumb C++: libxposed_art <= frameworks/base/cmds/xposed/libxposed_art.cpp
frameworks/base/cmds/xposed/libxposed_art.cpp: In function 'void xposed::onVmCreated(JNIEnv*)':
frameworks/base/cmds/xposed/libxposed_art.cpp:44:19: error: 'XLOG' was not declared in this scope
frameworks/base/cmds/xposed/libxposed_art.cpp:53:19: error: 'XLOG' was not declared in this scope
frameworks/base/cmds/xposed/libxposed_art.cpp:59:5: error: 'xposed_callback_class' is not a member of 'art::mirror::ArtMethod'
frameworks/base/cmds/xposed/libxposed_art.cpp:61:14: error: 'XLOG' was not declared in this scope
frameworks/base/cmds/xposed/libxposed_art.cpp: In function 'void xposed::logExceptionStackTrace()':
frameworks/base/cmds/xposed/libxposed_art.cpp:78:15: error: 'XLOG' was not declared in this scope
frameworks/base/cmds/xposed/libxposed_art.cpp: In function 'jboolean xposed::callback_XposedBridge_initNative(JNIEnv*)':
frameworks/base/cmds/xposed/libxposed_art.cpp:96:5: error: 'xposed_callback_method' is not a member of 'art::mirror::ArtMethod'
frameworks/base/cmds/xposed/libxposed_art.cpp:98:9: error: 'xposed_callback_method' is not a member of 'art::mirror::ArtMethod'
frameworks/base/cmds/xposed/libxposed_art.cpp:99:19: error: 'XLOG' was not declared in this scope
frameworks/base/cmds/xposed/libxposed_art.cpp: In function 'void xposed::XposedBridge_hookMethodNative(JNIEnv*, jclass, jobject, jobject, jint, jobject)':
frameworks/base/cmds/xposed/libxposed_art.cpp:123:16: error: 'class art::mirror::ArtMethod' has no member named 'EnableXposedHook'
frameworks/base/cmds/xposed/libxposed_art.cpp: In function 'void xposed::XposedBridge_setObjectClassNative(JNIEnv*, jclass, jobject, jclass)':
frameworks/base/cmds/xposed/libxposed_art.cpp:146:19: error: 'XLOG' was not declared in this scope
frameworks/base/cmds/xposed/libxposed_art.cpp: In function 'void xposed::XposedBridge_dumpObjectNative(JNIEnv*, jclass, jobject)':
frameworks/base/cmds/xposed/libxposed_art.cpp:155:5: error: 'LOG_XPOSED' was not declared in this scope
frameworks/base/cmds/xposed/libxposed_art.cpp: In function '_jobject* xposed::XposedBridge_cloneToSubclassNative(JNIEnv*, jclass, jobject, jclass)':
frameworks/base/cmds/xposed/libxposed_art.cpp:162:73: error: no matching function for call to 'art::mirror::Object::Clone(art::Thread*, size_t)'
frameworks/base/cmds/xposed/libxposed_art.cpp:162:73: note: candidate is:
In file included from art/runtime/mirror/class.h:21:0,
                 from art/runtime/mirror/art_method.h:20,
                 from art/runtime/mirror/art_method-inl.h:20,
                 from frameworks/base/cmds/xposed/libxposed_art.cpp:10:
art/runtime/mirror/object.h:84:11: note: art::mirror::Object* art::mirror::Object::Clone(art::Thread*)
art/runtime/mirror/object.h:84:11: note:   candidate expects 1 argument, 2 provided

**Comment by rovo89** [comment]
Looks like you haven't checked out the Xposed variant of ART: https://github.com/rovo89/android_art
Please use these instructions and scripts for building: https://github.com/rovo89/XposedTools

**Comment by CwxGhost** [comment]
I have been carried out in accordance with the above steps, but in the end there is a mistake.
The error log as follows:
Build failed!
Last 10 lines from the log:
   HOST_ARCH=x86
   HOST_OS=linux
   HOST_OS_EXTRA=Linux-3.13.0-32-generic-x86_64-with-Ubuntu-12.04-precise
   HOST_BUILD_TYPE=release
   BUILD_ID=KRT16S
   OUT_DIR=out
   ============================================
   including ./abi/cpp/Android.mk ...
   including ./art/Android.mk ...
   art/build/Android.common_build.mk:211: *** LIBART_IMG_HOST_BASE_ADDRESS unset

**Comment by rovo89** [comment]
Well, have you really replaced the "art" folder with https://github.com/rovo89/android_art, e.g. by using the local manifest from the tools repository?

**Comment by CwxGhost** [comment]
Yes, but I did this, delete the original "art" folder and then copy the new folder

**Comment by rovo89** [comment]
KRT16S seems to be KitKat, right? In the current state of the repository, it might not be possible to compile Xposed for pre-Lollipop versions. You might have to check out commit e71b632817d76b37f57f5b7cc3c39053f2d2e29c to get to the last state that can be compiled, but then you also need the older XposedBridge and so on...

I hope that one day, I can unify all of the Xposed components again, but for now, you either have to use the prebuilt files or you'll have more effort to build it.

**Comment by CwxGhost** [comment]
Thank you for your reply, I'll try your way
