### ISSUE TITLE
Question: Gobal Method Hooking

### ISSUE THREAD

**Issue by ajinabraham** [rovo89/Xposed#62]
If say there exist a method named `isRooted()` in different applications.
With Xposed framework, can I hook and change the return value of this method for all the applications installed in the system which are using this method, without mentioning the package name?

**Comment by rovo89** [comment]
It depends on whether you're talking about the same method (in the same class) used by all apps, or about different methods (in different classes) which just have the same name.

The latter is not possible, you need to know the class in which you want to hook something.
The former might be possible. In that case, I assume the method is part of the Android standard, so you would hook it in `initZygote()`. I can't say more without additional details about your situation.
