### ISSUE TITLE
Bootloop in Xperia T2 Ultra D5322 ( 5.1.1 )

### ISSUE THREAD

**Issue by mahmoudsaad1** [rovo89/Xposed#64]
hi ,
I have a bootloop after flashing xposed-v73-sdk22-arm
log : http://pastebin.com/b0bkqAaK
please help

**Comment by rovo89** [comment]
```
I/dex2oat ( 2997): Using '/system/framework/arm/ethernet-service.odex' instead of file descriptor
I/dex2oat ( 2997): Decided to run without swap.
F/dex2oat ( 2997): art/runtime/thread.cc:1143] No pending exception expected: java.lang.ArrayIndexOutOfBoundsException: length=75; index=30976
```

That's very likely the known issue that Sony's odex files are corrupted. I'm not sure whether this happened by mistake or is intended to prevent decompilation... You get similar messages with tools like baksmali as well. So unless someone manages to extract a working .dex file from the odex files (which can be decompiled), I'm afraid there's nothing I can do for you.

**Comment by pylerSM** [comment]
Cant we just skip these odex files to prevent bootlool.

**Comment by rovo89** [comment]
I don't think so. Xposed has to recompile everything, otherwise the hooks won't work (reliably) because of a few of the optimizations done by standard ART. As the system services would be affected, many modules wouldn't work correctly and the authors would get strange bug reports that are extremely hard to debug and cannot be solved. And even if this was accepted, we would need to identify such broken odex files quite early - even before the ROM tries to recompile them.

**Comment by mahmoudsaad1** [comment]
so no hope getting xposed work on my device ?

**Comment by rovo89** [comment]
I might have missed something, but from what I've seen, Xposed can't work properly for this ROM. It will probably work on custom ROMs though, and who knows - maybe someone finds out that the original dex file can be reconstructed somehow (which I doubt because a part of it has been overwritten with other data).

**Comment by mahmoudsaad1** [comment]
Thanks for your help :+1:

**Comment by rovo89** [comment]
In case someone uses the search function: Crashes on Sony stock-based ROMs with messages like `No pending exception expected: java.lang.ArrayIndexOutOfBoundsException: length=123; index=456` are caused by corrupted files in the ROM and as far as I can see can't be fixed. If anyone is able to properly deodex such a ROM, we can talk again.

**Comment by mahmoudsaad1** [comment]
Would you suggest a way to deodex lollipop rom properly ?

**Comment by rovo89** [comment]
I honestly don't know which way is the best, I never cared about that. My point here is: Deodexing the files is quite close to the first step of recompiling them, which is what Xposed must do. I have seen several files and they seemed to be corrupted. I couldn't deodex them, but if somebody found any way to do so (e.g. by somehow fixing those files), it would probably be possible to recompile them as well. Unless that happens, I don't see a chance for Xposed to support such ROMs.

**Comment by mahmoudsaad1** [comment]
Could you please check this ? :)
http://forum.xda-developers.com/t2-ultra/development/stock-xperia-t2-deodex-patch-t3254093

**Comment by rovo89** [comment]
It's not clear to me what the author has done there. Has he deodexed a stock ROM with broken files (like services.odex) or did he take files from another ROM? And if he succeeded to actually deodex the broken files, how was that done?

**Comment by mahmoudsaad1** [comment]
He didn't deodex T2 Ultra stock rom , He ported Z1 compat rom to T2 Ultra

**Comment by mahmoudsaad1** [comment]
The rom works fine , xposed framework successfully installed and active

**Comment by rovo89** [comment]
OK, good for you. So the Z1 Compact ROM doesn't seem to be broken then?

**Comment by mahmoudsaad1** [comment]
I don't think so , I think this is the solution for t2 ultra users problem with xposed
The rom isn't fully stable but he said he will release the stable version soon

**Comment by Ziad7** [comment]
I have bootloop on my Xperia T2 Ultra Dual D5322
If i delete boot.oat form "System/framework/arm/boot.oat
And put another one (boot.oat) from rhe original rom 5.1.1
It will works or not ?

**Comment by mahmoudsaad1** [comment]
No, just flash xposed uninstaller.zip then wipe cache and dalvik cache


Sent from Outlook Mobile






On Thu, Dec 17, 2015 at 4:39 PM -0800, "Ziad7" <notifications@github.com> wrote:





I have bootloop on my Xperia T2 Ultra Dual D5322
If i delete boot.oat form "System/framework/arm/boot.oat
And put another one (boot.oat) from rhe original rom 5.1.1
It will works or not ?

---

**Comment by Ziad7** [comment]
It's didn't work 
I got try that before ans same thing bootloop 
When i flash rom from flashtool without wipe data and apps log to because and don't wanna lose my data 
The phone got work to optimizing app and he optimize the apps in so fast, after that all the apps get force stop all the time, nothing get work 
If i take backup from twrp to data and wipe my data, it's gonna work when i restored or not? 
And thank for your answer 
I will try another time with deodexed

**Comment by Ziad7** [comment]
Sorry for the mistake 
I got try that before and its same (bootloop)

**Comment by rovo89** [comment]
Is this still related to Xposed? If you want to talk about how you can flash a ROM, please do this on XDA. Every comment here will send an email to the 200+ watchers of the repository. To my knowledge, the stock Sony ROMs are broken and I can't do anything about this.

**Comment by Ziad7** [comment]
Its not like that 
I got infinity bootloop 
Now its need to delete my system and data and everything after that flash official rom to get rid of bootloop
What i want my data i need it and my apps data, i don't wanna to delete them

**Comment by Muhammad7k** [comment]
it's worked on xperia z2 5.1.1 with custom rom (existenZ v6) with xposed-v79-sdk22-arm.zip

**Comment by yashwantbansal89** [comment]
I have flashed oneplus2 version oxygenos 2.2.0 every version of xposed framework..sdk22 v72,73,and 79 but after flash it hardbrick...
But in oxgenos 2.1.0 is supporting same framework ..sdk22 v72..

**Comment by nassy42** [comment]
Work on every Sony Xperia Z2 5.1.1 ROM for me, except the last sony update .234 .. :\

**Comment by Lynix87** [comment]
Booloop Samsung Galaxy S5 SM G900F on Marshmallow 6.0.1

**Comment by odisseo86** [comment]
hello everyone, I have a problem about installing fremework Xposed on my galaxy s6 currently mount the custom rom noble , that turned me my s6 in a s7 edge I infer from the model code which appears to me in the settings. Xposed installer will install correctly even when the framework of recovery he flashed the phone is switched off automatically, when you reboot it manually the framework is not installed . can you help me. please. thank you

**Comment by krishana5292** [comment]
Xpose fremwork not work issu touchwiz rom 
My samsung A500g 6.0.1 v plz help

**Comment by Agentdude420** [comment]
Hey, I installed Xsposed Framework on my Xperia C3 and without reading the 'Known issues' and, my phone is stuck on a bootloop. Can someone help me to remove the framework? Thanks!
Sony Xperia C3 D2533
Arm 7i

**Comment by ChRriiZz** [comment]
> ```
> I/art     ( 2957): DexFile_isDexOptNeeded file /system/framework/arm/ethernet-service.odex needs to be recompiled with Xposed for /system/framework/ethernet-service.jar
> I/dex2oat ( 2997): /system/bin/dex2oat --zip-fd=6 --zip-location=/system/framework/ethernet-service.jar --oat-fd=7 --oat-location=/data/dalvik-cache/arm/system@framework@ethernet-service.jar@classes.dex --instruction-set=arm --instruction-set-features=div --runtime-arg -Xms64m --runtime-arg -Xmx512m --swap-fd=11
> I/dex2oat ( 2997): Using '/system/framework/arm/ethernet-service.odex' instead of file descriptor
> I/dex2oat ( 2997): Decided to run without swap.
> F/dex2oat ( 2997): art/runtime/thread.cc:1143] No pending exception expected: java.lang.ArrayIndexOutOfBoundsException: length=75; index=30976
> ```
> 
> That's very likely the known issue that Sony's odex files are corrupted. I'm not sure whether this happened by mistake or is intended to prevent decompilation... You get similar messages with tools like baksmali as well. So unless someone manages to extract a working .dex file (which can be decompiled) from the .odex file, I'm afraid there's nothing I can do for you.

**Comment by Rwadxvv** [comment]
1 mast

**Comment by Rwadxvv** [comment]
![Screenshot_٢٠٢٢٠٨٠١-٠١٥٤٥١_One UI Home](https://user-imag@rovo89 s.githubusercontent.com/109966453/182050004-1e4f037a-155f-4ee6-842a-baea30e2f836.jpg)
@
