### ISSUE TITLE
Nop Hook breaks xposed

### ISSUE THREAD

**Issue by Fuzion24** [rovo89/Xposed#68]
```java
        findAndHookMethod(java.lang.System.class, "loadLibrary", String.class, new XC_MethodHook() {
            @Override
            protected void beforeHookedMethod(XC_MethodHook.MethodHookParam param) throws Throwable {
            }
        });
```

same issue when trying this hook on dragonboard (qualcomm's 5.1.1 + xposed alpha)
findAndHookMethod(java.lang.reflect.Method.class, "invoke", Object.class, Object[].class, new XC_MethodHook()

-> The same hook works fine on android 4.4.4.

**Comment by giantpune** [comment]
I cannot provide a helpful log :( .  There is no useful information in the logs or logcat.  The app you are hooking with these hooks just die silently.

**Comment by rovo89** [comment]
@Fuzion24 What do you mean with "breaks Xposed"?

**Comment by Fuzion24** [comment]
The app just stops functioning.  Nothing in logcat, etc..

**Comment by rovo89** [comment]
OK, so actually it breaks the app. I assume it depends on whether the app has (and depends on) any JNI libraries.

Here's the implementation of System.loadLibrary():
```
public static void loadLibrary(String libName) {
  Runtime.getRuntime().loadLibrary(libName, VMStack.getCallingClassLoader());
}
```

As you can see, the library is loaded from the calling classloader - and by hooking the method, that isn't the app's classloader anymore, but maybe Xposed's, yours or the boot classloader. I don't see a way to fix this, but you can probably hook Runtime.loadLibrary() instead.

Is the Method.invoke() issue also without any log information? I would never recommend to hook such a central method, and I can't really support you with this.

**Comment by giantpune** [comment]
@rovo89 what about the second hook mentioned?  this worked with xposed on 4.4.4 but does not work on 5.1.1.

```sh
findAndHookMethod(java.lang.reflect.Method.class, "invoke", Object.class, Object[].class, new XC_MethodHook()
```

**Comment by rovo89** [comment]
ART and Dalvik implement Method.invoke() totally differently, that might be the reason.
