### ISSUE TITLE
Fatal signal 13 (SIGPIPE), code 0 in tid 25562 (sh)

### ISSUE THREAD

**Issue by Alexey71** [rovo89/Xposed#70]
Hello. What is error, can fix please?. CM12.1-5.1.1 official

tombstone_04 - http://pastebin.com/GSwimFbQ
xposed_error_20151003_094014.log - http://pastebin.com/gChTxzDE

**Comment by rovo89** [comment]
That's a crash of the "sh" (Shell) process. It's not related to Xposed, the only issue here is that this crash is written to the Xposed log (see #40).
