### ISSUE TITLE
React on 5.1.1_r19 change in app_process

### ISSUE THREAD

**Issue by rovo89** [rovo89/Xposed#71]
https://android.googlesource.com/platform/frameworks/base.git/+/d4d3181d013f8d9b96de8e396b029f8a418894a7%5E!/#F0

**Comment by wanam** [comment]
Just tested it and it unfortunately boot-loops on the GalaxyS6 5.1.1 TW, logs: http://pastebin.com/Vwqm1VgJ

Does it have any dependent commits? what if we update the whole repo to 5.1.1_r19?

**Comment by ASHURiCAN** [comment]
Bootloop on latest CM12.1 nightlies. NEXUS 5 for my case.

**Comment by Alexey71** [comment]
Bootloop 5.1.1_r24  latest CM12.1 nightlies

**Comment by rovo89** [comment]
OK, I pretty much expected this. I'll try to post a warning later today not to update your ROM until I had the time to analyze this. I could simply merge the app_process related changes from AOSP, but then it would probably break for older ROMs...

**Comment by wanam** [comment]
Yes, that's what i did, it will break older Roms that does not have the new zygote parameter, do we need to include "libandroid_runtime" on xposed to bypass this incompatibly issue?

**Comment by rovo89** [comment]
I hope not. Function names are mangled, so the function with added parameter cannot be found by the linker anymore. So probably, we need dlsym() here, and probably it has to check for both variants. As long as GCC is used everywhere, the mangled names should be always the same - and I think this should be safe to assume as the app_process binaries seem to work everywhere.

**Comment by mkszuba** [comment]
Bootloop on the CM12.1 nightly from the 6th of October running on amami (Sony Xperia Z1 Compact) - so yeah, there definitely is a trend here.

On a completely off-topic note, I am happy to say that until this change Xposed worked perfectly on CM12.1/amami.

**Comment by rovo89** [comment]
Please stop the "me too" comments. I know that this is a breaking change which needs a reaction from my side. I'll work on this with high priority, but nevertheless it might take a few days - I don't know.

**Comment by wanam** [comment]
I just flashed the latest GalaxyS6 FW (G920FXXU3COI9), and i can confirm that Samsung has also included this patch, i applied app_process changes to xposed and it seems to work fine now.

@rovo89 Do you have any idea how we can check what variant to use with dlsym()?

**Comment by rovo89** [comment]
@wanam Currently testing this: https://github.com/rovo89/Xposed/commit/d0551ccb86f27e7bc34953bc16d4ca9754be560b
Works fine on Genymotion (with older 5.1.1), I'm about to test it on the latest CM12.1. Additional tests would be welcome, but I'm pretty confident that it will work.

**Comment by jpat14** [comment]
@rovo89 Any word on whether this fix worked for the CM12.1 nightly?

**Comment by bkromhout** [comment]
@jpat14, I run CM 12.1 on my LG G3, and I flashed v75 of xposed as well as a version of CM 12.1 that is based off of Android 5.1.1_r23 yesterday, and everything booted and works fine. I assume you'll have a similar experience, so go ahead and try it.

**Comment by DDzwiedziu** [comment]
I can confirm working with CM12.1 20151008 and v75.
