### ISSUE TITLE
Bootloop on Dell Venue 8 7840 / Android 5.1

### ISSUE THREAD

**Issue by Johnson145** [rovo89/Xposed#77]
Sadly, Xposed is still not working on my Dell Venue 8 7840. It is working on Android 5.0, but not on 5.1. It's always causing a bootloop which will only show the Intel logo.

I've attached the logcat output in the [xda discussion thread](http://forum.xda-developers.com/xposed/official-xposed-lollipop-t3030118/page987#post63260924). The xposed log file does not seem to exist, yet. 
As far as I can see this might be the first error line:
*F/libc    ( 1026): Fatal signal 6 (SIGABRT), code -6 in tid 1026 (main)*

I have used the latest official (and correct) version "xposed-v75-sdk22-x86.zip". The installation has been completed successfully without any errors. Also the device has been rooted before using a temporary Clockwork Mod revovery. Can't try any other recovery system as this is the only existing one.

Alternatively, I have also tried the unofficial version by romracer which will cause the same boot loop. Cache clearing does not help either. 

Sadly, nobody in the xda discussion thread could solve the problem, so I hope you have the time to have a closer look. Thanks in advance.

**Comment by Johnson145** [comment]
Just two more updates/hints:
- Now I've also tried the (temporary recovery version of) TWRP, but without success, too.
- It's not just a problem with my own device, but a general one with likely all devices of this model. So there are more people interested in a solution ([e.g.](http://forum.xda-developers.com/dell-venue/general/xposed-5-0-7840-t3118738/page2)).

**Comment by rovo89** [comment]
`W/dex2oat ( 1048): Failed to open oat file from '/system/framework/x86/boot.oat': Invalid oat magic for '/system/framework/x86/boot.oat'

Could you please upload that file? Maybe this is another vendor who has made changes to ART in some way.

**Comment by Johnson145** [comment]
Thanks for your answer.

Here is the file you've requested: [boot.oat] (
https://mega.nz/#!2M1SQLRQ!FE-jMDNg7N-bHXuBYqtJdqDCzol5LjyRDr3_wJxkhNw
)

And the rest of the Android 5.1 stock image, if you need anything else: [Dell Venue 8 7840 Android 5.1.zip] (
https://mega.nz/#!6V8ywBzA!aNldbmNbdDyX-y5G3KgpbDa7Q-BAzfGETWX6vp1rtko
)

I hope the files will help.

**Comment by rovo89** [comment]
I had a look at the file and it turned out that your vendor is using version 048 of the oat format. AOSP had version 045 for 5.1 and 064 for 6.0. As far as I can see, the AOSP changes that changed the version number were:
- 045 -> 046: Delete unused imtable field
- 046 -> 047: Fix LinkFieldsComparator.
- 047 -> 048: Fix ordering of fields with the same name.
There are obviously many other changes in AOSP that didn't change the format of the file. We don't know which of them they used in their version of ART.

I gave it a quick try anyway and changed the expected version from 045 to 048, but it caused various verification errors because of unexpected instructions and types. So this looks like much work... I can't make any promises if and when this can be made compatible.

**Comment by Johnson145** [comment]
Those news aren't too good. It would be great if you can make it work, but of course I understand that you can't guarantee that. Do we might have luck if the Android 6.0 update is available? So that the needed version numbers are incremented correctly?

**Comment by rovo89** [comment]
Maybe. But chances are that they will again use an intermediate version of ART on Marshmallow.

**Comment by MsK8k** [comment]
Xposed install bt not active.what can i do.plz help thr r my log https://drive.google.com/file/d/0B9nNRhu487JXM0Uwb2tMQWNkYzg/view?usp=docslist_api

**Comment by xXCooL69GuYXx** [comment]
Did you flash the right one ?

**Comment by MsK8k** [comment]
Yes with Twrp

**Comment by MsK8k** [comment]
I have flashed V80_sdk22_arm64.zip, this is suitable for my device.

**Comment by rovo89** [comment]
@MsK8k Don't hijack other issues! I will delete your comments now. The error in your case is that your ROM has a theme manager that extends the Resources class in a similar way to Xposed, and these two implementations conflict. It's a known issue, but I currently have no time to work on it. Disabling resource hooks in the Xposed Installer settings might work around it.

**Comment by vampirefo** [comment]
Any update on this? I am using i708q rom, looking at boot.oat in a hex editor, I see it's also 048

oat.048.Bt1d

logcat error.

W/dex2oat (25354): Failed to open oat file from '/system/framework/x86/boot.oat': Invalid oat magic for '/system/framework/x86/boot.oat'

**Comment by rovo89** [comment]
> Any update on this?

No, and I don't think this will be fixed. It's simply too far away from the official AOSP sources. If their Marshmallow ROMs are more standard, Xposed might work with them, but chances are that they'll once again follow their own agenda.

**Comment by Xstar97** [comment]
I have one question is it just oat version 048 thats not compatible all together(from sdk 21 to 23) or only if a lollipop device that has an sdk 21 with an oat version of 048?

**Comment by rovo89** [comment]
In each Android version, ART uses different file structures. As these file structures aren't compatible with each other (neither downwards nor upwards compatible), each ART version can only handle exactly one file version. There is no officially released version of ART that can handle oat version 048.

**Comment by guanlingji** [comment]
Hello, rovo89 ! I have some questions to ask when I was studying Xposed!
Mobile phone model HUAWEI SCL-AL00 can not be installed through the Xposed Zip Recovery package!
I want to ask what this is!

**Comment by Umarkamboh** [comment]
I flashed s7edge rom in note 3. but when I flash xposed framework zip in my phone my phone still hang on bootloop and phone does not start. How I fix bootloop??

**Comment by Xstar97** [comment]
@Umarkamboh
flash uninstaller or reflash the custom rom

**Comment by Umarkamboh** [comment]
I want to use xposed modules in my rom...after flash uninstaller how can i use xposed...how i can run xposed installer on my device.??

Sent from Yahoo Mail on Android 
 
  On Tue, Aug 23, 2016 at 16:07, Xstar97<notifications@github.com> wrote:   
@Umarkamboh
flash uninstaller or reflash the custom rom

**Comment by Xstar97** [comment]
well...I been working on a tool for some time now & had to released an entirely new app because of stupids reasons....however my app can flash the xposed framework without a custom recovery...however the new app its not available publicly so if you dont mind joining my beta to test my new app...not only it will help me, but you too!
for samsung my tool will flash wanam sdk22+ & dkcldark for sdk21 devices

here's the beta link(you may also have to join my community to install the beta tool)
https://play.google.com/apps/testing/com.mcs.terminalinstallerx

**Comment by Umarkamboh** [comment]
How can i download  your new app???

Sent from Yahoo Mail on Android 
 
  On Tue, Aug 23, 2016 at 16:19, Xstar97<notifications@github.com> wrote:   
well...I been working on a tool for some time now & had to released an entirely new app because of stupids reasons....however my app can flash the xposed framework without a custom recovery...however the new app its not available publicly so if you dont mind joining my beta to test my new app...not only it will help me, but you too!
for samsung my tool will flash wanam sdk22+ & dkcldark for sdk21 devices

here's the beta link(you may also have to join my community to install the beta tool)
https://play.google.com/apps/testing/com.mcs.terminalinstallerx

**Comment by Xstar97** [comment]
its on google play...are you not able to sign up w/ the beta link?

**Comment by Umarkamboh** [comment]
How i sign up your beta link??

Sent from Yahoo Mail on Android 
 
  On Tue, Aug 23, 2016 at 16:24, Xstar97<notifications@github.com> wrote:   
its on google play...are you not able to sign up w/ the beta link?

**Comment by Umarkamboh** [comment]
How i sign up your beta link..???

Sent from Yahoo Mail on Android 
 
  On Tue, Aug 23, 2016 at 16:24, Xstar97<notifications@github.com> wrote:   
its on google play...are you not able to sign up w/ the beta link?

**Comment by Xstar97** [comment]
you have to also join my plus community first...it should have told you when tapping the link...so join the community below & then click the beta link to sign up for the beta
https://plus.google.com/communities/101286674025561115431

**Comment by rovo89** [comment]
This is a bug tracker, not a chat. Please stay on topic.

**Comment by pridhvi10** [comment]
Hello,I'm a newbie and I have the exact same problem as jhonson145 .I tried to install xposed onto the dell venue 8 7840 and now it's stuck on the intel logo.neither wiping the cache partition nor hard reset seem to solve the issue.Its just stuck on the intel logo.please help.

**Comment by Xstar97** [comment]
@pridhvi10
Flash the uninstaller zip

**Comment by pridhvi10** [comment]
Could you explain that step by step?I'm new to android.thanks.

**Comment by Xstar97** [comment]
@pridhvi10
1. Download the uninstaller zip onto your pc from http://dl-xda.xposed.info/framework/uninstaller/

2. Move the zip file to your microSD card & Boot into your custom recovery.

3. Flash the uninstaller zip file
Clear cache & reboot.

Please note I am trying to keep this short & sweet, but if this explanation wasn't easy for you then please YouTube it for further questions/instructions.

**Comment by pridhvi10** [comment]
Thanks a lot.I'm grateful.☺️😊

**Comment by pridhvi10** [comment]
Hello nothing seems to be working.the tablet doesn't even seem to connect to a pc.it keeps installing device drives forever.doesnt even read the sd card.please help.will installing a factory rom help?

**Comment by Xstar97** [comment]
@pridhvi10
This is not the place to ask that...Please go to xda(http://forum.xda-developers.com/member.php?u=5961712) & shoot me a pm with your device info so I can help you further there...

**Comment by KonstaT** [comment]
FYI there's a custom build of Xposed (sdk22, x86, v81) that's reported working on Intel Cherry Trail devices running stock Android and stock Remix OS. It was likely built against Intel's ART modifications. http://amiduos.com/support/knowledge-base/article/xposed-framework-support-in-amiduos

Regular Xposed builds are reported working on Intel Cherry Trail devices running my CM12.1/CM13 builds so this is not an issue with x86 architecture itself.

**Comment by oJacko** [comment]
^^ I took a wild shot in the dark and I managed to successfully install "amiduos-xposed.zip"(Xposed framework specifically developed for amiduOS) On my Ares Nextbook 8 NXA8QC116 stock lolipop 5.1.1 Rom, after trying countless other official and non official modiffied xposed versions, the amiduos package was the only one that did NOT bootloop, after flashing with TWRP 3.0.2 suprisingly itz running great no hicups with 27 modules running strong. So I think the answer lies in amiduos-xposed.zip, what made me try was realizing that my amiduOS 2.0.8 setup on win10 runs lolipop 5.1.1 and plays nice with xposed and all modules I throw at it, whats really weird is my device is x86 while my amiduOS is 64bit and its running on the tablet like it was made for it, just something u might wanna look into, as it not only suprised me but left me completely shocked once I installed many modules and still dident loop it runs flawlessly!

**Comment by LestatAb** [comment]
Hi, any update about this issue? I have a 7840 and get temp cwm on android 5.0.1, flash stock 5.1, flash supersu and flash xposed x86 sdk22 v87 and gets bootloop.
Tks!

**Comment by waheed-shah** [comment]
Sir i try to install xposed installer in my samsung device but ever time he give error of framework how cuold i install this application plz help me

**Comment by xstar97** [comment]
@waheed-shah
Check out this link -> https://www.google.com/amp/s/forum.xda-developers.com/xposed/unofficial-xposed-samsung-lollipop-t3180960/amp/
