### ISSUE TITLE
Bootloop on ASUS MeMO Pad 7 (ME176CX) latest update (5.0, not 5.1 like others)

### ISSUE THREAD

**Issue by jerbear64** [rovo89/Xposed#78]
A recent hotfix to Lollipop on our device has broken Xposed. Unfortunately I'm not home and won't be until late tonight so I can't get a log of the bootloop, but I do have a copy of app-process32 from the update.

What's strange is that this is 5.0, not even 5.1 which seems to have been broken.

https://drive.google.com/file/d/0ByKdwmtWgoKBQkFTVE40QWVvaFU/view?usp=sharing is the app_process32 file. If logs are needed I'll be able to capture one tomorrow morning.

**Comment by rovo89** [comment]
This should be fixed with version 78.
