### ISSUE TITLE
FC of Second Screen on LG V10

### ISSUE THREAD

**Issue by viperboy** [rovo89/Xposed#80]
Although this device is a 5.1.1 64bit device, I don't believe the issue to be related to the architecture. This doesn't happen without Xposed and this FC is reproducible by making a phone call and it will constantly FC. This was tested using xposed-v75-sdk22-arm64.zip Here is the relevant log:

11-03 16:11:41.490 29950 29950 E AndroidRuntime: FATAL EXCEPTION: main

11-03 16:11:41.490 29950 29950 E AndroidRuntime: Process: com.lge.signboard, PID: 29950

11-03 16:11:41.490 29950 29950 E AndroidRuntime: android.view.InflateException: Binary XML file line #2: Error inflating class com.android.incallui.coneui.ConeLayout

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:757)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:482)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:668)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(<Xposed>)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	at com.lge.lgewidgetlib.LgeRemoteViews.applyForCustomView(LgeRemoteViews.java:150)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	at com.lge.lgewidgetlib.LgeRemoteViews.apply(LgeRemoteViews.java:49)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	at com.lge.signboard.eventlistener.ItemCall.applyNoitification(ItemCall.java:53)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	at com.lge.signboard.eventlistener.LayerCall.addNotification(LayerCall.java:45)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	at com.lge.signboard.eventlistener.EventGroup.onNotificationAddeded(EventGroup.java:297)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	at com.lge.signboard.eventlistener.EventListenerService$4$1.handleMessage(EventListenerService.java:281)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:135)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5421)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.incallui.coneui.ConeLayout" on path: DexPathList[[zip file "/system/framework/com.lge.mdm.jar", zip file "/system/priv-app/LGInCallUI/LGInCallUI.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:571)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	... 19 more

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	Suppressed: java.io.IOException: Entry not found

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 		at dalvik.system.DexFile.openDexFileNative(Native Method)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 		at dalvik.system.DexFile.openDexFile(DexFile.java:295)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 		at dalvik.system.DexFile.<init>(DexFile.java:80)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 		at dalvik.system.DexFile.<init>(DexFile.java:59)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 		at dalvik.system.DexPathList.loadDexFile(DexPathList.java:262)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 		at dalvik.system.DexPathList.makeDexElements(DexPathList.java:231)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 		at dalvik.system.DexPathList.<init>(DexPathList.java:109)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 		at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 		at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:65)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 		at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:57)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 		at android.app.LoadedApk.getClassLoader(LoadedApk.java:410)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 		at de.robv.android.xposed.XposedBridge$4.afterHookedMethod(XposedBridge.java:250)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 		at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:682)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 		at android.app.LoadedApk.<init>(<Xposed>)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 		at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1811)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 		at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1772)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 		at android.app.ContextImpl.createApplicationContext(ContextImpl.java:2281)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 		at android.content.ContextWrapper.createApplicationContext(ContextWrapper.java:684)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 		at com.lge.lgewidgetlib.LgeRemoteViews.prepareContextForCustomView(LgeRemoteViews.java:93)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 		at com.lge.lgewidgetlib.LgeRemoteViews.applyForCustomView(LgeRemoteViews.java:141)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 		... 13 more

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	Caused by: java.io.IOException: Failed to open file '/data/dalvik-cache/arm/system@priv-app@LGInCallUI@LGInCallUI.apk@classes.dex': Permission denied

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 		... 33 more

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 	Suppressed: java.lang.ClassNotFoundException: com.android.incallui.coneui.ConeLayout

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 		at java.lang.Class.classForName(Native Method)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)

11-03 16:11:41.490 29950 29950 E AndroidRuntime: 		at java.lang.Boot

Here are the 2 files mentioned in the log: https://www.dropbox.com/sh/b3lvzh7z2uyybbq/AACpDFK5PGyYD6Zzk1nBFuWDa?dl=0

Let me know if I can help with this.

**Comment by rovo89** [comment]
Could you please try if the latest version (v79) fixes this?

**Comment by rovo89** [comment]
Closed due to the lack of feedback.

**Comment by bimzcy** [comment]
The latest version (v79) has not fixed this.
