### ISSUE TITLE
Xposed breaks my ZTE A450

### ISSUE THREAD

**Issue by timofonic** [rovo89/Xposed#82]
Hello 

I tried to install Xposed many time ago, but I can't do it successfully. It nearly bricked my rom, but fortunately I was able to restore it.

I want to know what could happen and provide feedback to fix this issue if possible. I'm a novice, but lease ask and I will provide all needed information and make all required tests  on my system (with a rom backup, of course).

Kind regards.

**Comment by rovo89** [comment]
With "brick", I assume you mean a bootloop? In this case, please execute "adb logcat -v time > logcat.txt" while it keeps rebooting, wait for 1-2 minutes and then press Ctrl+C. Then upload the file or use pastebin and post the link here.

**Comment by timofonic** [comment]
I'm very busy, but wanted to explain it before forgetting the issue.

I'll backup the ROM and my SD card this weekend and try it again, I don't
want to lose my data again ;)

Thanks a lot for your support!

**Comment by rovo89** [comment]
Closing this due to the lack of response.
