### ISSUE TITLE
Xposed v75 bootloop with November security patch

### ISSUE THREAD

**Issue by ALIRAQI** [rovo89/Xposed#84]
Hi 
I'm using Zenfone 2 with 5.0, Asus recently released update that included latest security patch with other fixes
I included app_process32 from latest update .139 and previous update .97 
http://pc.cd/KidrtalK

I'll flash the ROM again and get you a logcat 

Thanks :)

**Comment by ALIRAQI** [comment]
logcat 
http://pastebin.com/337Pm0jd

**Comment by rovo89** [comment]
This should be fixed with version 78.
