### ISSUE TITLE
Missing Build instructions 

### ISSUE THREAD

**Issue by renaudcerrato** [rovo89/Xposed#86]
I'd love to contribute to the Xposed Framework, but I'm missing build instructions.  

I'm rather used to JNI/native stuffs, but looking at the Makefiles it seems the build relies on AOSP headers (and probably native shared libraries). 

I'm not really sure how to setup the right dev environment to kick off. 

Any hints?

**Comment by rovo89** [comment]
Check this: https://github.com/rovo89/XposedTools

**Comment by renaudcerrato** [comment]
Thanks! Sorry for the noise...
ᐧ
