### ISSUE TITLE
SDK23: error creating XModuleResources

### ISSUE THREAD

**Issue by C3C0** [rovo89/Xposed#87]
Getting this error within handleInitPackageResources when trying to construct XModuleResources.
XModuleResources modRes = XModuleResources.createInstance(GravityBox.MODULE_PATH, resparam.res);

Result:
11-15 19:52:49.745 I/Xposed  ( 6195): GB:ModSettings: C3C0: MODULE_PATH=/data/app/com.ceco.marshmallow.gravitybox-1/base.apk
11-15 19:52:49.752 E/Xposed  ( 6195): java.lang.NoSuchMethodError: android.content.res.ResourcesKey(java.lang.String,java.lang.Integer,null,
java.lang.Float,null)#bestmatch
11-15 19:52:49.752 E/Xposed  ( 6195):   at de.robv.android.xposed.XposedHelpers.findConstructorBestMatch(XposedHelpers.java:469)
11-15 19:52:49.752 E/Xposed  ( 6195):   at de.robv.android.xposed.XposedHelpers.findConstructorBestMatch(XposedHelpers.java:476)
11-15 19:52:49.752 E/Xposed  ( 6195):   at de.robv.android.xposed.XposedHelpers.newInstance(XposedHelpers.java:1032)
11-15 19:52:49.752 E/Xposed  ( 6195):   at android.app.AndroidAppHelper.createResourcesKey(AndroidAppHelper.java:95)
11-15 19:52:49.752 E/Xposed  ( 6195):   at android.app.AndroidAppHelper.addActiveResource(AndroidAppHelper.java:113)
11-15 19:52:49.752 E/Xposed  ( 6195):   at android.content.res.XModuleResources.createInstance(XModuleResources.java:33)
11-15 19:52:49.752 E/Xposed  ( 6195):   at com.ceco.marshmallow.gravitybox.ModSettings.initPackageResources(ModSettings.java:36)
11-15 19:52:49.752 E/Xposed  ( 6195):   at com.ceco.marshmallow.gravitybox.GravityBox.handleInitPackageResources(GravityBox.java:87)
11-15 19:52:49.752 E/Xposed  ( 6195):   at de.robv.android.xposed.IXposedHookInitPackageResources$Wrapper.handleInitPackageResources(IXposed
HookInitPackageResources.java:20)

**Comment by C3C0** [comment]
Sorry, issue should probably go to XposedBridge repo instead.

**Comment by HashBang173** [comment]
Try it with v78: http://forum.xda-developers.com/showpost.php?p=63842241&postcount=26

**Comment by rovo89** [comment]
Yes, I think it should be fixed now. I just made sure that the call works though - I hope that everything behind this will work as well.
