### ISSUE TITLE
xperia c3 dual

### ISSUE THREAD

**Issue by raghed** [rovo89/Xposed#91]
when install xposed sdk22 v78 arm my phone restart until i deleted the xposed this is log for xposed

11-18 20:16:11.163 I/Xposed  (  591): -----------------
11-18 20:16:11.163 I/Xposed  (  591): Starting Xposed version 78, compiled for SDK 22
11-18 20:16:11.163 I/Xposed  (  591): Device: D2502 (Sony), Android version 5.1.1 (SDK 22)
11-18 20:16:11.163 I/Xposed  (  591): ROM: 19.4.A.0.182
11-18 20:16:11.163 I/Xposed  (  591): Build fingerprint: Sony/D2502/D2502:5.1.1/19.4.A.0.182/26220503:user/release-keys
11-18 20:16:11.163 I/Xposed  (  591): Platform: armeabi-v7a, 32-bit binary, system server: yes
11-18 20:16:11.163 I/Xposed  (  591): SELinux enabled: yes, enforcing: yes
11-18 20:16:12.175 I/Xposed  (  591): -----------------
11-18 20:16:12.175 I/Xposed  (  591): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
11-18 20:16:50.454 I/Xposed  (  591): Detected ART runtime
11-18 20:16:50.458 I/Xposed  (  591): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
11-18 20:16:50.724 E/Xposed  (  591): Cannot load any modules because /data/data/de.robv.android.xposed.installer/conf/modules.list was not found
11-18 20:16:51.989 F/libc    ( 1561): Fatal signal 11 (SIGSEGV), code 1, fault addr 0xe3d1d5d0 in tid 1562 (Compiler driver)
11-18 20:16:51.989 F/libc    ( 1561): Fatal signal 11 (SIGSEGV), code 1, fault addr 0xca8de9a8 in tid 1563 (Compiler driver)
11-18 20:16:51.990 F/libc    ( 1561): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8d4d9ee8 in tid 1561 (main)
11-18 20:16:51.990 F/libc    ( 1561): Fatal signal 11 (SIGSEGV), code 1, fault addr 0xccf68b18 in tid 1564 (Compiler driver)
11-18 20:16:52.119 I/DEBUG   (  558): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-18 20:16:52.119 I/DEBUG   (  558): UUID: 00b6a4e6-142a-4bfb-b53b-32a771390573
11-18 20:16:52.119 I/DEBUG   (  558): Build fingerprint: 'Sony/D2502/D2502:5.1.1/19.4.A.0.182/26220503:user/release-keys'
11-18 20:16:52.119 I/DEBUG   (  558): Revision: '0'
11-18 20:16:52.119 I/DEBUG   (  558): ABI: 'arm'
11-18 20:16:52.120 I/DEBUG   (  558): pid: 1561, tid: 1562, name: Compiler driver  >>> /system/bin/dex2oat <<<
11-18 20:16:52.120 I/DEBUG   (  558): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xe3d1d5d0
11-18 20:16:52.140 I/DEBUG   (  558):     r0 b2204ee0  r1 b2201dd0  r2 b2204e70  r3 8c6c61bc
11-18 20:16:52.140 I/DEBUG   (  558):     r4 8c6c61bd  r5 000075ef  r6 b6ed3a5c  r7 0001d7bc
11-18 20:16:52.140 I/DEBUG   (  558):     r8 b2201cdc  r9 b732f908  sl b7325998  fp b73345b0
11-18 20:16:52.140 I/DEBUG   (  558):     ip b6ed3a74  sp b2201c10  lr b6cb8e09  pc b6cb8d5e  cpsr 800f0030
11-18 20:16:52.141 I/DEBUG   (  558): 
11-18 20:16:52.141 I/DEBUG   (  558): backtrace:
11-18 20:16:52.141 I/DEBUG   (  558):     #00 pc 000d8d5e  /system/lib/libart.so (art::ClassLinker::ResolveType(art::DexFile const&, unsigned short, art::Handle<art::mirror::DexCache>, art::Handle<art::mirror::ClassLoader>)+89)
11-18 20:16:52.141 I/DEBUG   (  558):     #01 pc 00146d5b  /system/lib/libart-compiler.so
11-18 20:16:52.141 I/DEBUG   (  558):     #02 pc 0013c931  /system/lib/libart-compiler.so
11-18 20:16:52.141 I/DEBUG   (  558):     #03 pc 00235693  /system/lib/libart.so (art::ThreadPoolWorker::Run()+34)
11-18 20:16:52.141 I/DEBUG   (  558):     #04 pc 00235ee1  /system/lib/libart.so (art::ThreadPoolWorker::Callback(void*)+52)
11-18 20:16:52.141 I/DEBUG   (  558):     #05 pc 00013693  /system/lib/libc.so (__pthread_start(void*)+30)
11-18 20:16:52.141 I/DEBUG   (  558):     #06 pc 000115bf  /system/lib/libc.so (__start_thread+6)
11-18 20:16:52.387 I/DEBUG   (  558): 
11-18 20:16:52.387 I/DEBUG   (  558): Tombstone written to: /data/tombstones/tombstone_07
11-18 20:16:52.439 E/DEBUG   (  558): unexpected waitpid response: n=1563, status=0000000b
11-18 20:16:52.439 E/DEBUG   (  558): tid exited before attach completed: tid 1563
11-18 20:16:52.533 F/libc    ( 1565): Fatal signal 6 (SIGABRT), code -6 in tid 1565 (main)
11-18 20:16:52.635 I/DEBUG   (  558): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-18 20:16:52.635 I/DEBUG   (  558): UUID: 8e8f6505-0c8d-41c7-8464-bc83f7dab199
11-18 20:16:52.635 I/DEBUG   (  558): Build fingerprint: 'Sony/D2502/D2502:5.1.1/19.4.A.0.182/26220503:user/release-keys'
11-18 20:16:52.635 I/DEBUG   (  558): Revision: '0'
11-18 20:16:52.635 I/DEBUG   (  558): ABI: 'arm'
11-18 20:16:52.635 I/DEBUG   (  558): pid: 1565, tid: 1565, name: main  >>> /system/bin/dex2oat <<<
11-18 20:16:52.635 I/DEBUG   (  558): signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
11-18 20:16:52.662 I/DEBUG   (  558): Abort message: 'art/runtime/thread.cc:1143] No pending exception expected: java.lang.ArrayIndexOutOfBoundsException: length=75; index=27206'
11-18 20:16:52.662 I/DEBUG   (  558):     r0 00000000  r1 0000061d  r2 00000006  r3 00000000
11-18 20:16:52.662 I/DEBUG   (  558):     r4 b6f49e38  r5 00000006  r6 00000002  r7 0000010c
11-18 20:16:52.662 I/DEBUG   (  558):     r8 00000000  r9 b8352d78  sl b835d1a0  fp 00000083
11-18 20:16:52.662 I/DEBUG   (  558):     ip 0000061d  sp bedbfc18  lr b69d9f11  pc b69fff28  cpsr 600f0010
11-18 20:16:52.662 I/DEBUG   (  558): 
11-18 20:16:52.662 I/DEBUG   (  558): backtrace:
11-18 20:16:52.662 I/DEBUG   (  558):     #00 pc 00039f28  /system/lib/libc.so (tgkill+12)
11-18 20:16:52.663 I/DEBUG   (  558):     #01 pc 00013f0d  /system/lib/libc.so (pthread_kill+52)
11-18 20:16:52.663 I/DEBUG   (  558):     #02 pc 00014b2b  /system/lib/libc.so (raise+10)
11-18 20:16:52.663 I/DEBUG   (  558):     #03 pc 00011255  /system/lib/libc.so (__libc_android_abort+36)
11-18 20:16:52.663 I/DEBUG   (  558):     #04 pc 0000f5fc  /system/lib/libc.so (abort+4)
11-18 20:16:52.663 I/DEBUG   (  558):     #05 pc 0021bb3d  /system/lib/libart.so (art::Runtime::Abort()+160)
11-18 20:16:52.663 I/DEBUG   (  558):     #06 pc 000a8357  /system/lib/libart.so (art::LogMessage::~LogMessage()+1066)
11-18 20:16:52.663 I/DEBUG   (  558):     #07 pc 0022a705  /system/lib/libart.so (art::Thread::AssertNoPendingException() const+368)
11-18 20:16:52.663 I/DEBUG   (  558):     #08 pc 000d81e7  /system/lib/libart.so (art::ClassLinker::FindClass(art::Thread*, char const*, art::Handle<art::mirror::ClassLoader>)+14)
11-18 20:16:52.663 I/DEBUG   (  558):     #09 pc 000d8d8b  /system/lib/libart.so (art::ClassLinker::ResolveType(art::DexFile const&, unsigned short, art::Handle<art::mirror::DexCache>, art::Handle<art::mirror::ClassLoader>)+134)
11-18 20:16:52.663 I/DEBUG   (  558):     #10 pc 00146d5b  /system/lib/libart-compiler.so
11-18 20:16:52.663 I/DEBUG   (  558):     #11 pc 0013c931  /system/lib/libart-compiler.so
11-18 20:16:52.663 I/DEBUG   (  558):     #12 pc 00235979  /system/lib/libart.so (art::ThreadPool::Wait(art::Thread*, bool, bool)+172)
11-18 20:16:52.663 I/DEBUG   (  558):     #13 pc 0013f6e7  /system/lib/libart-compiler.so
11-18 20:16:52.663 I/DEBUG   (  558):     #14 pc 0013fbf9  /system/lib/libart-compiler.so (art::CompilerDriver::Resolve(_jobject*, std::__1::vector<art::DexFile const*, std::__1::allocator<art::DexFile const*> > const&, art::ThreadPool*, art::TimingLogger*)+200)
11-18 20:16:52.663 I/DEBUG   (  558):     #15 pc 001495c5  /system/lib/libart-compiler.so (art::CompilerDriver::PreCompile(_jobject*, std::__1::vector<art::DexFile const*, std::__1::allocator<art::DexFile const*> > const&, art::ThreadPool*, art::TimingLogger*)+60)
11-18 20:16:52.663 I/DEBUG   (  558):     #16 pc 0014a505  /system/lib/libart-compiler.so (art::CompilerDriver::CompileAll(_jobject*, std::__1::vector<art::DexFile const*, std::__1::allocator<art::DexFile const*> > const&, art::TimingLogger*)+68)
11-18 20:16:52.663 I/DEBUG   (  558):     #17 pc 0000b4fd  /system/bin/dex2oat
11-18 20:16:52.663 I/DEBUG   (  558):     #18 pc 0000d9fd  /system/bin/dex2oat
11-18 20:16:52.663 I/DEBUG   (  558):     #19 pc 0000f4b9  /system/lib/libc.so (__libc_init+44)
11-18 20:16:52.663 I/DEBUG   (  558):     #20 pc 00004cd8  /system/bin/dex2oat
11-18 20:16:52.812 I/DEBUG   (  558): 
11-18 20:16:52.812 I/DEBUG   (  558): Tombstone written to: /data/tombstones/tombstone_01
11-18 20:16:52.864 F/libc    ( 1569): Fatal signal 11 (SIGSEGV), code 2, fault addr 0x45cdbcdc in tid 1571 (Compiler driver)
11-18 20:16:52.864 F/libc    ( 1569): Fatal signal 11 (SIGSEGV), code 2, fault addr 0x2ea2e114 in tid 1569 (main)
11-18 20:16:52.865 F/libc    ( 1569): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x6047bcf8 in tid 1572 (Compiler driver)
11-18 20:16:52.866 F/libc    ( 1569): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x64d89358 in tid 1570 (Compiler driver)
11-18 20:16:52.966 I/DEBUG   (  558): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-18 20:16:52.966 I/DEBUG   (  558): UUID: 285530d1-98fa-4442-b879-1e1050ae2fe8
11-18 20:16:52.966 I/DEBUG   (  558): Build fingerprint: 'Sony/D2502/D2502:5.1.1/19.4.A.0.182/26220503:user/release-keys'
11-18 20:16:52.966 I/DEBUG   (  558): Revision: '0'
11-18 20:16:52.966 I/DEBUG   (  558): ABI: 'arm'
11-18 20:16:52.966 I/DEBUG   (  558): pid: 1569, tid: 1571, name: Compiler driver  >>> /system/bin/dex2oat <<<
11-18 20:16:52.966 I/DEBUG   (  558): signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x45cdbcdc
11-18 20:16:52.978 I/DEBUG   (  558):     r0 b2601770  r1 b24fcdd0  r2 b2601700  r3 64db695b
11-18 20:16:52.978 I/DEBUG   (  558):     r4 64db695c  r5 0000786c  r6 b6f3ea5c  r7 0001e1b0
11-18 20:16:52.978 I/DEBUG   (  558):     r8 b24fccdc  r9 b70b0950  sl b70a6a20  fp b70b5e98
11-18 20:16:52.979 I/DEBUG   (  558):     ip b6f3ea74  sp b24fcc10  lr b6d23e09  pc b6d23d5e  cpsr 00070030
11-18 20:16:52.979 I/DEBUG   (  558): 
11-18 20:16:52.979 I/DEBUG   (  558): backtrace:
11-18 20:16:52.979 I/DEBUG   (  558):     #00 pc 000d8d5e  /system/lib/libart.so (art::ClassLinker::ResolveType(art::DexFile const&, unsigned short, art::Handle<art::mirror::DexCache>, art::Handle<art::mirror::ClassLoader>)+89)
11-18 20:16:52.979 I/DEBUG   (  558):     #01 pc 00146d5b  /system/lib/libart-compiler.so
11-18 20:16:52.979 I/DEBUG   (  558):     #02 pc 0013c931  /system/lib/libart-compiler.so
11-18 20:16:52.979 I/DEBUG   (  558):     #03 pc 00235693  /system/lib/libart.so (art::ThreadPoolWorker::Run()+34)
11-18 20:16:52.979 I/DEBUG   (  558):     #04 pc 00235ee1  /system/lib/libart.so (art::ThreadPoolWorker::Callback(void*)+52)
11-18 20:16:52.979 I/DEBUG   (  558):     #05 pc 00013693  /system/lib/libc.so (__pthread_start(void*)+30)
11-18 20:16:52.979 I/DEBUG   (  558):     #06 pc 000115bf  /system/lib/libc.so (__start_thread+6)
11-18 20:16:53.224 I/DEBUG   (  558): 
11-18 20:16:53.224 I/DEBUG   (  558): Tombstone written to: /data/tombstones/tombstone_08
11-18 20:16:53.275 E/DEBUG   (  558): unexpected waitpid response: n=1569, status=0000000b
11-18 20:16:53.275 E/DEBUG   (  558): tid exited before attach completed: tid 1569

**Comment by rovo89** [comment]
> No pending exception expected: java.lang.ArrayIndexOutOfBoundsException: length=75; index=27206'

See #64
