### ISSUE TITLE
Support Xiaomi Redmi Note 2 / MIUI 7

### ISSUE THREAD

**Issue by devnoname120** [rovo89/Xposed#93]
I'm trying to install Xposed on my Xiaomi Redmi Note 2 Prime Edition device, which is running MIUI 7 version 5.11.12 (Android 5.0.2). Yet, when I launch Xposed's installer (version 2.7.1), an error is displayed:

![screenshot_2015-11-22-21-38-40_de robv android xposed installer_1448224759185](https://cloud.githubusercontent.com/assets/2824100/11326147/8c8ddb30-9161-11e5-8087-a5fba9cd7092.jpg)

I also tried to use WSM Tools which is an unofficial fork designed to work on Xiaomi devices running MIUI, but it yields the same error (and on a side note it has not been updated since MIUI 5).

Would it be possible to support this phone / OS ?

Thank you for your help.

**Comment by rovo89** [comment]
As with every Lollipop/Marshmallow ROM, you will need Xposed Installer 3.0 (see XDA).
