### ISSUE TITLE
Not booting - HTC butterfly3 HTV31

### ISSUE THREAD

**Issue by sprint-w** [rovo89/Xposed#95]
Stuck at bootanimation.

HTC butterfly3 HTV31
Android 5.0.2

I tried 2 version of Xposed.
Xposed v78 sdk21 arm64
[v78_logcat.txt](https://github.com/rovo89/Xposed/files/48015/v78_logcat.txt)
Xposed v79-test sdk21 arm64 from issue #88 
[v79test_logcat.txt](https://github.com/rovo89/Xposed/files/48016/v79test_logcat.txt)

Please check attached log.

**Comment by rovo89** [comment]
Can you please get another logcat with the test version, but this time clear the Dalvik cache before?

**Comment by sprint-w** [comment]
Yes I cleared cache and Dalvik cache.
I will get new logcat then upload it.(about 5min?)

(I'm using temporary twrp recovery. Is it problem? It's overwrite boot section.
See  http://forum.xda-developers.com/butterfly-3/development/guide-rooting-guide-twrp-2-8-7-0-t3251434)

**Comment by sprint-w** [comment]
60min

**Comment by sprint-w** [comment]
about 3 hour.
And down low battery.
I can't uplode it too big.

**Comment by sprint-w** [comment]
Oops.
I could not upload log.
Try it again.

**Comment by sprint-w** [comment]
I lost a log.
I will try it towmorow.

**Comment by rovo89** [comment]
I was a little bit confused about the other comments you posted before and that are deleted now. Keep in mind that 206 people watch this repository and get one email per comment you post. Therefore, just take your time and post when you're ready. Also, the first 5-10 minutes of logcat after clearing the Dalvik cache and booting the device for the first time should be enough, then you can press Ctrl+C. No need to capture several hours.

**Comment by sprint-w** [comment]
Really sorry.
I will take care in future.

[logcat2.txt](https://github.com/rovo89/Xposed/files/49222/logcat2.txt)

**Comment by rovo89** [comment]
Please check #88, several others have the same issue.

**Comment by sprint-w** [comment]
@rovo89 Thank you! I'm looking forward it.
