### ISSUE TITLE
Android in bootloop after install xposed-v78-sdk22-arm64.zip

### ISSUE THREAD

**Issue by tigerwood** [rovo89/Xposed#98]
After installing Xposed with android 5.1 system, the pad doesn't boot. logs in attached, please help on it, thanks!
if you need more information, please just let me know, thanks!

[log8.txt](https://github.com/rovo89/Xposed/files/63712/log8.txt)

**Comment by rovo89** [comment]
Sorry, but I don't see any issues in the logcat you attached. It ends when the system is still busy compiling system apps. So it looks to me like you just didn't wait long enough. Please do the same thing again, but wait at least 10-15 minutes for the first boot. If it still doesn't show the "Android is optimizing apps" screen by then, please take a new logcat and post it.

**Comment by rovo89** [comment]
Please use the new version 79 when you try again.

**Comment by tigerwood** [comment]
still on the boot screen, i find some log about xposed is,
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm64/services.odex needs to be recompiled with Xposed for /system/framework/services.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm64/ethernet-service.odex needs to be recompiled with Xposed for /system/framework/ethernet-service.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm64/wifi-service.odex needs to be recompiled with Xposed for /system/framework/wifi-service.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm/com.mediatek.effect.odex needs to be recompiled with Xposed for /system/framework/com.mediatek.effect.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm/com.android.location.provider.odex needs to be recompiled with Xposed for /system/framework/com.android.location.provider.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm/com.android.future.usb.accessory.odex needs to be recompiled with Xposed for /system/framework/com.android.future.usb.accessory.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm/javax.obex.odex needs to be recompiled with Xposed for /system/framework/javax.obex.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm/android.test.runner.odex needs to be recompiled with Xposed for /system/framework/android.test.runner.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm/com.android.media.remotedisplay.odex needs to be recompiled with Xposed for /system/framework/com.android.media.remotedisplay.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm/com.android.mediadrm.signer.odex needs to be recompiled with Xposed for /system/framework/com.android.mediadrm.signer.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm64/com.mediatek.effect.odex needs to be recompiled with Xposed for /system/framework/com.mediatek.effect.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm64/com.android.location.provider.odex needs to be recompiled with Xposed for /system/framework/com.android.location.provider.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm64/com.android.future.usb.accessory.odex needs to be recompiled with Xposed for /system/framework/com.android.future.usb.accessory.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm64/javax.obex.odex needs to be recompiled with Xposed for /system/framework/javax.obex.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm64/android.test.runner.odex needs to be recompiled with Xposed for /system/framework/android.test.runner.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm64/com.android.media.remotedisplay.odex needs to be recompiled with Xposed for /system/framework/com.android.media.remotedisplay.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm64/com.android.mediadrm.signer.odex needs to be recompiled with Xposed for /system/framework/com.android.mediadrm.signer.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm/CustomPropInterface.odex needs to be recompiled with Xposed for /system/framework/CustomPropInterface.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm/MultiWindowProxy.odex needs to be recompiled with Xposed for /system/framework/MultiWindowProxy.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm/am.odex needs to be recompiled with Xposed for /system/framework/am.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm/appops.odex needs to be recompiled with Xposed for /system/framework/appops.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm/appwidget.odex needs to be recompiled with Xposed for /system/framework/appwidget.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm/bmgr.odex needs to be recompiled with Xposed for /system/framework/bmgr.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm/bu.odex needs to be recompiled with Xposed for /system/framework/bu.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm/content.odex needs to be recompiled with Xposed for /system/framework/content.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm/dpm.odex needs to be recompiled with Xposed for /system/framework/dpm.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm/ime.odex needs to be recompiled with Xposed for /system/framework/ime.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm/input.odex needs to be recompiled with Xposed for /system/framework/input.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm/media_cmd.odex needs to be recompiled with Xposed for /system/framework/media_cmd.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm/monkey.odex needs to be recompiled with Xposed for /system/framework/monkey.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm/pm.odex needs to be recompiled with Xposed for /system/framework/pm.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm/recovery.odex needs to be recompiled with Xposed for /system/framework/recovery.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm/requestsync.odex needs to be recompiled with Xposed for /system/framework/requestsync.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm/settings.odex needs to be recompiled with Xposed for /system/framework/settings.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm/svc.odex needs to be recompiled with Xposed for /system/framework/svc.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm/uiautomator.odex needs to be recompiled with Xposed for /system/framework/uiautomator.jar
I/art     (  967): DexFile_isDexOptNeeded file /system/framework/arm/wm.odex needs to be recompiled with Xposed for /system/framework/wm.jar

and there also some fatal error,
F/libc    ( 2318): Fatal signal 16 (SIGSTKFLT), code 0 in tid 2318 (ndroid.systemui)
F/libc    (  967): Fatal signal 16 (SIGSTKFLT), code 0 in tid 967 (system_server)

please see the log from https://www.dropbox.com/s/991ni0te6xdgpmg/BootLoopLog_xposed-v79-sdk22-arm64.zip?dl=0 for more info. hope this time's log is OK,  anyway please let me know if there any further step or info needed, thanks!

**Comment by tigerwood** [comment]
more log added, can boot into home screen, but operate touch & key did't get any feedback, then system root.
https://www.dropbox.com/s/rhvxo3xopt3f90y/bootToHomeSreen_then_Reboot.zip?dl=0

**Comment by tigerwood** [comment]
here also added the clean log, without the xposed boot log, hope can help a little bit, thanks!
https://www.dropbox.com/s/s3e9ficvd51ifym/NoXposedLog.zip?dl=0

**Comment by rovo89** [comment]
Looks like the issue in #81, please follow up there.
