### ISSUE TITLE
modules.list was not found

### ISSUE THREAD

**Issue by SebiPanther** [rovo89/Xposed#99]
Hello,
i've tryed to install Xposed and Xprivacy on my Motorola Moto G LTE on top of CM13, but Xprivacy says that it can't find the Privacy Services. I've tryed to find a Solution online, but didn't find a solution that works for me. The device is clean installed and i've also that problem with a CM12. Reinstall Xposed or Xprivacy havn't helped. Also Reboot does not give any solution. The Log shows this:

12-16 19:45:32.168 I/Xposed  (  230): -----------------
12-16 19:45:32.168 I/Xposed  (  230): Starting Xposed version 78, compiled for SDK 23
12-16 19:45:32.168 I/Xposed  (  230): Device: XT1039 (motorola), Android version 6.0.1 (SDK 23)
12-16 19:45:32.168 I/Xposed  (  230): ROM: cm_peregrine-userdebug 6.0.1 MMB29M bb3b7e88f5 test-keys
12-16 19:45:32.168 I/Xposed  (  230): Build fingerprint: motorola/peregrine_reteu/peregrine:5.1/LPB23.13-17/18:user/release-keys
12-16 19:45:32.168 I/Xposed  (  230): Platform: armeabi-v7a, 32-bit binary, system server: yes
12-16 19:45:32.168 I/Xposed  (  230): SELinux enabled: yes, enforcing: yes
12-16 19:45:32.180 I/Xposed  (  230): -----------------
12-16 19:45:32.181 I/Xposed  (  230): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
12-16 19:45:32.669 I/Xposed  (  230): Detected ART runtime
12-16 19:45:32.732 I/Xposed  (  230): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
12-16 19:45:33.283 E/Xposed  (  230): Cannot load any modules because /data/data/de.robv.android.xposed.installer/conf/modules.list was not found

I would be thankful for help - thanks for the awesome work! (Also sorry if that is the wrong way to looking for help)

**Comment by wanam** [comment]
Open Xposed Installer, enable your modules and reboot.

**Comment by SebiPanther** [comment]
Thanks - my fault m(
I'm relay sorry ;.;

**Comment by SebiPanther** [comment]
I'm relay sorry ;.;
